# Cloud creation scenario #3b

#colosseum.endpoint			http://192.168.48.135:9000/api
colosseum.endpoint			http://192.168.98.135:9000/api
colosseum.auth.email		john.doe@example.com
colosseum.auth.tenant		admin
colosseum.auth.password		admin

# Pre-configured Id's
id.api								1
id.cloud							1
id.credentials						1
id.app								1
id.app-instance						1

# 1. API info
api.name							EC2Api
api.internalProviderName			aws-ec2

# 2. Cloud info
cloud.name							EC2
cloud.endpoint						http://ec2.eu-west-1.amazonaws.com

# 3. Cloud credentials
credentials.user					********************
credentials.secret					********************
credentials.tenant					1

# 4. Application info
app.name							myAppName

# 5. LC components info
comp[0].init						
comp[0].install						~/melodic/MySQLDB.sh install
comp[0].name						Wordpress_DBConfiguration
comp[0].postInstall					~/melodic/MySQLDB.sh configure
comp[0].postStart					
comp[0].postStop					
comp[0].preInstall					rm -rf ~/melodic && mkdir ~/melodic && cd ~/melodic && wget https://s3-eu-west-1.amazonaws.com/melodic.testing.data/MySQLDB.sh && chmod +x ~/melodic/MySQLDB.sh
comp[0].preStart					
comp[0].preStop						
comp[0].shutdown					
comp[0].start						~/melodic/MySQLDB.sh start
comp[0].startDetection				
comp[0].stop						
comp[0].stopDetection				

comp[1].init						
comp[1].install						~/melodic/MySQLDB.sh install
comp[1].name						Wordpress_WebServerConfiguration
comp[1].postInstall					~/melodic/MySQLDB.sh configure
comp[1].postStart					
comp[1].postStop					
comp[1].preInstall					rm -rf ~/melodic && mkdir ~/melodic && cd ~/melodic && wget https://s3-eu-west-1.amazonaws.com/melodic.testing.data/MySQLDB.sh && chmod +x ~/melodic/MySQLDB.sh
comp[1].preStart					
comp[1].preStop						
comp[1].shutdown					
comp[1].start						~/melodic/MySQLDB.sh start
comp[1].startDetection				
comp[1].stop						
comp[1].stopDetection				

# 6. Application instance creation

# 7. VM templates info
vmt[0].image						64
vmt[0].location						62
vmt[0].hardware						52
vmt[0].templateOptions				

vmt[1].image						94
vmt[1].location						72
vmt[1].hardware						52
vmt[1].templateOptions				

# 8. Application Component-to-VM templates info
ac[0].component						1
ac[0].virtualMachineTemplate		1
ac[0].containerType					

ac[1].component						2
ac[1].virtualMachineTemplate		2
ac[1].containerType					

# 9. VM's info
vm[0].remoteId						
vm[0].remoteState					
vm[0].providerId					
vm[0].swordId						
vm[0].cloudCredentials				
vm[0].owner							
vm[0].location						62
vm[0].name							WM_TwoComponentAppVMInstance_1_10
vm[0].image							64
vm[0].hardware						52
vm[0].templateOptions				

vm[1].remoteId						
vm[1].remoteState					
vm[1].providerId					
vm[1].swordId						
vm[1].cloudCredentials				
vm[1].owner							
vm[1].location						62
vm[1].name							WM_TwoComponentAppVMInstance_2_10
vm[1].image							64
vm[1].hardware						52
vm[1].templateOptions				

vm[2].remoteId						
vm[2].remoteState					
vm[2].providerId					
vm[2].swordId						
vm[2].cloudCredentials				
vm[2].owner							
vm[2].location						72
vm[2].name							WM_TwoComponentAppVMInstance_3_10
vm[2].image							94
vm[2].hardware						52
vm[2].templateOptions				

vm[3].remoteId						
vm[3].remoteState					
vm[3].providerId					
vm[3].swordId						
vm[3].cloudCredentials				
vm[3].owner							
vm[3].location						72
vm[3].name							WM_TwoComponentAppVMInstance_4_10
vm[3].image							94
vm[3].hardware						52
vm[3].templateOptions				

# 10. Provided Ports info
provided[0].name					WordpressDBPort
provided[0].applicationComponent	1
provided[0].port					3306

# 11. Required Ports info
required[0].name					WordpressPortDbReq
required[0].applicationComponent	2
required[0].updateAction			
required[0].isMandatory				true

# 12. Communications info
comm[0].requiredPort				2
comm[0].providedPort				1

# 13. Instances info
instance[0].remoteId				
instance[0].remoteState				
instance[0].providerId				
instance[0].swordId					
instance[0].applicationComponent	1
instance[0].applicationInstance		1
instance[0].virtualMachine			99

instance[1].remoteId				
instance[1].remoteState				
instance[1].providerId				
instance[1].swordId					
instance[1].applicationComponent	1
instance[1].applicationInstance		1
instance[1].virtualMachine			100

instance[2].remoteId				
instance[2].remoteState				
instance[2].providerId				
instance[2].swordId					
instance[2].applicationComponent	2
instance[2].applicationInstance		1
instance[2].virtualMachine			101

instance[3].remoteId				
instance[3].remoteState				
instance[3].providerId				
instance[3].swordId					
instance[3].applicationComponent	2
instance[3].applicationInstance		1
instance[3].virtualMachine			102
