<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cp" nsURI="http://paasage.inria.fr/metamodel/cp" nsPrefix="cp">
  <eClassifiers xsi:type="ecore:EClass" name="CPElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstraintProblem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="goals" upperBound="-1"
        eType="#//Goal" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constants" upperBound="-1"
        eType="#//Constant" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
        eType="#//Variable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//ComparisonExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="auxExpressions" upperBound="-1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true" eSuperTypes="#//CPElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="NumericExpression" abstract="true" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="#//NumericExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="ecore:EClass paasageTypes.ecore#//NumericValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domain" lowerBound="1"
        eType="#//Domain" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Domain" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="NumericDomain" eSuperTypes="#//Domain">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EEnum paasageTypes.ecore#//BasicTypeEnum"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="ecore:EClass paasageTypes.ecore#//NumericValue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RangeDomain" eSuperTypes="#//NumericDomain">
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1" eType="ecore:EClass paasageTypes.ecore#//NumericValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1" eType="ecore:EClass paasageTypes.ecore#//NumericValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumericListDomain" eSuperTypes="#//NumericDomain">
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" lowerBound="1"
        upperBound="-1" eType="ecore:EClass paasageTypes.ecore#//NumericValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constant" eSuperTypes="#//NumericExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EEnum paasageTypes.ecore#//BasicTypeEnum"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="ecore:EClass paasageTypes.ecore#//NumericValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComposedExpression" eSuperTypes="#//NumericExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" lowerBound="2"
        upperBound="-1" eType="#//NumericExpression"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//OperatorEnum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OperatorEnum">
    <eLiterals name="plus"/>
    <eLiterals name="minus" value="1"/>
    <eLiterals name="times" value="2"/>
    <eLiterals name="div" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GoalOperatorEnum">
    <eLiterals name="max" literal="max"/>
    <eLiterals name="min" value="1" literal="min"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ComparatorEnum">
    <eLiterals name="greaterThan"/>
    <eLiterals name="lessThan" value="1"/>
    <eLiterals name="greaterOrEqualTo" value="2"/>
    <eLiterals name="lessOrEqualTo" value="3"/>
    <eLiterals name="equalTo" value="4"/>
    <eLiterals name="different" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComparisonExpression" eSuperTypes="#//BooleanExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="exp1" lowerBound="1" eType="#//Expression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exp2" lowerBound="1" eType="#//Expression"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comparator" lowerBound="1"
        eType="#//ComparatorEnum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Goal" eSuperTypes="#//CPElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//NumericExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="goalType" lowerBound="1"
        eType="#//GoalOperatorEnum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanExpression" abstract="true" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="ListDomain" eSuperTypes="#//Domain">
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" lowerBound="1"
        upperBound="-1" eType="ecore:EClass paasageTypes.ecore#//StringValue" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="ecore:EClass paasageTypes.ecore#//StringValue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MultiRangeDomain" eSuperTypes="#//NumericDomain">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ranges" lowerBound="2"
        upperBound="-1" eType="#//RangeDomain" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnaryExpression" abstract="true" eSuperTypes="#//NumericExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//NumericExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SimpleUnaryOperatorEnum">
    <eLiterals name="abstractValue"/>
    <eLiterals name="lnValue" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ComposedUnaryOperatorEnum">
    <eLiterals name="exponentialValue"/>
    <eLiterals name="logValue" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleUnaryExpression" abstract="true"
      eSuperTypes="#//UnaryExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
        eType="#//SimpleUnaryOperatorEnum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComposedUnaryExpression" abstract="true"
      eSuperTypes="#//UnaryExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
        eType="#//ComposedUnaryOperatorEnum"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanDomain" eSuperTypes="#//Domain"/>
</ecore:EPackage>
