<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="application" nsURI="http://paasage.inria.fr/metamodel/application"
    nsPrefix="application">
  <eClassifiers xsi:type="ecore:EClass" name="PaasageConfiguration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="goals" upperBound="-1"
        eType="#//PaaSageGoal" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="ecore:EClass cp.ecore#//ComparisonExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
        eType="#//PaaSageVariable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" upperBound="-1"
        eType="#//ElasticityRule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//ApplicationComponent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providers" lowerBound="1"
        upperBound="-1" eType="#//Provider" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vmProfiles" upperBound="-1"
        eType="#//VirtualMachineProfile" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="auxExpressions" upperBound="-1"
        eType="ecore:EClass cp.ecore#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vms" upperBound="-1" eType="#//VirtualMachine"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="monitoredDimensions" upperBound="-1"
        eType="#//Dimension"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VirtualMachine" eSuperTypes="paasageTypes.ecore#//typesPaasage/PaaSageCPElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="profile" lowerBound="1"
        eType="#//VirtualMachineProfile"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VirtualMachineProfile" eSuperTypes="#//CloudML_Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" lowerBound="1" eType="ecore:EEnum paasageTypes.ecore#//typesPaasage/VMSizeEnum"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="memory" eType="#//Memory"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="storage" eType="#//Storage"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cpu" eType="#//CPU" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="os" lowerBound="1" eType="ecore:EClass paasageTypes.ecore#//typesPaasage/OS"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="provider" eType="#//ProviderCost"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CloudML_Element" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cloudMLId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Resource" abstract="true" eSuperTypes="paasageTypes.ecore#//typesPaasage/PaaSageCPElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="ecore:EClass paasageTypes.ecore#//NumericValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Memory" eSuperTypes="#//Resource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" eType="ecore:EEnum paasageTypes.ecore#//typesPaasage/DataUnitEnum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Storage" eSuperTypes="#//Resource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" eType="ecore:EEnum paasageTypes.ecore#//typesPaasage/DataUnitEnum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CPU" eSuperTypes="#//Resource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="frequency" eType="ecore:EEnum paasageTypes.ecore#//typesPaasage/FrequencyEnum"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cores" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Provider" eSuperTypes="paasageTypes.ecore#//typesPaasage/PaaSageCPElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" eType="ecore:EClass paasageTypes.ecore#//typesPaasage/Location"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="ecore:EClass paasageTypes.ecore#//typesPaasage/ProviderType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ApplicationComponent" eSuperTypes="#//CloudML_Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vm" eType="#//VirtualMachine"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preferredLocations" upperBound="-1"
        eType="ecore:EClass paasageTypes.ecore#//typesPaasage/Location"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredProfile" eType="#//VirtualMachineProfile"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="profile" lowerBound="1"
        eType="ecore:EClass paasageTypes.ecore#//typesPaasage/ApplicationComponentProfile"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="features" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredFeatures" upperBound="-1"
        eType="#//RequiredFeature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preferredProviders" upperBound="-1"
        eType="ecore:EClass paasageTypes.ecore#//typesPaasage/ProviderType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElasticityRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" lowerBound="1"
        eType="#//Action" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
        eType="#//Condition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameters" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="ecore:EClass paasageTypes.ecore#//typesPaasage/ActionType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Condition" eSuperTypes="cp.ecore#//BooleanExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
        eType="ecore:EEnum paasageTypes.ecore#//typesPaasage/LogicOperatorEnum"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exp1" lowerBound="1" eType="ecore:EClass cp.ecore#//BooleanExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exp2" eType="ecore:EClass cp.ecore#//BooleanExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PaaSageVariable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="paasageType" eType="ecore:EEnum paasageTypes.ecore#//typesPaasage/VariableElementTypeEnum"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relatedElements" lowerBound="1"
        upperBound="-1" eType="#//CloudML_Element"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cpVariableId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PaaSageGoal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="goal" lowerBound="1" eType="ecore:EEnum cp.ecore#//GoalOperatorEnum"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="function" lowerBound="1"
        eType="ecore:EClass paasageTypes.ecore#//typesPaasage/FunctionType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequiredFeature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="feature" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedBy" lowerBound="1"
        eType="#//CloudML_Element"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="remote" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optional" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dimension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProviderCost">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="provider" lowerBound="1"
        eType="#//Provider"/>
  </eClassifiers>
</ecore:EPackage>
