# Cloudiator/Colosseum client configuration 

colosseum.endpoint			http://192.168.98.135:9000/api
#colosseum.endpoint			http://192.168.48.135:9000/api
colosseum.auth.email		john.doe@example.com
colosseum.auth.tenant		admin
colosseum.auth.password		admin

#colosseum.db.driver			com.mysql.cj.jdbc.Driver
##colosseum.db.url			jdbc:mysql://192.168.98.135:3306/colosseum?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#colosseum.db.url			jdbc:mysql://192.168.48.135:3306/colosseum?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#colosseum.db.username		root
#colosseum.db.password		melodic
#colosseum.db.database		colosseum
#
#colosseum.owner-id			1
