# Baguette Server configuration

#coordinator.class = eu.melodic.event.baguette.server.coordinator.ThreeLevelSegmentCoordinator
#coordinator.class = eu.melodic.event.baguette.server.coordinator.TwoLevelCoordinator
coordinator.class = eu.melodic.event.baguette.server.coordinator.NoopCoordinator
#coordinator.class = eu.melodic.event.baguette.server.coordinator.ServerCoordinatorPerCloud

server.port = 2222
server.key.file = hostkey.ser
heartbeat = off
heartbeat.period = 60000

#num-of-vms = 1
registration-window = 30000

# Configuration specific to 'ServerCoordinatorClientsOnly'
#broker.address = 192.168.2.2
#broker.port = 61616
#broker.config.template = /opt/baguette-client/bin/client1.sh.tpl
#broker.config.file = /opt/baguette-client/bin/client1.sh

# Configuration specific to 'ServerCoordinatorPerCloud'
#third-level.address = autodetect
#third-level.address = 192.168.2.2
#third-level.port = 61616

#broker.config.template = /opt/baguette-client/bin/broker1.sh.tpl
#broker.config.file = /opt/baguette-client/bin/broker1.sh
broker.config.template = ./bin/broker1.sh.tpl
broker.config.file = ./bin/broker1.sh
#broker.address-override = 192.168.3.3
broker.port = 61616

#client.config.template = /opt/baguette-client/bin/client1.sh.tpl
#client.config.file = /opt/baguette-client/bin/client1.sh
client.config.template = ./bin/client1.sh.tpl
client.config.file = ./bin/client1.sh
#client.address-override = 34.249.190.70
client.port = 61616


BAGUETTE_CLIENT_DOWNLOAD_URL = https://bitbucket.7bulls.eu/projects/TST/repos/melodic/raw/esper-demo/baguette-client.zip?at=refs%2Fheads%2Fesper-demo

#BAGUETTE_SERVER_HOST = 192.168.2.2
BAGUETTE_SERVER_HOST = 127.0.0.1
BAGUETTE_SERVER_PORT = 2222
BAGUETTE_SERVER_PUBKEY = AAAAB3NzaC1yc2EAAAADAQABAAABAQDKAyYAkXcrRat3qKawSipfZJPsmoGTggin+GIoA/0DJ8xc+3vGYAV0J6EAtDZyFKFYWzWamfpsb08wRGkFTLzXcfW+MRvRYauoAzSFBozKNKq8ycn3x0PIySnZOI3B1SIR9sgJMTyT32QPI8IhxNE78ZPf+rhEaAIjG/T7hnnhkAJ+OvAmhYb3T2x0W2mlmj0JPihUynsoCdQFSt7UARvzG/UIRBmdZ//DRqUn919gf9mLOfQ9zVhrpSq75/cqGwXM1c+UYBYWtnJS2UyWKlMwFe3y6mTtlyWfD3Jn03ZFNCX5q3UDQhcdKj4kMI6xdRn6AnfpfXWPbiK2cMvH9ZXJ
BAGUETTE_SERVER_FINGERPRINT = SHA256:9iANcu6iK6UePw0n1DwKwUTeS8MF2W/ih+lUewXgL0A

BAGUETTE_SERVER_USERNAME = bb
BAGUETTE_SERVER_PASSWORD = yy

BAGUETTE_SERVER_CREDENTIALS_FILE = /opt/baguette-client/conf/baguette-server.credentials
