#
# Copyright (C) 2017 Institute of Communication and Computer Systems (imu.iccs.com)
#
# This Source Code Form is subject to the terms of the
# Mozilla Public License, v. 2.0. If a copy of the MPL
# was not distributed with this file, You can obtain one at
# http://mozilla.org/MPL/2.0/.
#

spring.application.name=EMS

#### REST interface settings ####
server.port=8111
#server.servlet.context-path=/

#### Static Resources ####
#spring.resources.staticLocations=${MELODIC_CONFIG_DIR}/html