#
# Copyright (C) 2017 Institute of Communication and Computer Systems (imu.iccs.com)
#
# This Source Code Form is subject to the terms of the
# Mozilla Public License, v. 2.0. If a copy of the MPL
# was not distributed with this file, You can obtain one at
# http://mozilla.org/MPL/2.0/.
#

control.esb-url =
control.metasolver-configuration-url = http://localhost:8092/updateSubscriptions

### Debug settings - Deactivate processing modules
#control.skip-translation = true
#control.skip-mvv-retrieve = true
#control.skip-broker-cep = true
#control.skip-baguette = true
control.skip-metasolver = true
control.skip-esb-notification = true
control.upperware-grouping = GLOBAL

### Debug settings - Load/Save translation results
control.tc-load-file = _TC.json
control.tc-save-file = _TC.json

### Debug settings - Enable event debugging
control.event-debug-enabled = true

### Process CAMEL model on start-up
#control.preload.camel-model = /camel-new
#control.preload.camel-model = /mytest5
#control.preload.camel-model = /older/TrafficSimulationUF
#control.preload.camel-model = /CRM
#control.preload.camel-model = /TrafficSimulationUF
control.preload.camel-model = /FCRnew

### Use CP model on start-up
#control.preload.cp-model = /cpModelTest
control.preload.cp-model = /FCRnew_cpModelTest