# Baguette Server configuration

# Coordinator and Registration settings
baguette.server.coordinator.class = eu.melodic.event.baguette.server.coordinator.TestCoordinator
#coordinator.class = eu.melodic.event.baguette.server.coordinator.ServerCoordinatorPerCloud

#   Available Coordinators (in 'eu.melodic.event.baguette.server.coordinator' package) :
#     ServerCoordinatorWaitAll, ServerCoordinatorTimeWin, ServerCoordinatorClientsOnly,
#     ServerCoordinatorPerCloud, ThreeLevelSegmentCoordinator, TwoLevelCoordinator

#baguette.server.num-of-instances = 1
baguette.server.registration-window = 30000

# SSH Server settings
baguette.server.port = 2222
baguette.server.key.file = ${MELODIC_CONFIG_DIR}/hostkey.ser
baguette.server.heartbeat = off
baguette.server.heartbeat.period = 60000



baguette.server.third-level.address = autodetect
#third-level.address = 192.168.2.2
baguette.server.third-level.port = 61616

baguette.server.broker.address = 192.168.2.2
baguette.server.broker.port = 61616
baguette.server.broker.config.template = /opt/baguette-client/bin/client1.sh.tpl
baguette.server.broker.config.file = /opt/baguette-client/bin/client1.sh
#baguette.server.broker.address.override = 192.168.3.3

baguette.server.client.config.template = ./bin/client1.sh.tpl
baguette.server.client.config.file = ./bin/client1.sh
#baguette.server.client.address.override = 34.249.190.70
baguette.server.client.port = 61616
