#
# Copyright (C) 2017 Institute of Communication and Computer Systems (imu.iccs.com)
#
# This Source Code Form is subject to the terms of the
# Mozilla Public License, v. 2.0. If a copy of the MPL
# was not distributed with this file, You can obtain one at
# http://mozilla.org/MPL/2.0/.
#

### URLs of Upperware services being invoked by EMS
control.esb-url =
control.metasolver-configuration-url = http://localhost:8092/updateConfiguration

################################################################################
### Debug settings - Deactivate processing modules
#control.skip-translation = true
#control.skip-mvv-retrieve = true
#control.skip-broker-cep = true
#control.skip-baguette = true
#control.skip-metasolver = true
#control.skip-esb-notification = true
control.upperware-grouping = GLOBAL

### Debug settings - Load/Save translation results
control.tc-load-file = _TC.json
control.tc-save-file = _TC.json

### Debug settings - Enable event debugging
control.event-debug-enabled = true

################################################################################
### Process CAMEL model on start-up
#control.preload.camel-model = /camel-new
#control.preload.camel-model = /mytest5
#control.preload.camel-model = /older/TrafficSimulationUF
#control.preload.camel-model = /CRM
#control.preload.camel-model = /TrafficSimulationUF
###########control.preload.camel-model = /FCRnew

### Use CP model on start-up
#control.preload.cp-model = /cpModelTest
###########control.preload.cp-model = /FCRnew_cpModelTest


################################################################################
### Web configuration - Port
server.port = 8111

### Web configuration - HTTPS
#server.ssl.key-store=${MELODIC_CONFIG_DIR}/broker-keystore.p12
#server.ssl.key-store-password=melodic
#server.ssl.keyStoreType=PKCS12
#server.ssl.keyAlias=localhost

### Web configuration - API key
#web.api-key.value=generate
#web.api-key.value=1234567890
#web.api-key.header=EMS-API-KEY
#web.api-key.parameter=ems-api-key

### Web configuration - Resources
static.favicon.path=classpath:/public/favicon.ico
#static.resource.path=file:${MELODIC_CONFIG_DIR}/resources/
static.resource.path=file:/opt/ems-server/resources/
static.resource.context=/resources/**
#static.resource.redirect=/resources/index.html

# Effective only if 'control.event-debug-enabled' is 'true'
event-debug.resource.path=classpath:/public/
event-debug.resource.context=/event-debug/**
static.resource.redirect=/event-debug/index.html

### Other settings
control.exit-allowed = false
control.exit-grace-period = 10
control.exit-code = 0

control.password-encoder = eu.passage.upperware.commons.passwords.IdentityPasswordEncoder

### Hawtio web console settings
management.endpoints.web.exposure.include=hawtio,jolokia
management.endpoints.web.base-path=/
#management.endpoints.web.path-mapping.hawtio=hawtio/console

hawtio.authenticationEnabled=false
#hawtio.realm=activemq
#hawtio.role=admins
#hawtio.rolePrincipalClasses=org.apache.activemq.jaas.GroupPrincipal

#hawtio.proxyWhitelist=

#jolokia.config.debug=false
#endpoints.jolokia.sensitive = false
#endpoints.jolokia.enabled=true
#endpoints.jolokia.path=/jolokia
#spring.jmx.enabled=true
#endpoints.jmx.enabled=true
#management.port=9001
#management.address=127.0.0.1