#
# Copyright (C) 2017 Institute of Communication and Computer Systems (imu.iccs.com)
#
# This Source Code Form is subject to the terms of the
# Mozilla Public License, v. 2.0. If a copy of the MPL
# was not distributed with this file, You can obtain one at
# http://mozilla.org/MPL/2.0/.
#

# Common and non-SSL Broker settings
#brokercep.broker-name = broker
#brokercep.connector-port = 1099
brokercep.broker-url = tcp://localhost:61616
# Don't use in Upperware
#brokercep.bypass-local-broker = true

# SSL Broker settings
#brokercep.ssl.enable = false
#brokercep.broker-url = ssl://localhost:61616
brokercep.broker-url-properties = transport.daemon=true&transport.trace=false&transport.useKeepAlive=true&transport.useInactivityMonitor=false&transport.needClientAuth=${brokercep.ssl.client-auth.required}&transport.verifyHostName=false
brokercep.ssl.client-auth.required = true
# Key store
brokercep.ssl.truststore.file = ${MELODIC_CONFIG_DIR}/broker-truststore.p12
brokercep.ssl.truststore.type = PKCS12
brokercep.ssl.truststore.password = melodic
# Trust store
brokercep.ssl.keystore.file = ${MELODIC_CONFIG_DIR}/broker-keystore.p12
brokercep.ssl.keystore.type = PKCS12
brokercep.ssl.keystore.password = melodic

# Authentication and Authorization settings
brokercep.authentication-enabled = false
brokercep.additional-broker-credentials = aaa/111, bbb/222
brokercep.authorization-enabled = false

# Broker instance settings
brokercep.broker-persistence-enabled = false
brokercep.broker-using-jmx = true
brokercep.broker-advisory-support-enabled = true
brokercep.broker-using-shutdown-hook = false

brokercep.broker-enable-statistics = true
brokercep.broker-populate-jmsx-user-id = true

# Memory usage limit
brokercep.usage.memory.jvm-heap-percentage = 20
#brokercep.usage.memory.size = 134217728