#
# Copyright (C) 2017 Institute of Communication and Computer Systems (imu.iccs.com)
#
# This Source Code Form is subject to the terms of the
# Mozilla Public License, v. 2.0. If a copy of the MPL
# was not distributed with this file, You can obtain one at
# http://mozilla.org/MPL/2.0/.
#

# JWT authentication configuration for EMS
jwt.secret=mE1odiCl0ud
jwt.expirationTime=86400000
jwt.refreshTokenExpirationTime=86400000

#melodic user
user.username=myUsername
user.password=myPassword