#
# Copyright (C) 2017 Institute of Communication and Computer Systems (imu.iccs.com)
#
# This Source Code Form is subject to the terms of the
# Mozilla Public License, v. 2.0. If a copy of the MPL
# was not distributed with this file, You can obtain one at
# http://mozilla.org/MPL/2.0/.
#

# Baguette Client installation utilities configuration

# OS families
baguette.client.install.osFamilies.LINUX=CENTOS,DARWIN,DEBIAN,FEDORA ,FREEBSD ,GENTOO,COREOS,AMZN_LINUX,MANDRIVA ,NETBSD,OEL ,OPENBSD,RHEL,SCIENTIFIC,CEL,SLACKWARE,SOLARIS,SUSE,TURBOLINUX,CLOUD_LINUX,UBUNTU
baguette.client.install.osFamilies.WINDOWS=WINDOWS

baguette.client.install.baseDir=/opt/baguette-client
baguette.client.install.mkdirs=${baguette.client.install.baseDir}/bin,${baguette.client.install.baseDir}/conf,${baguette.client.install.baseDir}/logs
baguette.client.install.touchFiles=${baguette.client.install.baseDir}/logs/output.log
baguette.client.install.checkInstalledFile=${baguette.client.install.baseDir}/conf/ok.txt

baguette.client.install.downloadUrl=++++++ ${random.uuid} +++++++/resources
baguette.client.install.apiKey=1234567890
baguette.client.install.installScriptUrl=${baguette.client.install.downloadUrl}/install.sh
baguette.client.install.installScriptFile=${baguette.client.install.baseDir}/bin/install.sh

baguette.client.install.credentialsTempFile=/tmp/baguette-server.credentials
baguette.client.install.credentialsFile=${baguette.client.install.baseDir}/conf/baguette-server.credentials
baguette.client.install.clientConfigFile=${baguette.client.install.baseDir}/conf/baguette-client.properties
baguette.client.install.clientConfigTemplateFile=${MELODIC_CONFIG_DIR}/credentials.tpl
