#
# Copyright (C) 2017-2022 Institute of Communication and Computer Systems (imu.iccs.gr)
#
# This Source Code Form is subject to the terms of the Mozilla Public License, v2.0, unless
# Esper library is used, in which case it is subject to the terms of General Public License v2.0.
# If a copy of the MPL was not distributed with this file, you can obtain one at
# https://www.mozilla.org/en-US/MPL/2.0/
#

# Broker ports and protocol
#brokercep.broker-name = broker
brokercep.broker-port = 61617
#brokercep.connector-port = 1099
brokercep.broker-protocol = ssl
# Don't use in Upperware
#brokercep.bypass-local-broker = true

# Common Broker settings
#brokercep.ssl.enable = false
brokercep.broker-url = ${brokercep.broker-protocol}://0.0.0.0:${brokercep.broker-port}
brokercep.broker-url-2 = tcp://0.0.0.0:61616?${brokercep.broker-url-properties}
brokercep.broker-url-3 = stomp://0.0.0.0:61610
brokercep.broker-url-properties = transport.daemon=true&transport.trace=false&transport.useKeepAlive=true&transport.useInactivityMonitor=false&transport.needClientAuth=${brokercep.ssl.client-auth.required}&transport.verifyHostName=true&transport.connectionTimeout=0&transport.keepAlive=true
brokercep.ssl.client-auth.required = false
brokercep.broker-url-for-consumer = tcp://${IP_SETTING}:61616?daemon=true&trace=false&useInactivityMonitor=false&connectionTimeout=0&keepAlive=true
brokercep.broker-url-for-clients = ${brokercep.broker-protocol}://${IP_SETTING}:${brokercep.broker-port}?daemon=true&trace=false&useInactivityMonitor=false&connectionTimeout=0&keepAlive=true
# Must be a public IP address

# Key store
brokercep.ssl.keystore-file = ${MELODIC_CONFIG_DIR}/ems-keystore.p12
brokercep.ssl.keystore-type = PKCS12
#brokercep.ssl.keystore-password = melodic
brokercep.ssl.keystore-password = ENC(ISMbn01HVPbtRPkqm2Lslg==)
# Trust store
brokercep.ssl.truststore-file = ${MELODIC_CONFIG_DIR}/ems-truststore.p12
brokercep.ssl.truststore-type = PKCS12
#brokercep.ssl.truststore-password = melodic
brokercep.ssl.truststore-password = ENC(ISMbn01HVPbtRPkqm2Lslg==)
# Certificate
brokercep.ssl.certificate-file = ${MELODIC_CONFIG_DIR}/ems.crt
# Key-and-Cert data
brokercep.ssl.key-entry-generate = ALWAYS
brokercep.ssl.key-entry-name = ems
brokercep.ssl.key-entry-dname = CN=ems,OU=Information Management Unit (IMU),O=Institute of Communication and Computer Systems (ICCS),L=Athens,ST=Attika,C=GR
brokercep.ssl.key-entry-ext-san = dns:localhost,ip:127.0.0.1,ip:${DEFAULT_IP},ip:${PUBLIC_IP}

# Authentication and Authorization settings
brokercep.authentication-enabled = true
#brokercep.additional-broker-credentials = aaa/111, bbb/222, morphemic/morphemic
brokercep.additional-broker-credentials = ENC(axeJUxNHajYfBffUwvuT3kwTgLTpRliDMz/ZQ9hROZ3BNOv0Idw72NJsawzIZRuZ)
brokercep.authorization-enabled = false

# Broker instance settings
brokercep.broker-persistence-enabled = false
brokercep.broker-using-jmx = true
brokercep.broker-advisory-support-enabled = true
brokercep.broker-using-shutdown-hook = false

brokercep.broker-enable-statistics = true
brokercep.broker-populate-jmsx-user-id = true

# Message interceptors
brokercep.message-interceptors[0].destination = >
brokercep.message-interceptors[0].className = eu.melodic.event.brokercep.broker.interceptor.SequentialCompositeInterceptor
brokercep.message-interceptors[0].params[0] = #SourceAddressMessageUpdateInterceptor
brokercep.message-interceptors[0].params[1] = #MessageForwarderInterceptor

brokercep.message-interceptors-specs.SourceAddressMessageUpdateInterceptor.className = eu.melodic.event.brokercep.broker.interceptor.SourceAddressMessageUpdateInterceptor
brokercep.message-interceptors-specs.MessageForwarderInterceptor.className = eu.melodic.event.brokercep.broker.interceptor.MessageForwarderInterceptor

# Message forward destinations (MessageForwarderInterceptor must be included in 'message-interceptors' property)
#brokercep.message-forward-destinations[0].connection-string = tcp://localhost:51515
#brokercep.message-forward-destinations[0].username = AAA
#brokercep.message-forward-destinations[0].password = 111
#brokercep.message-forward-destinations[1].connection-string = tcp://localhost:41414
#brokercep.message-forward-destinations[1].username = AAA
#brokercep.message-forward-destinations[1].password = 111

# Advisory watcher
brokercep.enable-advisory-watcher = true

# Memory usage limit
brokercep.usage.memory.jvm-heap-percentage = 20
#brokercep.usage.memory.size = 134217728
