variables:
  DOCKER_PUSH: "false"
  LOCAL_REPO: "127.0.0.1:5000"
  DOCKER_REPO: "gitlab.ow2.org:4567"
  MAVEN_IMAGE: "maven:3.6.3-jdk-8"
  DOCKER_DIND_IMAGE: "docker:19.03.1"
  DOCKER_DIND_SERVICE: "$DOCKER_DIND_IMAGE-dind"
  DOCKER_DRIVER: overlay
  DOCKER_TLS_CERTDIR: "/certs"

  MAVEN_OPTS: "-Xmx2048m -Xms2048m"
  SKIP_TESTS: "true"

  DOCKER_CLI: "docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $CI_PROJECT_DIR/maven_repo:/root/.m2 -w /usr/src/mymaven -v $CI_PROJECT_DIR:/usr/src/mymaven --env-file .env.list $MAVEN_IMAGE"
  MELODIC_UPPERWARE_CLI: "mvn --batch-mode -N -Dmaven.test.skip=$SKIP_TESTS -f pom.xml"
  UPPERWARE_METAMODEL_CLI: "mvn --batch-mode -N -Dmaven.test.skip=$SKIP_TESTS -f upperware_metamodel/pom.xml"
  JWT_COMMONS_CLI: "mvn --batch-mode -N -Dmaven.test.skip=$SKIP_TESTS -f jwt-commons/pom.xml"
  MELODIC_COMMONS_CLI: "mvn --batch-mode -N -Dmaven.test.skip=$SKIP_TESTS -f melodic-commons/pom.xml"
  MELODIC_CACHE_CLI: "mvn --batch-mode -N -Dmaven.test.skip=$SKIP_TESTS -f melodic-cache/pom.xml"

  JWT_SERVER_CLI: "mvn --batch-mode -N -Dmaven.test.skip=$SKIP_TESTS -Ddocker.push=false -f jwt-server/pom.xml"
  UTILITY_GENERATOR_CLI: "mvn --batch-mode -N -Dmaven.test.skip=$SKIP_TESTS -f utility-generator/pom.xml"

  ZPP_SOLVER_CLI: "mvn --batch-mode -N -Dmaven.test.skip=$SKIP_TESTS -f zpp-solver/pom.xml"

  ADAPTER_SERVER_CLI: "mvn --batch-mode -N -Dmaven.test.skip=$SKIP_TESTS -Ddocker.push=false -f adapter/pom.xml"
  CP_GENERATOR_CLI: "mvn --batch-mode -N -Dmaven.test.skip=$SKIP_TESTS -Ddocker.push=false -U -f cp_generator/pom.xml"

  CP_PARSER_CLI: "mvn --batch-mode -N -Dmaven.test.skip=$SKIP_TESTS -Ddocker.push=false -f zpp-solver/cp-parser/pom.xml"
  CP_SOLVER_CLI: "mvn --batch-mode -N -Dmaven.test.skip=$SKIP_TESTS -Ddocker.push=false -f cp-solver/pom.xml"
  GEN_SOLVER_CLI: "mvn --batch-mode -N -Dmaven.test.skip=$SKIP_TESTS -Ddocker.push=false -f zpp-solver/genetic-solver/pom.xml"
  NC_SOLVER_CLI: "mvn --batch-mode -N -Dmaven.test.skip=$SKIP_TESTS -Ddocker.push=false -f zpp-solver/node-candidates-solver/pom.xml"
  PT_SOLVER_CLI: "mvn --batch-mode -N -Dmaven.test.skip=$SKIP_TESTS -Ddocker.push=false -f zpp-solver/pt-solver/pom.xml"
  MCTS_SOLVER_CLI: "mvn --batch-mode -N -Dmaven.test.skip=$SKIP_TESTS -Ddocker.push=false -f zpp-solver/mcts-solver/pom.xml"

  EMS_CLI: "mvn --batch-mode -Dmaven.test.skip=$SKIP_TESTS -Ddocker.push=false -f event-management/pom.xml"
  EMS_UTIL_CLI: "mvn --batch-mode -N -Dmaven.test.skip=$SKIP_TESTS -Ddocker.push=false -f event-management/util/pom.xml"
  EMS_BROKER_CLIENT_CLI: "mvn --batch-mode -N -Dmaven.test.skip=$SKIP_TESTS -Ddocker.push=false -f event-management/broker-client/pom.xml"
  EMS_BROKER_CEP_CLI: "mvn --batch-mode -N -Dmaven.test.skip=$SKIP_TESTS -Ddocker.push=false -f event-management/broker-cep/pom.xml"
  EMS_BAGUETTE_CLIENT_CLI: "mvn --batch-mode -N -Dmaven.test.skip=$SKIP_TESTS -Ddocker.push=false -f event-management/baguette-client/pom.xml"
  EMS_BAGUETTE_CLIENT_INSTALL_CLI: "mvn --batch-mode -N -Dmaven.test.skip=$SKIP_TESTS -Ddocker.push=false -f event-management/baguette-client-install/pom.xml"
  EMS_BAGUETTE_SERVER_CLI: "mvn --batch-mode -N -Dmaven.test.skip=$SKIP_TESTS -Ddocker.push=false -f event-management/baguette-server/pom.xml"
  EMS_TRANSLATOR_CLI: "mvn --batch-mode -N -Dmaven.test.skip=$SKIP_TESTS -Ddocker.push=false -f event-management/translator/pom.xml"
  EMS_SERVER_CLI: "mvn --batch-mode -N -Dmaven.test.skip=$SKIP_TESTS -Ddocker.push=false -f event-management/control-service/pom.xml"

  METASOLVER_CLI: "mvn --batch-mode -N -Dmaven.test.skip=$SKIP_TESTS -Ddocker.push=false -f meta_solver/pom.xml"
  MQ_ADAPTER_CLI: "mvn --batch-mode -N -Dmaven.test.skip=$SKIP_TESTS -Ddocker.push=false -f mq-http-adapter/pom.xml"
  GUI_BACKEND_CLI: "mvn --batch-mode -N -Dmaven.test.skip=$SKIP_TESTS -Ddocker.push=false -U -f gui-backend/pom.xml"

  FUNCTIONIZER_TESTING_TOOL_CLI: "mvn --batch-mode -N -Dmaven.test.skip=$SKIP_TESTS -Ddocker.push=false -f functionizer-testing-tool/pom.xml"

cache:
  paths:
    - maven_repo/

before_script:
  - mkdir -p $HOME/.m2
  - echo '<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
    https://maven.apache.org/xsd/settings-1.0.0.xsd">
    <localRepository>'$CI_PROJECT_DIR'/maven_repo</localRepository>
    </settings>' > $HOME/.m2/settings.xml
  - echo "MAVEN_OPTS=$MAVEN_OPTS" > $CI_PROJECT_DIR/.env.list

after_script:
  - echo '=========================================================================='
  - docker image ls
  - echo '=========================================================================='

stages:
  - build-basic-dependencies
  - build-required-part1
  - build-required-part2
  - build-required-part3
  - build-required-part4
  - build-required-part5
  - build-required-part6
  - build-required-part7
  - build-required-part8
  - build
  - deploy
  - deploy-solvers-part1
  - deploy-solvers-part2
  - deploy-solvers-part3
  - deploy-solvers-part4

build-basic-dependencies:melodic-upperware:
  stage: build-basic-dependencies
  image: $MAVEN_IMAGE
  script:
    - $MELODIC_UPPERWARE_CLI -Pwithout-docker clean install
  artifacts:
    expire_in: 1 week
    paths:
      - /builds/melodic/melodic-upperware/maven_repo/org/ow2/paasage/upperware/

build-required-part1:upperware-metamodel:
  stage: build-required-part1
  image: $MAVEN_IMAGE
  script:
    - $UPPERWARE_METAMODEL_CLI -Pwithout-docker clean install
  artifacts:
    expire_in: 1 week
    paths:
      - /builds/melodic/melodic-upperware/maven_repo/org/ow2/paasage/upperware-metamodel/

build-required-part2:jwt-commons:
  stage: build-required-part2
  image: $MAVEN_IMAGE
  script:
    - $JWT_COMMONS_CLI -Pwithout-docker clean install
  artifacts:
    expire_in: 1 week
    paths:
      - /builds/melodic/melodic-upperware/maven_repo/org/ow2/paasage/jwt-commons/

build-required-part2:melodic-commons:
  stage: build-required-part2
  image: $MAVEN_IMAGE
  script:
    - $MELODIC_COMMONS_CLI -Pwithout-docker clean install
  artifacts:
    expire_in: 1 week
    paths:
      - /builds/melodic/melodic-upperware/maven_repo/org/ow2/paasage/melodic-commons/

build-required-part3:melodic-cache:
  stage: build-required-part3
  image: $MAVEN_IMAGE
  script:
    - $MELODIC_CACHE_CLI -Pwithout-docker clean install
  artifacts:
    expire_in: 1 week
    paths:
      - /builds/melodic/melodic-upperware/maven_repo/org/ow2/paasage/melodic-cache/

build-required-part3:zpp-solver:
  stage: build-required-part3
  image: $MAVEN_IMAGE
  script:
    - $ZPP_SOLVER_CLI -Pwithout-docker clean install
  artifacts:
    expire_in: 1 week
    paths:
      - /builds/melodic/melodic-upperware/maven_repo/org/ow2/paasage/zpp-solver/


build-required-part3:ems:
  stage: build-required-part3
  image: $MAVEN_IMAGE
  script:
    - $EMS_CLI -Pwithout-docker clean install
  artifacts:
    expire_in: 1 week
    paths:
      - $CI_PROJECT_DIR/event-management/bin
      - $CI_PROJECT_DIR/event-management/config-files
      - $CI_PROJECT_DIR/event-management/util/target
      - $CI_PROJECT_DIR/event-management/translator/target
      - $CI_PROJECT_DIR/event-management/broker-client/target
      - $CI_PROJECT_DIR/event-management/broker-cep/target
      - $CI_PROJECT_DIR/event-management/baguette-client/target
      - $CI_PROJECT_DIR/event-management/baguette-client-install/target
      - $CI_PROJECT_DIR/event-management/baguette-server/target
      - $CI_PROJECT_DIR/event-management/control-service/target
      - $CI_PROJECT_DIR/event-management/control-service/src/main/resources/public


build-required-part4:ems-util:
  stage: build-required-part4
  image: $MAVEN_IMAGE
  script:
    - $EMS_UTIL_CLI -Pwithout-docker clean install
  artifacts:
    paths:
      - /builds/melodic/melodic-upperware/maven_repo/eu/melodic/event/util/

build-required-part5:utility-generator:
  stage: build-required-part5
  image: $MAVEN_IMAGE
  script:
    - $UTILITY_GENERATOR_CLI -Pwithout-docker clean install
  artifacts:
    expire_in: 1 week
    paths:
      - /builds/melodic/melodic-upperware/maven_repo/eu/melodic/utility-generator/

build-required-part5:ems-broker-cep:
  stage: build-required-part5
  image: $MAVEN_IMAGE
  script:
    - $EMS_BROKER_CEP_CLI -Pwithout-docker clean install
  artifacts:
    paths:
      - /builds/melodic/melodic-upperware/maven_repo/eu/melodic/event/broker-cep/

build-required-part6:ems-baguette-server:
  stage: build-required-part6
  image: $MAVEN_IMAGE
  script:
    - $EMS_BAGUETTE_SERVER_CLI -Pwithout-docker clean install
  artifacts:
    paths:
      - /builds/melodic/melodic-upperware/maven_repo/eu/melodic/event/baguette-server/

build-required-part6:cp-solver:
  stage: build-required-part6
  image: $MAVEN_IMAGE
  script:
    - $CP_SOLVER_CLI -Pwithout-docker clean install
  artifacts:
    expire_in: 1 week
    paths:
      - /builds/melodic/melodic-upperware/maven_repo/eu/melodic/cp-solver/

build-required-part7:ems-baguette-client-install:
  stage: build-required-part7
  image: $MAVEN_IMAGE
  script:
    - $EMS_BAGUETTE_CLIENT_INSTALL_CLI -Pwithout-docker clean install
  artifacts:
    paths:
      - /builds/melodic/melodic-upperware/maven_repo/eu/melodic/event/baguette-client-install/
#
build-required-part7:ems-broker-client:
  stage: build-required-part7
  image: $MAVEN_IMAGE
  script:
    - $EMS_BROKER_CLIENT_CLI -Pwithout-docker clean install
  artifacts:
    paths:
      - /builds/melodic/melodic-upperware/maven_repo/eu/melodic/event/broker-client/
#
build-required-part7:ems-translator:
  stage: build-required-part7
  image: $MAVEN_IMAGE
  script:
    - $EMS_TRANSLATOR_CLI -Pwithout-docker clean install
  artifacts:
    paths:
      - /builds/melodic/melodic-upperware/maven_repo/eu/melodic/event/translator/

build-required-part8:ems-baguette-client:
  stage: build-required-part8
  image: $MAVEN_IMAGE
  script:
    - $EMS_BAGUETTE_CLIENT_CLI -Pwithout-docker clean install
  artifacts:
    paths:
      - /builds/melodic/melodic-upperware/maven_repo/eu/melodic/event/baguette-client/

build:cp-parser:
  stage: build
  image: $MAVEN_IMAGE
  script:
    - $CP_PARSER_CLI -Pwithout-docker clean install
  artifacts:
    expire_in: 1 week
    paths:
      - /builds/melodic/melodic-upperware/maven_repo/eu/melodic/cp-parser/

build:ems-server:
  stage: build
  image: $MAVEN_IMAGE
  script:
    - $EMS_SERVER_CLI -Pwithout-docker clean install
  artifacts:
    paths:
      - /builds/melodic/melodic-upperware/maven_repo/eu/melodic/event-management/control-service/

build:ems-server:
  stage: build
  image: $MAVEN_IMAGE
  script:
    - $EMS_SERVER_CLI -Pwithout-docker clean install
  artifacts:
    paths:
    - $CI_PROJECT_DIR/event-management/control-service/target

deploy:melodic-upperware:
  stage: deploy
  only:
    - morphemic-rc3.0
  image: $DOCKER_DIND_IMAGE
  services:
    - $DOCKER_DIND_SERVICE
  dependencies:
    - build-basic-dependencies:melodic-upperware
  script:
    - $DOCKER_CLI $MELODIC_UPPERWARE_CLI deploy

deploy:upperware-metamodel:
  stage: deploy
  only:
    - morphemic-rc3.0
  image: $DOCKER_DIND_IMAGE
  services:
    - $DOCKER_DIND_SERVICE
  dependencies:
    - build-required-part1:upperware-metamodel
  script:
    - $DOCKER_CLI $UPPERWARE_METAMODEL_CLI deploy

deploy:jwt-commons:
  stage: deploy
  only:
    - morphemic-rc3.0
  image: $DOCKER_DIND_IMAGE
  services:
    - $DOCKER_DIND_SERVICE
  dependencies:
    - build-required-part2:jwt-commons
  script:
    - $DOCKER_CLI $JWT_COMMONS_CLI deploy

deploy:melodic-commons:
  stage: deploy
  only:
    - morphemic-rc3.0
  image: $DOCKER_DIND_IMAGE
  services:
    - $DOCKER_DIND_SERVICE
  dependencies:
    - build-required-part2:melodic-commons
  script:
    - $DOCKER_CLI $MELODIC_COMMONS_CLI deploy

deploy:melodic-cache:
  stage: deploy
  only:
    - morphemic-rc3.0
  image: $DOCKER_DIND_IMAGE
  services:
    - $DOCKER_DIND_SERVICE
  dependencies:
    - build-required-part3:melodic-cache
  script:
    - $DOCKER_CLI $MELODIC_CACHE_CLI deploy

deploy:jwt-server:
  stage: deploy
  only:
    - morphemic-rc3.0
  image: $DOCKER_DIND_IMAGE
  services:
    - $DOCKER_DIND_SERVICE
  script:
    - $DOCKER_CLI $JWT_SERVER_CLI -Ddocker.imagePrefix=melodic/ clean install
    - echo "$K8S_SECRET_DOCKER_PASSWORD" | docker login $CI_REGISTRY -u $K8S_SECRET_DOCKER_USER --password-stdin
    - docker tag $LOCAL_REPO/melodic/jwtserver:unknown $CI_REGISTRY_IMAGE/jwt-server:$CI_COMMIT_BRANCH
    - docker push $CI_REGISTRY_IMAGE/jwt-server:$CI_COMMIT_BRANCH

deploy:utility-generator:
  stage: deploy
  only:
    - morphemic-rc3.0
  image: $DOCKER_DIND_IMAGE
  services:
    - $DOCKER_DIND_SERVICE
  dependencies:
    - build-required-part5:utility-generator
    - build-required-part3:melodic-cache
  script:
    - $DOCKER_CLI $UTILITY_GENERATOR_CLI deploy

deploy:zpp-solver:
  stage: deploy
  only:
    - morphemic-rc3.0
  image: $DOCKER_DIND_IMAGE
  services:
    - $DOCKER_DIND_SERVICE
  dependencies:
    - build-required-part3:zpp-solver
  script:
    - $DOCKER_CLI $ZPP_SOLVER_CLI deploy

deploy:adapter:
  stage: deploy
  only:
    - morphemic-rc3.0
  image: $DOCKER_DIND_IMAGE
  services:
    - $DOCKER_DIND_SERVICE
  script:
    - $DOCKER_CLI $ADAPTER_SERVER_CLI -Ddocker.imagePrefix=melodic/ clean install
    - echo "$K8S_SECRET_DOCKER_PASSWORD" | docker login $CI_REGISTRY -u $K8S_SECRET_DOCKER_USER --password-stdin
    - docker tag $LOCAL_REPO/melodic/adapter:unknown $CI_REGISTRY_IMAGE/adapter:$CI_COMMIT_BRANCH
    - docker push $CI_REGISTRY_IMAGE/adapter:$CI_COMMIT_BRANCH

deploy:cp-generator:
  stage: deploy
  only:
    - morphemic-rc3.0
  image: $DOCKER_DIND_IMAGE
  services:
    - $DOCKER_DIND_SERVICE
  script:
    - $DOCKER_CLI $CP_GENERATOR_CLI -Ddocker.imagePrefix=melodic/ clean install
    - echo "$K8S_SECRET_DOCKER_PASSWORD" | docker login $CI_REGISTRY -u $K8S_SECRET_DOCKER_USER --password-stdin
    - docker tag $LOCAL_REPO/melodic/generator:unknown $CI_REGISTRY_IMAGE/generator:$CI_COMMIT_BRANCH
    - docker push $CI_REGISTRY_IMAGE/generator:$CI_COMMIT_BRANCH

deploy:cp-solver:
  stage: deploy
  only:
    - morphemic-rc3.0
  image: $DOCKER_DIND_IMAGE
  dependencies:
    - build-required-part6:cp-solver
  services:
    - $DOCKER_DIND_SERVICE
  script:
    - $DOCKER_CLI $CP_SOLVER_CLI -Ddocker.imagePrefix=melodic/ clean install
    - echo "$K8S_SECRET_DOCKER_PASSWORD" | docker login $CI_REGISTRY -u $K8S_SECRET_DOCKER_USER --password-stdin
    - docker tag $LOCAL_REPO/melodic/cpsolver:unknown $CI_REGISTRY_IMAGE/cpsolver:$CI_COMMIT_BRANCH
    - docker push $CI_REGISTRY_IMAGE/cpsolver:$CI_COMMIT_BRANCH
    - $DOCKER_CLI $CP_SOLVER_CLI deploy

deploy:ems-server:
  stage: deploy
  only:
    - morphemic-rc3.0
  image: $DOCKER_DIND_IMAGE
  dependencies:
    - build-required-part3:ems
  services:
    - $DOCKER_DIND_SERVICE
  script:
    - $DOCKER_CLI $EMS_CLI -Ddocker.imagePrefix=melodic/ clean install
    - echo "$K8S_SECRET_DOCKER_PASSWORD" | docker login $CI_REGISTRY -u $K8S_SECRET_DOCKER_USER --password-stdin
    - docker tag $LOCAL_REPO/melodic/ems-server:UNKNOWN $CI_REGISTRY_IMAGE/ems-server:$CI_COMMIT_BRANCH
    - docker push $CI_REGISTRY_IMAGE/ems-server:$CI_COMMIT_BRANCH

deploy:metasolver:
  stage: deploy
  only:
    - morphemic-rc3.0
  image: $DOCKER_DIND_IMAGE
  services:
    - $DOCKER_DIND_SERVICE
  script:
    - $DOCKER_CLI $METASOLVER_CLI -Ddocker.imagePrefix=melodic/ clean install
    - echo "$K8S_SECRET_DOCKER_PASSWORD" | docker login $CI_REGISTRY -u $K8S_SECRET_DOCKER_USER --password-stdin
    - docker tag $LOCAL_REPO/melodic/metasolver:unknown $CI_REGISTRY_IMAGE/metasolver:$CI_COMMIT_BRANCH
    - docker push $CI_REGISTRY_IMAGE/metasolver:$CI_COMMIT_BRANCH

deploy:mq-adapter:
  stage: deploy
  only:
    - morphemic-rc3.0
  image: $DOCKER_DIND_IMAGE
  services:
    - $DOCKER_DIND_SERVICE
  script:
    - $DOCKER_CLI $MQ_ADAPTER_CLI -Ddocker.imagePrefix=melodic/ clean install
    - echo "$K8S_SECRET_DOCKER_PASSWORD" | docker login $CI_REGISTRY -u $K8S_SECRET_DOCKER_USER --password-stdin
    - docker tag $LOCAL_REPO/melodic/mq-http-adapter:unknown $CI_REGISTRY_IMAGE/mq-http-adapter:$CI_COMMIT_BRANCH
    - docker push $CI_REGISTRY_IMAGE/mq-http-adapter:$CI_COMMIT_BRANCH

deploy:gui-backend:
  stage: deploy
  only:
    - morphemic-rc3.0
  image: $DOCKER_DIND_IMAGE
  services:
    - $DOCKER_DIND_SERVICE
  script:
    - $DOCKER_CLI $GUI_BACKEND_CLI -Ddocker.imagePrefix=melodic/ clean install -U
    - echo "$K8S_SECRET_DOCKER_PASSWORD" | docker login $CI_REGISTRY -u $K8S_SECRET_DOCKER_USER --password-stdin
    - docker tag $LOCAL_REPO/melodic/gui-backend:unknown $CI_REGISTRY_IMAGE/gui-backend:$CI_COMMIT_BRANCH
    - docker push $CI_REGISTRY_IMAGE/gui-backend:$CI_COMMIT_BRANCH

#deploy:functionizer-testing-tool:
#  stage: deploy
#  only:
#    - master
#    - rc3.0
#    - rc3.1
#    - morphemic-rc1.5
#  image: $DOCKER_DIND_IMAGE
#  services:
#    - $DOCKER_DIND_SERVICE
#  script:
#    - $DOCKER_CLI $FUNCTIONIZER_TESTING_TOOL_CLI -Ddocker.imagePrefix=melodic/ clean install
#    - echo "$K8S_SECRET_DOCKER_PASSWORD" | docker login $CI_REGISTRY -u $K8S_SECRET_DOCKER_USER --password-stdin
#    - docker tag $LOCAL_REPO/melodic/functionizer-testing-tool:unknown $CI_REGISTRY_IMAGE/functionizer-testing-tool:$CI_COMMIT_BRANCH
#    - docker push $CI_REGISTRY_IMAGE/functionizer-testing-tool:$CI_COMMIT_BRANCH

deploy:cp-parser:
  stage: deploy
  only:
    - morphemic-rc3.0
  image: $DOCKER_DIND_IMAGE
  services:
    - $DOCKER_DIND_SERVICE
  dependencies:
    - build:cp-parser
    - build-required-part3:zpp-solver
    - build-required-part6:cp-solver
  script:
    - $DOCKER_CLI $CP_PARSER_CLI deploy

deploy-solvers-part1:nc-solver:
  stage: deploy-solvers-part1
  only:
    - morphemic-rc3.0
  image: $DOCKER_DIND_IMAGE
  services:
    - $DOCKER_DIND_SERVICE
  dependencies:
    - build-required-part6:cp-solver
    - build:cp-parser
    - build-required-part3:zpp-solver
  script:
    - $DOCKER_CLI $NC_SOLVER_CLI -Ddocker.imagePrefix=melodic/ clean install
    - echo "$K8S_SECRET_DOCKER_PASSWORD" | docker login $CI_REGISTRY -u $K8S_SECRET_DOCKER_USER --password-stdin
    - docker tag $LOCAL_REPO/melodic/ncsolver:unknown $CI_REGISTRY_IMAGE/ncsolver:$CI_COMMIT_BRANCH
    - docker push $CI_REGISTRY_IMAGE/ncsolver:$CI_COMMIT_BRANCH

deploy-solvers-part2:pt-solver:
  stage: deploy-solvers-part2
  only:
    - morphemic-rc3.0
  image: $DOCKER_DIND_IMAGE
  services:
    - $DOCKER_DIND_SERVICE
  dependencies:
    - build-required-part6:cp-solver
    - build:cp-parser
    - build-required-part3:zpp-solver
  script:
    - $DOCKER_CLI $PT_SOLVER_CLI -Ddocker.imagePrefix=melodic/ clean install
    - echo "$K8S_SECRET_DOCKER_PASSWORD" | docker login $CI_REGISTRY -u $K8S_SECRET_DOCKER_USER --password-stdin
    - docker tag $LOCAL_REPO/melodic/ptsolver:unknown $CI_REGISTRY_IMAGE/ptsolver:$CI_COMMIT_BRANCH
    - docker push $CI_REGISTRY_IMAGE/ptsolver:$CI_COMMIT_BRANCH

deploy-solvers-part3:mcts-solver:
  stage: deploy-solvers-part3
  only:
    - morphemic-rc3.0
  image: $DOCKER_DIND_IMAGE
  services:
    - $DOCKER_DIND_SERVICE
  dependencies:
    - build-required-part6:cp-solver
    - build:cp-parser
    - build-required-part3:zpp-solver
  script:
    - $DOCKER_CLI $MCTS_SOLVER_CLI -Ddocker.imagePrefix=melodic/ clean install
    - echo "$K8S_SECRET_DOCKER_PASSWORD" | docker login $CI_REGISTRY -u $K8S_SECRET_DOCKER_USER --password-stdin
    - docker tag $LOCAL_REPO/melodic/mctssolver:unknown $CI_REGISTRY_IMAGE/mctssolver:$CI_COMMIT_BRANCH
    - docker push $CI_REGISTRY_IMAGE/mctssolver:$CI_COMMIT_BRANCH

deploy-solvers-part4:gen-solver:
  stage: deploy-solvers-part4
  only:
    - morphemic-rc3.0
  image: $DOCKER_DIND_IMAGE
  services:
    - $DOCKER_DIND_SERVICE
  dependencies:
    - build-required-part6:cp-solver
    - build:cp-parser
    - build-required-part3:zpp-solver
  script:
    - $DOCKER_CLI $GEN_SOLVER_CLI -Ddocker.imagePrefix=melodic/ clean install
    - echo "$K8S_SECRET_DOCKER_PASSWORD" | docker login $CI_REGISTRY -u $K8S_SECRET_DOCKER_USER --password-stdin
    - docker tag $LOCAL_REPO/melodic/geneticsolver:unknown $CI_REGISTRY_IMAGE/geneticsolver:$CI_COMMIT_BRANCH
    - docker push $CI_REGISTRY_IMAGE/geneticsolver:$CI_COMMIT_BRANCH
