#
# Copyright (C) 2017-2026 Institute of Communication and Computer Systems (imu.iccs.gr)
#
# This Source Code Form is subject to the terms of the Mozilla Public License, v2.0, unless
# Esper library is used, in which case it is subject to the terms of General Public License v2.0.
# If a copy of the MPL was not distributed with this file, you can obtain one at
# https://www.mozilla.org/en-US/MPL/2.0/
#

ARG BUILDER_IMAGE=docker.io/library/maven:3.9.15-eclipse-temurin-21-noble
ARG SERVER_BASE_IMAGE=eclipse-temurin:21.0.10_7-jre-alpine-3.23
ARG CLIENT_BASE_IMAGE=eclipse-temurin:21.0.10_7-jre-alpine-3.23


# ----------------- EMS Builder image -----------------
FROM $BUILDER_IMAGE AS ems-server-builder

ARG BUILD_DIR=/build
ARG SOURCE_DIR=/build/ems-core
ARG TARGET_DIR=/build/dist

ENV BUILD_DIR=${BUILD_DIR} \
    TARGET_DIR=${TARGET_DIR}

WORKDIR ${BUILD_DIR}

COPY ./ems-core ${SOURCE_DIR}

#RUN --mount=type=cache,target=/root/.m2  \
RUN \
    set -eux; \
    mvn -B -ntp -f ${BUILD_DIR}/ems-core/pom.xml -DskipTests clean install -P '!build-docker-image' -P '!build-web-admin'; \
    java -Djarmode=tools -jar ${SOURCE_DIR}/control-service/target/control-service.jar extract --layers --launcher; \
    mv ${BUILD_DIR}/control-service ${TARGET_DIR}; \
    cp ${SOURCE_DIR}/control-service/target/esper*.jar ${TARGET_DIR}/application/BOOT-INF/lib/


# ----------------- EMS-Core Run image (ALPINE) -----------------
FROM $SERVER_BASE_IMAGE AS ems-server

ARG BUILD_DIR=/build
ARG SOURCE_DIR=/build/ems-core
ARG TARGET_DIR=/build/dist

ARG EMS_USER=emsuser
ARG EMS_HOME=/opt/ems-server

# Install required tools (Alpine uses apk)
RUN set -eux; \
    apk add --no-cache wget ca-certificates dumb-init

# Add EMS user (Alpine style)
RUN set -eux; \
    addgroup -S ${EMS_USER}; \
    adduser -S -G ${EMS_USER} -h ${EMS_HOME} -s /bin/false ${EMS_USER}; \
    mkdir -p ${EMS_HOME} ${EMS_HOME}/models; \
    chown -R ${EMS_USER}:${EMS_USER} ${EMS_HOME}

# Setup environment
ENV BASEDIR=${EMS_HOME} \
    EMS_CONFIG_DIR=${EMS_HOME}/config \
    BIN_DIR=${EMS_HOME}/bin \
    CONFIG_DIR=${EMS_HOME}/config \
    LOGS_DIR=${EMS_HOME}/logs \
    MODELS_DIR=${EMS_HOME}/models \
    PUBLIC_DIR=${EMS_HOME}/public_resources

# Copy resource files
COPY --chown=${EMS_USER}:${EMS_USER} --from=ems-server-builder ${SOURCE_DIR}/bin               ${BIN_DIR}
COPY --chown=${EMS_USER}:${EMS_USER} --from=ems-server-builder ${SOURCE_DIR}/config-files      ${CONFIG_DIR}
COPY --chown=${EMS_USER}:${EMS_USER} --from=ems-server-builder ${SOURCE_DIR}/public_resources  ${PUBLIC_DIR}

# Copy app layers
COPY --chown=${EMS_USER}:${EMS_USER} --from=ems-server-builder ${TARGET_DIR}/dependencies          ${BASEDIR}
COPY --chown=${EMS_USER}:${EMS_USER} --from=ems-server-builder ${TARGET_DIR}/spring-boot-loader    ${BASEDIR}
COPY --chown=${EMS_USER}:${EMS_USER} --from=ems-server-builder ${TARGET_DIR}/snapshot-dependencies ${BASEDIR}
COPY --chown=${EMS_USER}:${EMS_USER} --from=ems-server-builder ${TARGET_DIR}/application           ${BASEDIR}

# Final setup
RUN set -eux; \
    mkdir -p ${LOGS_DIR} ${MODELS_DIR}; \
    chmod +x ${BIN_DIR}/*.sh; \
    chown -R ${EMS_USER}:${EMS_USER} ${BASEDIR}

# Set user and work dir.
USER ${EMS_USER}
WORKDIR ${EMS_HOME}

EXPOSE 2222 8111 61610 61616 61617

ENTRYPOINT ["dumb-init", "./bin/run.sh"]


# ----------------- EMS-Client Runtime image (ALPINE) -----------------
FROM $CLIENT_BASE_IMAGE AS ems-client

ARG SOURCE_DIR=/build/ems-core
ARG EMS_USER=emsuser
ARG EMS_HOME=/opt/baguette-client
ARG INSTALLATION_PACKAGE=baguette-client-installation-package.tgz

# Install minimal tools
RUN set -eux; \
    apk add --no-cache tar bash ca-certificates

# Add user (Alpine style)
RUN set -eux; \
    addgroup -S ${EMS_USER}; \
    adduser -S -G ${EMS_USER} -h ${EMS_HOME} -s /bin/false ${EMS_USER}; \
    mkdir -p ${EMS_HOME}; \
    chown -R ${EMS_USER}:${EMS_USER} ${EMS_HOME}

# Setup environment
ENV EMS_CONFIG_DIR=${EMS_HOME}/conf \
    JAVA_HOME=/opt/java/openjdk \
    PATH=$JAVA_HOME/bin:$PATH

# Copy and install EMS client
COPY --chown=${EMS_USER}:${EMS_USER} --from=ems-server-builder \
    ${SOURCE_DIR}/baguette-client/target/${INSTALLATION_PACKAGE} /tmp
COPY --chown=${EMS_USER}:${EMS_USER} --from=ems-server-builder \
    ${SOURCE_DIR}/baguette-client/conf/ ${EMS_HOME}/conf/
RUN set -eux; \
    tar zxvf /tmp/${INSTALLATION_PACKAGE} -C /opt; \
    rm -f /tmp/${INSTALLATION_PACKAGE}; \
    chown -R ${EMS_USER}:${EMS_USER} ${EMS_HOME}

# Set user and work dir.
USER ${EMS_USER}
WORKDIR ${EMS_HOME}

EXPOSE 61610 61616 61617

ENTRYPOINT ["/bin/sh", "-c", "/opt/baguette-client/bin/run.sh  &&  tail -f /opt/baguette-client/logs/output.txt"]