#inputFile=/home/asinha/git/paasadapter/src/test/resources/Scalarm_full.xmi
inputFile=/home/asinha/git/paasadapterOW2/paasadapter/src/test/resources/ScalarmModelInstance.xmi
#CDO.host=localhost
#CDO.port=2036
#CDO.repositoryName=repo1
#CDO.resourceName=NewsssSsssSs1
##ExecutionwareURL=http://localhost:9000
#ExecutionwareURL=http://131.254.13.194:9000
ExecutionwareURL=http://134.60.64.129:9000
ExecutionwareUname=john.doe@example.com
ExecutionwarePwd=admin
ExecutionwareTenant=admin
#####Cloud-Provider-Credentials###
#NOTE for adding new cloud provider:The key should contain the cloud provider name (case insensitive) followed by hyphen and then the kind of information i.e. uname OR pass OR endpoint
#Please modify/delete the existing ones according to your needs
Flexiant-uname=flexiant@flexiant.com/0c187aae-23c8-6855-7f9b-c8779f929b68_To_BE_PROVIDED
Flexiant-pass=flex*p@ss_To_BE_PROVIDED
Flexiant-endpoint=optional_for_flexiant
#
Omistack-uname=omistackUname_To_BE_PROVIDED
Omistack-pass=OmI*p@ss_To_BE_PROVIDED
Omistack-endpoint=optional_for_omistack
#
gwdg-uname=gwdgUname_To_BE_PROVIDED
gwdg-pass=gWDg*p@ss_To_BE_PROVIDED
gwdg-endpoint=https://api.cloud.gwdg.de:5000/v2.0/
#
ec2-uname=ec2Uname_To_BE_PROVIDED
ec2-pass=eC2*p@ss_To_BE_PROVIDED
ec2-endpoint=https://ec2.eu-west-1.amazonaws.com
# ZMQ
#ZMQ.SubS2DPort=5584
#ZMQ.SubS2DTopic=newCamelDeploymentAvailable
#ZMQ.SubTerminationPort=5588
#ZMQ.SubTerminationTopic=terminate
#ZMQ.SubScalingPort=5589