#inputFile=/home/asinha/git/paasadapter/src/test/resources/Scalarm_full.xmi
inputFile=/home/asinha/git/paasadapterOW2/paasadapter/src/test/resources/ScalarmModelInstance.xmi
#CDO.host=localhost
#CDO.port=2036
#CDO.repositoryName=repo1
#CDO.resourceName=NewsssSsssSs1
##ExecutionwareURL=http://localhost:9000
#ExecutionwareURL=http://131.254.13.194:9000
ExecutionwareURL=http://134.60.64.129:9000
ExecutionwareUname=john.doe@example.com
ExecutionwarePwd=admin
ExecutionwareTenant=admin
# ZMQ
#ZMQ.SubS2DPort=5584
#ZMQ.SubS2DTopic=newCamelDeploymentAvailable
#ZMQ.SubTerminationPort=5588
#ZMQ.SubTerminationTopic=terminate
#ZMQ.SubScalingPort=5589