#inputFile=/home/asinha/git/paasadapter/src/test/resources/Scalarm_full.xmi
inputFile=/home/asinha/git/paasadapterOW2/paasadapter/src/test/resources/ScalarmModelInstance.xmi
#CDO.host=localhost
#CDO.port=2036
#CDO.repositoryName=repo1
#CDO.resourceName=NewsssSsssSs1
##ExecutionwareURL=http://localhost:9000
#ExecutionwareURL=http://131.254.13.194:9000
ExecutionwareURL=http://134.60.64.129:9000
ExecutionwareUname=john.doe@example.com
ExecutionwarePwd=admin
ExecutionwareTenant=admin
#####Cloud-Provider-Credentials###
Flexiant-uname=flexiant@flexiant.com/0c187aae-23c8-6855-7f9b-c8779f929b68
Flexiant-pass=flex*p@ss
Flexiant-endpoint=optional
#
Omistack-uname=omistackUname
Omistack-pass=OmI*p@ss
Omistack-endpoint=optional