#
# Copyright (C) 2023 Institute of Communication and Computer Systems (imu.iccs.gr)
#
# This Source Code Form is subject to the terms of the Mozilla Public License, v2.0.
# If a copy of the MPL was not distributed with this file, you can obtain one at
# https://www.mozilla.org/en-US/MPL/2.0/
#

# IMPORTANT:
# Sample metric model for discussion with consortium
# Based on surveillance app demo

apiVersion: nebulous/v1
kind: MetricModel
metadata:
  name: face-detection-deployment
  labels:
    app: surveillance-demo-app

# Not part of metric model... The following is a YAML hack
templates:
  percentage_template: &prct_tpl    # Occurrences of '*prct_tpl' will be replaced with the following keys
    id: 'prct'
    type: double
    range: [0, 100]
    unit: none

spec:
  components:
    - name: face-detection
      requirements:
        - name: cpu_slo
          type: slo
#          constraint: 'cpu_util_prct > 80'
          # ALTERNATIVE REPRESENTATION of constraint
          constraint:
            type: metric
            metric: cpu_util_prct
            operator: '>'
            threshold: 80
        - name: ram_slo
          type: slo
          constraint: 'ram_util_prct > 80'
        - name: bandwidth_slo
          type: slo
          constraint: 'bandwidth > 85'
        - name: latency_slo
          type: slo
          constraint: 'latency > 25'
        - name: fps_slo
          type: slo
#          constraint: 'fps - 30 * vc_instance_number < 0'
          constraint: 'vc_instance_number < 0'

        - name: test_logical_slo
          type: slo
          constraint:                   # i.e.  (bandwidth > 10 and bandwidth < 50) or (bandwidth > 85)
            type: logical
            operator: or
            constraints: [ _c1_slo, _c2_slo ]
        - name: test_conditional_slo
          type: slo
          constraint:
            type: conditional
            if:   _c1a_slo
            then: _c1b_slo
            else: _c2_slo

        - name: _c1_slo
          type: slo
          constraint:
            type: logical
            operator: and
            constraints: [ _c1a_slo, _c1b_slo ]
        - name: _c1a_slo
          type: slo
          constraint: 'bandwidth > 10'
        - name: _c1b_slo
          type: slo
          constraint: 'bandwidth < 50'
        - name: _c2_slo
          type: slo
          constraint: 'bandwidth > 85'

      #--------------------------
      metrics:
        - name: cpu_util_prct
          type: composite                       # Optional. Can be inferred from the existence of 'formula' field
          template: *prct_tpl
          formula: 'mean(cpu_util_instance)'    # Expression follows mathXParser syntax (see https://mathparser.org/)
#          window: 'sliding 5 min'
          # ALTERNATIVE REPRESENTATION of window
          window:
            type: sliding
            size:
              value: 5
              unit: min
#          output: 'all 30 sec'
          # ALTERNATIVE REPRESENTATION of output
          output:
            type: all
            schedule:
              value: 30
              unit: sec
        - name: cpu_util_instance
          type: raw                             # Optional. Can be inferred from the existence of 'sensor' field
          template: *prct_tpl
#          sensor: 'netdata netdata__system__cpu__total'
          # ALTERNATIVE REPRESENTATION of sensor
          sensor:
            type: netdata
            affinity: netdata__system__cpu__total
          output: 'all 30 sec'
        - name: ram_util_prct
          type: composite
          template: *prct_tpl
          formula: 'mean(ram_util_instance)'
          window: 'sliding 5 min'
          output: 'all 30 sec'
        - name: ram_util_instance
          type: raw
          template: *prct_tpl
          sensor: 'netdata netdata__system__cpu__total'
          output: 'all 30 sec'
        - name: bandwidth
          type: composite
          level: per_region
          formula: 'mean(bandwidth_instance) / my_sgn(PROVIDER_BANDWIDTH) * PROVIDER_BANDWIDTH'
          window: 'sliding 5 min'
          output: 'all 30 sec'
        - name: bandwidth_instance
          type: raw
          busy-status: true
          sensor: 'netdata netdata__system__cpu__total'
          output: 'all 30 sec'
        - name: PROVIDER_BANDWIDTH
          type: constant                              # Mandatory, in case of constants.
          default: '1'                                # Used to set initial values to constants provided by solver
          template:
            type: double
            range: [0, 999999999]
            unit: GB
        #---
        - name: latency
#          type: composite
          formula: 'mean(latency_instance)'
          window: 'sliding 5 min'
          output: 'all 30 sec'
        - name: latency_instance
          type: raw
          sensor:
            type: 'my_latency_sensor'                 # Custom / Application sensor  (default is Netdata, used to collect system metrics)
            config: { ping_address: '1.2.3.4', proto: 'icmp', schedule: '1 min' }   # Sensor specific configuration (as key-value pairs)
          output: 'all 30 sec'
        #---
        - name: fps
          type: composite
          formula: 'mean(fps_instance)'
          window: 'sliding 1 min'
          output: 'all 10 sec'
        - name: fps_instance
          type: raw
          sensor:
            type: 'my_fps_sensor'                     # Custom / Application sensor, without configuration
          output: 'all 1 sec'
        - name: vc_instance_number
          ref: '[video-capture].[vc_instance_number]' # Replicates [video-capture].[vc_instance_number] under vc_instance_number name
      #--------------------------
    - name: video-capture
      metrics:
        #---
        - name: vc_instance_number
          formula: 'add(vc_instance_number_raw)'
          window:
            type: sliding
            size: '1 sec'
            processing:
             - type: group                            # A window GROUPING processing
               function: 'unique'                     # applies UNIQUE (EPL) function
               criteria: [ INSTANCE ]                 # using the listed grouping criteria....
               #  I.e., groups windows events per instance (IP address) and applies the UNIQUE function per group
               #  Result: The latest event per group/instance are effectively retained and used in subsequent calculations
          output: 'all 1 sec'
        - name: vc_instance_number_raw
          sensor:
            type: 'my_vc_sensor'
            config: {}
            install:
              script: 'wget http://..... && chmod +x ..... && ./run.sh &'
  #--------------------------
  scopes:
    - name: app-wide-scope
      requirements:
        - name: sample_slo_combining_data_across_components
          type: slo
          constraint: 'sample_metric_combining_data_across_components > 10'
      metrics:
        - name: sample_metric_combining_data_across_components
          formula: 'vc_instance_number * fd_latency'
          grouping: per_zone
          output: 'all 1 min'
        - name: vc_instance_number
          ref: '[video-capture].[vc_instance_number]'
        - name: fd_latency
          ref: '[face-detection].[latency]'
          #---
        - name: VideoCaptureCardinality
          ref: '[video-capture].[vc_instance_number]'

functions:
  - name: my_sgn
    expression: 'abs( n ) / n'
    arguments: [ n ]