amazonEC2:/model/fm/amazonEC2.xmi;/model/mapping/amazonEC2Mapping.xmi
elasticHosts:/model/fm/elastichosts.xmi;/model/mapping/elastichostsMapping.xmi
heroku:/model/fm/heroku.xmi;/model/mapping/herokuMapping.xmi
windowsAzure:/model/fm/windowsAzure.xmi;/model/mapping/windowsAzureMapping.xmi