
# Startup times per VM type
startupTimes.t1.micro=50
startupTimes.t1.small=100
startupTimes.t1.xlarge=120
startupTimes.t1.medium=110
startupTimes.t1.xxlarge=130
startupTimes.m1.tiny=55
startupTimes.m1.small=79
startupTimes.m1.medium=88
startupTimes.m1.large=132
startupTimes.m1.xlarge=140
startupTimes.t1.large=110

# State info for VM characteristics

stateInfo=1,0.6,0.5;1,1.7,160;4,7.5,850;8,15,1690;7,17.1,420;5,2,350;1,0.5,0.5;1,2.048,10;2,4.096,10;4,8.192,20;8,16.384,40

# Memcached info

host=127.0.0.1
port=11211

vmData.t1_micro.startupTime=50
vmData.t1_micro.cores=1
vmData.t1_micro.ram=0.6
vmData.t1_micro.disk=0.5

vmData.t1_small.startupTime=100
vmData.t1_small.cores=1
vmData.t1_small.ram=1.7
vmData.t1_small.disk=160

vmData.t1_xlarge.startupTime=120
vmData.t1_xlarge.cores=4
vmData.t1_xlarge.ram=7.5
vmData.t1_xlarge.disk=850

vmData.t1_medium.startupTime=110
vmData.t1_medium.cores=8
vmData.t1_medium.ram=15
vmData.t1_medium.disk=1690

vmData.t1_xxlarge.startupTime=130
vmData.t1_xxlarge.cores=7
vmData.t1_xxlarge.ram=17.1
vmData.t1_xxlarge.disk=420

vmData.m1_tiny.startupTime=55
vmData.m1_tiny.cores=5
vmData.m1_tiny.ram=2
vmData.m1_tiny.disk=350

vmData.m1_small.startupTime=79
vmData.m1_small.cores=1
vmData.m1_small.ram=0.5
vmData.m1_small.disk=0.5

vmData.m1_medium.startupTime=88
vmData.m1_medium.cores=1
vmData.m1_medium.ram=2.048
vmData.m1_medium.disk=10

vmData.m1_large.startupTime=132
vmData.m1_large.cores=2
vmData.m1_large.ram=4.096
vmData.m1_large.disk=10

vmData.m1_xlarge.startupTime=140
vmData.m1_xlarge.cores=4
vmData.m1_xlarge.ram=8.192
vmData.m1_xlarge.disk=20

vmData.t1_large.startupTime=110
vmData.t1_large.cores=8
vmData.t1_large.ram=16.384
vmData.t1_large.disk=40
