#########################################################
# cdo server connection properties
# This file is used for development.  During production
# run, there should be a similar file located in the 
# $PAASAGE_CONFIG_DIR and which is used by the 
# upperware components.
#########################################################
#
###CDO server endpoint
#stfc development cdo server
#host=kirkhac3.miniserver.com
host=127.0.0.1
#production
#host=toc
###server port
port=2036
###repository name
#stfc development repo
repository=repo1
#production
#repository=repo1
#logging to be set off or on - default is off
logging=off

