#cloudML:eu.paasage.upperware.profiler.cp.generator.model.cloudML.lib.CloudMLXMIProcessorFactory
#saloonOntology:eu.paasage.upperware.profiler.cp.generator.model.saloon.lib.SaloonProcessorFactory
camel:eu.paasage.upperware.profiler.cp.generator.model.camel.lib.CamelProcessorFactory