Flexiant:/model/fm/FlexiantCamelModel.xmi;/model/mapping/FlexiantCamelModelMapping.xmi
GWDG:/model/fm/gwdgCamelModel.xmi;/model/mapping/gwdgCamelModelMapping.xmi
Omistack:/model/fm/Omistack.xmi;/model/mapping/omistackCamelModelMapping.xmi
