#
# Copyright (C) 2017-2022 Institute of Communication and Computer Systems (imu.iccs.gr)
#
# This Source Code Form is subject to the terms of the Mozilla Public License, v2.0.
# If a copy of the MPL was not distributed with this file, You can obtain one at
# https://www.mozilla.org/en-US/MPL/2.0/
#

#### Enable Web security ####
#melodic.security.enabled=false

#### Communication with ESB ####
#esb.enabled=false
esb.url=http://localhost:8088/api/metaSolver/deploymentProcess
#### Mock ESB endpoint in MetaSolver - For testing only
#esb.url=http://localhost:8092/esbTest

#### Communication with EMS ####
ems-url=http://localhost:8111/cpModelJson

#### Communication with EMS ActiveMQ broker ####
ems-broker-username=aaa
ems-broker-password=111
#ems-broker-certificate=
#NOTE: EMS broker truststore is set in run.bat or run.sh

#### REST interface port ####
server.port=8092

#### Pub/Sub configuration for Metric Values and Scale events ####
pubsub.on=true

# #### Startup topic subscriptions
# #pubsub.startupTopics[0].name = MetaSolver_METRIC_topic
# pubsub.startupTopics[0].name = AverageResponseTime
# #pubsub.startupTopics[0].url = DEFAULT_BROKER_URL
# #pubsub.startupTopics[0].url = tcp://172.24.29.139:61616
# pubsub.startupTopics[0].url = tcp://192.168.99.100:61616
# #pubsub.startupTopics[0].url = tcp://34.241.234.14:61616	The hackaton 2nd-level VM broker
# pubsub.startupTopics[0].clientId = Metasolver-Metric-Value-Monitor-Bean-client
# pubsub.startupTopics[0].type = MVV
# 
# pubsub.startupTopics[1].name = AverageResponseTimeHigh1m
# #pubsub.startupTopics[1].url = DEFAULT_BROKER_URL
# pubsub.startupTopics[1].url = tcp://192.168.99.100:61616
# #pubsub.startupTopics[1].clientId = Metasolver-Metric-Value-Monitor-Bean-client
# pubsub.startupTopics[1].type = SCALE

#### Topic subscriptions common in all subscription setups
pubsub.commonTopics[0].name = prediction.slo_severity_value
pubsub.commonTopics[0].url = DEFAULT_BROKER_URL
#pubsub.commonTopics[0].clientId = Metasolver-Metric-Value-Monitor-Bean-client
pubsub.commonTopics[0].type = SCALE

#### Default solver
#### Possible values: CPSOLVER, PTSOLVER, GENETICSOLVER, NCSOLVER, MCTSSOLVER
defaultSolver=CPSOLVER

#### New solutions must have utilities at least 'utility-threshold-factor' times higher
#### than the utility of the deployed solution
utility-threshold-factor=1.1

#### CP Model Update interval (in millis)
#cpModelUpdateEnabled = false
cpModelUpdateInterval = 30000

#### Debug events settings
#debugEvents.enabled=false
#debugEvents.topicName=metasolver_debug
#debugEvents.url=
#debugEvents.username=
#debugEvents.password=
#debugEvents.certificate=
#debugEvents.clientId=

#### Prediction processing settings
predictionMonitoringEnabled = true
#predictionTopicFormatter = prediction.%s
#predictionTopicPattern = ^prediction\.(.+)$
predictionRegistryCleanupRate = 60000
#predictionRegistryCleanupAfterScaleEvent = false

reconfigurationProbabilityThreshold = 0.5
#reconfigurationBlockingPeriod = 600000
#preventConcurrentReconfigurations = false
#preventConcurrentReconfigurationsTimeout = -1L

### logback configuration ###
logging.config=file:${MELODIC_CONFIG_DIR}/logback-conf/logback-spring.xml