#
# Copyright (C) 2017 Institute of Communication and Computer Systems (imu.iccs.com)
#
# This Source Code Form is subject to the terms of the
# Mozilla Public License, v. 2.0. If a copy of the MPL
# was not distributed with this file, You can obtain one at
# http://mozilla.org/MPL/2.0/.
#

#### Enable Web security ####
#melodic.security.enabled=false

#### Communication with ESB ####
esb.url=http://localhost:8088/api/metaSolver/deploymentProcess
#### Mock ESB endpoint in MetaSolver - For testing only
#esb.url=http://localhost:8092/esbTest

#### Communication with EMS ####
ems-url=http://localhost:8111/cpModelJson

#### REST interface port ####
server.port=8092

#### Pub/Sub configuration for Metrice Values and Scale events ####
pubsub.on=true

# #### Settings for 'localhost'
# #pubsub.topics[0].name = MetaSolver_METRIC_topic
# pubsub.topics[0].name = AverageResponseTime
# #pubsub.topics[0].url = DEFAULT_BROKER_URL
# #pubsub.topics[0].url = tcp://172.24.29.139:61616
# pubsub.topics[0].url = tcp://192.168.99.100:61616
# #pubsub.topics[0].url = tcp://34.241.234.14:61616	The hackaton 2nd-level VM broker
# pubsub.topics[0].clientId = Metasolver-Metric-Value-Monitor-Bean-client
# pubsub.topics[0].type = MVV
# 
# pubsub.topics[1].name = AverageResponseTimeHigh1m
# #pubsub.topics[1].url = DEFAULT_BROKER_URL
# pubsub.topics[1].url = tcp://192.168.99.100:61616
# #pubsub.topics[1].clientId = Metasolver-Metric-Value-Monitor-Bean-client
# pubsub.topics[1].type = SCALE

#### New solutions must have utilities at least '1.1' times higher than the utility of the deployed solution
utility-threshold-factor=1.1
### logback configuration ###
logging.config=file:${MELODIC_CONFIG_DIR}/logback-conf/logback-spring.xml