# MELODIC Authorization Service - Client/PEP configuration

### Authorization client configuration
pdp.disabled = false
pdp.access-key = 7235687126587231675321756752657236156321765723
pdp.endpoints = https://localhost:7071/checkJsonAccessRequest
pdp.load-balance-method = RANDOM
pdp.retry-count = 3

pdp.http-client.keystore-file = ${MELODIC_CONFIG_DIR}/truststore-client.p12
pdp.http-client.keystore-file-type = PKCS12
pdp.http-client.keystore-password = melodic


### Data aquisition & extraction configuration
#data.extractors = eu.melodic.upperware.adapter.extractor.CoreExtractor, eu.melodic.upperware.adapter.extractor.RamExtractor, eu.melodic.upperware.adapter.extractor.StorageExtractor
data.extractors = \
  eu.melodic.upperware.adapter.extractor.CoreExtractor,\
  eu.melodic.upperware.adapter.extractor.RamExtractor,\
  eu.melodic.upperware.adapter.extractor.StorageExtractor,\
  eu.melodic.upperware.adapter.extractor.CountryExtractor,\
  eu.melodic.upperware.adapter.extractor.PerVmCoreExtractor,\
  eu.melodic.upperware.adapter.extractor.PerVmRamExtractor,\
  eu.melodic.upperware.adapter.extractor.PerVmStorageExtractor,\
  eu.melodic.upperware.adapter.extractor.PerVmCountryExtractor
