## NOTE: this property files is the one used by Tomcat

# rabbitmq queue name for getting the result from the CP generator
PROFILER_QUEUE_NAME=wp3_profiler
PROFILER_HOST_NAME=localhost
PROFILER_PORT_NUM=-1

# queue name for sending the result to the Metasolver
OUTGOING_QUEUE_NAME=profiler_to_metasolver
METASOLVER_HOST_NAME=localhost
METASOLVER_PORT_NUM=-1

# properties for CDO server
CDO_HOST=localhost
CDO_PORT=2036
CDO_REPO=repo1

# a temp directory to unzip the cp model files
RP_TEMP_DIR=/tmp/rule_processor/

PAASAGE_CONFIG_DIR=/etc/paasage/

##################################################
# NOTE: The log4j properties for setting up the log file

#From http://logging.apache.org/log4j/1.2/apidocs/org/apache/log4j/Level.html
#Defines the minimum set of levels recognized by the system, that is 
# 1. OFF (highest rank - turn off logging) 
# 2. FATAL 
# 3. ERROR # 4. WARN # 5. INFO 
# 6. DEBUG
# 7. ALL (lowest rank - turn all logging).
# Root logger option
log4j.rootLogger=info, stdout
#log4j.logger.paasage-profiler-log=info, stdout

# Direct log messages to stdout
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.Target=System.out
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d{ABSOLUTE} %5p %c{1}:%L - %m%n

