Availability:eu.paasage.upperware.profiler.cp.generator.model.derivator.lib.AvailabilityFunctionCreator
ResponseTime:eu.paasage.upperware.profiler.cp.generator.model.derivator.lib.ResponseTimeFunctionCreator
Cost:eu.paasage.upperware.profiler.cp.generator.model.derivator.lib.CostFunctionCreator
Attribute:eu.paasage.upperware.profiler.cp.generator.model.derivator.lib.AttributeFunctionCreator