Flexiant:/model/fm/FlexiantCamelModel.xmi;/model/mapping/FlexiantCamelModelMapping.xmi
GWDG:/model/fm/gwdgCamelModel.xmi;/model/mapping/gwdgCamelModelMapping.xmi
Omistack:/model/fm/Omistack.xmi;/model/mapping/omistackCamelModelMapping.xmi
AmazonEC2:/model/fm/amazonCamelModel.xmi;/model/mapping/amazonEC2CamelModelMapping.xmi
TryStack:/model/fm/trystackCamelModel.xmi;/model/mapping/trystackCamelModelMapping.xmi
Ucystack:/model/fm/Ucystack.xmi;/model/mapping/ucystackCamelModelMapping.xmi