metric.servlet=http://localhost:30000/metrics/json
# ESPER SINK IS 147.102.17.105:8083
sink.esper = https://4e64e8be-b6d4-4efc-b456-942200ba4af7.mock.pstmn.io/test 
#server.port = 8083
#Metrics can be mentioned here

#Alluxio: Master GET
#http://128.39.37.159:19999/metrics/json

#Worker in the same machine
#http://128.39.37.159:30000/metrics/json

#worker in another machne:
#http://128.39.37.156:30000/metrics/json

##Testing with the db
spring.jpa.hibernate.ddl-auto=create
spring.datasource.url=jdbc:mysql://localhost:3306/db_schema
spring.datasource.username=user
spring.datasource.password=test