#
# Copyright (C) 2017 Institute of Communication and Computer Systems (imu.iccs.com)
#
# This Source Code Form is subject to the terms of the
# Mozilla Public License, v. 2.0. If a copy of the MPL
# was not distributed with this file, You can obtain one at
# http://mozilla.org/MPL/2.0/.
#

control.password-encoder = eu.passage.upperware.commons.passwords.IdentityPasswordEncoder

# Broker ports and protocol
brokercep.broker-name = broker
brokercep.broker-port = 61616
#brokercep.connector-port = 1088
brokercep.broker-protocol = tcp
# Don't use in Upperware
#brokercep.bypass-local-broker = true

# Common Broker settings
#brokercep.ssl.enable = false
brokercep.broker-url = ${brokercep.broker-protocol}://0.0.0.0:${brokercep.broker-port}
brokercep.broker-url-properties = transport.daemon=true&transport.trace=false&transport.useKeepAlive=true&transport.useInactivityMonitor=false&transport.needClientAuth=${brokercep.ssl.client-auth.required}&verifyHostName=true
brokercep.ssl.client-auth.required = false
brokercep.broker-url-for-consumer = ${brokercep.broker-protocol}://localhost:${brokercep.broker-port}
brokercep.broker-url-for-clients = ${brokercep.broker-protocol}://%{PUBLIC_IP}%:${brokercep.broker-port}
#brokercep.broker-url-for-clients = ${brokercep.broker-protocol}://%{DEFAULT_IP}%:${brokercep.broker-port}
# Must be a public IP address

# Key store
brokercep.ssl.truststore.file = ${MELODIC_CONFIG_DIR}/broker-truststore.p12
brokercep.ssl.truststore.type = PKCS12
brokercep.ssl.truststore.password = melodic
# Trust store
brokercep.ssl.keystore.file = ${MELODIC_CONFIG_DIR}/broker-keystore.p12
brokercep.ssl.keystore.type = PKCS12
brokercep.ssl.keystore.password = melodic
# Certificate
brokercep.ssl.certificate.file = ${MELODIC_CONFIG_DIR}/broker.crt
# Key-and-Cert data
brokercep.ssl.entry.generate = IF-IP-CHANGED
brokercep.ssl.entry.name = %{PUBLIC_IP}%
brokercep.ssl.entry.dname = CN=%{PUBLIC_IP}%,OU=Information Management Unit (IMU),O=Institute of Communication and Computer Systems (ICCS),L=Athens,ST=Attika,C=GR
brokercep.ssl.entry.ext-san = dns:localhost,ip:127.0.0.1,ip:%{DEFAULT_IP}%

# Authentication and Authorization settings
brokercep.authentication-enabled = false
brokercep.additional-broker-credentials = aaa/111, bbb/222
brokercep.authorization-enabled = false

# Broker instance settings
brokercep.broker-persistence-enabled = false
brokercep.broker-using-jmx = true
brokercep.broker-advisory-support-enabled = true
brokercep.broker-using-shutdown-hook = false

# Memory usage limit
brokercep.usage.memory.jvm-heap-percentage = 20
#brokercep.usage.memory.size = 134217728
