#
# Copyright (C) 2017 Institute of Communication and Computer Systems (imu.iccs.com)
#
# This Source Code Form is subject to the terms of the
# Mozilla Public License, v. 2.0. If a copy of the MPL
# was not distributed with this file, You can obtain one at
# http://mozilla.org/MPL/2.0/.
#

#### Communication with ESB ####
#esb.url=http://localhost:8088/api/constraintProblemSolution

#### REST interface port ####
server.port = 8092

#### Logging ####
logging.level.root=WARN
logging.level.org.springframework.web=ERROR
logging.level.org.hibernate=ERROR
logging.level.eu.melodic.upperware.metasolver=INFO
#logging.level.eu.melodic.upperware.metasolver.MetaSolverController=INFO
logging.level.eu.melodic.upperware.metasolver.Coordinator=INFO
logging.level.eu.melodic.upperware.metasolver.metricvalue=INFO
logging.level.eu.melodic.upperware.metasolver.util.CpModelHelper=INFO

# Logging pattern for the console
#logging.pattern.console= %d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.console= %-5level - %msg%n
#logging.pattern.console= %d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Logging pattern for file
logging.pattern.file= %d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.file=metaSolver.log

#### Spring framework debug/trace ####
#debug=true
#trace=true
#spring.output.ansi.enabled=DETECT
