#
# Copyright (C) 2017 Institute of Communication and Computer Systems (imu.iccs.com)
#
# This Source Code Form is subject to the terms of the
# Mozilla Public License, v. 2.0. If a copy of the MPL
# was not distributed with this file, You can obtain one at
# http://mozilla.org/MPL/2.0/.
#

#### Communication with ESB ####
esb.url=http://localhost:8088/api/metaSolver/deploymentProcess

#### REST interface port ####
server.port = 8092

#### Pub/Sub configuration for Metrice Values and Scale events ####
pubsub.on = true

#pubsub.topics[0].name = Feb2018_MVV_tests_17_107
#pubsub.topics[0].url = tcp://147.102.17.107:61616
#pubsub.topics[0].clientId = client_107
#pubsub.topics[0].type = MVV

pubsub.topics[0].name = Feb2018_MVV_tests
pubsub.topics[0].url = DEFAULT_BROKER_URL
pubsub.topics[0].clientId = Metasolver-Metric-Value-Monitor-Bean-client
pubsub.topics[0].type = MVV

#pubsub.topics[1].name = Feb2018_SCALE_tests
#pubsub.topics[1].url = DEFAULT_BROKER_URL
##pubsub.topics[1].clientId = Metasolver-Metric-Value-Monitor-Bean-client
#pubsub.topics[1].type = SCALE

#### CDO configuration ####
cdo.host = localhost
cdo.port = 2036
cdo.repositoryName = repo1
#cdo.secure = false

#### New solutions must have utilities at least '1.1' times higher than the utility of the deployed solution
utility-threshold-factor = 1.1