FROM java:8
VOLUME /tmp
ADD metrics-collector.jar metrics-collector.jar
RUN bash -c 'apt-get update'
RUN bash -c 'apt-get install -y netcat'
ENTRYPOINT ["/config/wait-for-cdo.sh", "java", "-Duser.timezone=Europe/Warsaw", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/metrics-collector.jar"]

