amazonEC2:/model/fm/amazonEC2PM.xmi;/model/mapping/amazonEC2MappingCamel.xmi
nova:/model/fm/novaFakePM.xmi;/model/mapping/novaFakeMappingCamel.xmi
flexiant:/model/fm/flexiantFakePM.xmi;/model/mapping/flexiantFakeMappingCamel.xmi
Amazon:/model/fm/amazonEC2PM.xmi;/model/mapping/amazonEC2MappingCamel.xmi
Sintef-Nova:/model/fm/novaFakePM.xmi;/model/mapping/novaFakeMappingCamel.xmi
Flexiant:/model/fm/flexiantFakePM.xmi;/model/mapping/flexiantFakeMappingCamel.xmi
amazon-eu:/model/fm/amazonEC2PM.xmi;/model/mapping/amazonEC2MappingCamel.xmi
oslo-nova:/model/fm/novaFakePM.xmi;/model/mapping/novaFakeMappingCamel.xmi