#spring datasource
#needs to be changed
spring.datasource.url=jdbc:mysql://localhost:3306/Latency?useSSL=false
spring.datasource.username=root
spring.datasource.password=root
server.port=8094

## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5InnoDBDialect

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = update


# This algorithm assigns equal weight to all the historical records
dlms.algorithms[0].name=algo1
dlms.algorithms[0].className=eu.melodic.dlms.algorithmRunners.Algo_AverageWeightRunner
dlms.algorithms[0].interval=600 
dlms.algorithms[0].arguments=80000
dlms.algorithms[0].weight=0.1
dlms.algorithms[0].camelId=algo1_CAMEL_ID

# This algorithm assigns higher weight to the latest records
#dlms.algorithms[1].name=algo2
#dlms.algorithms[1].className=eu.melodic.dlms.algorithmRunners.Algo_LatestHigherWeightRunner
#dlms.algorithms[1].interval=600
#dlms.algorithms[1].arguments=80000
#dlms.algorithms[1].weight=0.1
#dlms.algorithms[1].camelId=algo2_CAMEL_ID


#dlms.algorithms[1].name=algo2
#dlms.algorithms[1].className=eu.melodic.dlms.algorithmRunners.Algo2Runner
#dlms.algorithms[1].interval=2000
#dlms.algorithms[1].arguments=1,lala
#dlms.algorithms[1].weight=0.5
#dlms.algorithms[1].camelId=algo2_CAMEL_ID
