dlms.algorithms[0].name=algo1
dlms.algorithms[0].className=eu.melodic.dlms.algorithmRunners.Algo1Runner
dlms.algorithms[0].interval=10
dlms.algorithms[0].arguments=
dlms.algorithms[0].weight=0.1
dlms.algorithms[0].camelId=algo1_CAMEL_ID

dlms.algorithms[1].name=algo2
dlms.algorithms[1].className=eu.melodic.dlms.algorithmRunners.Algo2Runner
dlms.algorithms[1].interval=20
dlms.algorithms[1].arguments=1,lala
dlms.algorithms[1].weight=0.5
dlms.algorithms[1].camelId=algo2_CAMEL_ID

dlms.algorithms[2].name=algo3
dlms.algorithms[2].className=eu.melodic.dlms.algorithmRunners.Algo2Runner
dlms.algorithms[2].interval=30
dlms.algorithms[2].arguments=2,lalala
dlms.algorithms[2].weight=0.75
dlms.algorithms[2].camelId=algo3_CAMEL_ID
