#
# Copyright (C) 2017 Institute of Communication and Computer Systems (imu.iccs.com)
#
# This Source Code Form is subject to the terms of the
# Mozilla Public License, v. 2.0. If a copy of the MPL
# was not distributed with this file, You can obtain one at
# http://mozilla.org/MPL/2.0/.
#

#### Communication with ESB ####
esb.url=http://localhost:8088/api/metaSolver/deploymentProcess


#### REST interface port ####
server.port = 8092
pubsub.on = true

# 
 pubsub.topics[0].name = dataCenterConnection
 pubsub.topics[0].url = tcp://158.39.75.236:61616
 pubsub.topics[0].type = LATENCY_BANDWIDTH

 pubsub.topics[1].name = dataRead
 pubsub.topics[1].url = tcp://158.39.75.236:61616
 pubsub.topics[1].type = BYTES_READ

 pubsub.topics[2].name = dataWrite
 pubsub.topics[2].url = tcp://158.39.75.236:61616
 pubsub.topics[2].type = BYTES_WRITTEN