#spring datasource
#needs to be changed
#spring.datasource.url=jdbc:mysql://localhost:3306/dlms?useSSL=false
# below line to prevent Time Zone Issue in mysql
spring.datasource.url=jdbc:mysql://localhost:3306/dlms?useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC

spring.datasource.username=root
spring.datasource.password=root
server.port=8094

## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5InnoDBDialect

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = update


# Randomly generates the metrics between two datacenters at random locations
dlms.algorithms[0].name=algo0
dlms.algorithms[0].className=eu.melodic.dlms.algorithm_runners.Algo_DlmsMetricSender_DataCenterRunner
dlms.algorithms[0].interval=10
#argument order is: 
#jms server address, jms server port, best latency, worst latency, best bandwidth, worst bandwidth
dlms.algorithms[0].arguments=tcp://158.39.75.236,61616,5,2000,1024,1
dlms.algorithms[0].weight=0.1
dlms.algorithms[0].camelId=algo0_CAMEL_ID

# Calculate latency and bandwidth between two datacenters for the records based on different weight assignment strategy
dlms.algorithms[1].name=algo1
dlms.algorithms[1].className=eu.melodic.dlms.algorithm_runners.Algo_DataCenterAwarenessRunner
dlms.algorithms[1].interval=10
#argument order is: update all before the specified time interval (integer), update number of records (integer), update based on time or records (string) => "time" or "numRecords", weight of data calculated based on (string) => "averageWeight" or "latestHigher"
#e.g., 600, 1000, numRecords, latestHigher => implies update all the records 600 seconds from the current time, 1000 records, and the update is done based on the number of records in this instance and latest data are given higher weights
dlms.algorithms[1].arguments=800000,100,numRecords,averageWeight
dlms.algorithms[1].weight=0.1
dlms.algorithms[1].camelId=algo1_CAMEL_ID

#Cluster data centers to different zones, which will be used for computing graph similarity
dlms.algorithms[2].name=algo2
dlms.algorithms[2].className=eu.melodic.dlms.algorithm_runners.Algo_ClusterDataCentersRunner
dlms.algorithms[2].interval=10
# in the form of clustering_method (AffinityPropagation/PAMClustering), # cluster. # cluster is used by PAMClustering
dlms.algorithms[2].arguments=AffinityPropagation,4
dlms.algorithms[2].weight=0.1
dlms.algorithms[2].camelId=algo2_CAMEL_ID

# Randomly generates the metrics data read between two random application component and data source
dlms.algorithms[3].name=algo3
dlms.algorithms[3].className=eu.melodic.dlms.algorithm_runners.Algo_DlmsMetricSender_AcDsDataReadRunner
dlms.algorithms[3].interval=10
#argument order is: 
#jms server address, jms server port, #ac, #ds, best amountRead, worst amountRead
dlms.algorithms[3].arguments=tcp://158.39.75.236,61616,3,3,60129542144,0
dlms.algorithms[3].weight=0.1
dlms.algorithms[3].camelId=algo3_CAMEL_ID

# Randomly generates the metrics data write between two random application component and data source
dlms.algorithms[4].name=algo4
dlms.algorithms[4].className=eu.melodic.dlms.algorithm_runners.Algo_DlmsMetricSender_AcDsDataWriteRunner
dlms.algorithms[4].interval=14
#argument order is: 
#jms server address, jms server port, #ac, #ds, best amountWrite, worst amountWrite
dlms.algorithms[4].arguments=tcp://158.39.75.236,61616,3,3,21474836480,0
dlms.algorithms[4].weight=0.1
dlms.algorithms[4].camelId=algo4_CAMEL_ID

# Calculate affinity between application component and data sources
dlms.algorithms[5].name=algo5
dlms.algorithms[5].className=eu.melodic.dlms.algorithm_runners.Algo_AffinityAwarenessRunner
dlms.algorithms[5].interval=14
#argument order is: 
# numRecords,functionName (average/latestHigher/realTimePrediction)
dlms.algorithms[5].arguments=100,average
dlms.algorithms[5].weight=0.1
dlms.algorithms[5].camelId=algo5_CAMEL_ID

# Calculate the total cost of solutions
dlms.algorithms[6].name=algo6
dlms.algorithms[6].className=eu.melodic.dlms.algorithm_runners.Algo_DlmsTotalCostsRunner
dlms.algorithms[6].interval=10
dlms.algorithms[6].arguments=
dlms.algorithms[6].weight=0.1
dlms.algorithms[6].camelId=algo6_CAMEL_ID

# Calculate the total utility
dlms.algorithms[7].name=algo7
dlms.algorithms[7].className=eu.melodic.dlms.algorithm_runners.Algo_DlmsTotalUtilityRunner
dlms.algorithms[7].interval=10
dlms.algorithms[7].arguments=
dlms.algorithms[7].weight=0.1
dlms.algorithms[7].camelId=algo7_CAMEL_ID

# Calculate the source awareness
dlms.algorithms[8].name=algo8
dlms.algorithms[8].className=eu.melodic.dlms.algorithm_runners.Algo_SourceAwarenessRunner
dlms.algorithms[8].interval=10
dlms.algorithms[8].arguments=
dlms.algorithms[8].weight=0.1
dlms.algorithms[8].camelId=algo8_CAMEL_ID

# For dlms web service
# communication with esb
esb.url=http://127.0.0.1:14000/
