package eu.melodic.upperware.guibackend.service.user;

import eu.melodic.upperware.guibackend.controller.user.request.NewUserAutogeneratedPasswordRequest;
import eu.melodic.upperware.guibackend.controller.user.request.NewUserRequest;
import lombok.AllArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Slf4j
@Service
@AllArgsConstructor(onConstructor = @__(@Autowired))
public class UserService {

    private StrongPasswordGenerator strongPasswordGenerator;

    public NewUserRequest createCompletedUserRequest(NewUserAutogeneratedPasswordRequest newUserAutogeneratedPasswordRequest) {
        String password = strongPasswordGenerator.generatePassword();
        return NewUserRequest.builder()
                .username(newUserAutogeneratedPasswordRequest.getUsername())
                .userRole(newUserAutogeneratedPasswordRequest.getUserRole())
                .password(password)
                .passwordConfirmation(password)
                .build();
    }
}
