package eu.melodic.upperware.guibackend.service.user;

import eu.melodic.upperware.guibackend.controller.user.request.NewUserAutogeneratedPasswordRequest;
import eu.melodic.upperware.guibackend.controller.user.request.NewUserRequest;
import lombok.AllArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.passay.CharacterData;
import org.passay.CharacterRule;
import org.passay.EnglishCharacterData;
import org.passay.PasswordGenerator;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.Random;

@Slf4j
@Service
@AllArgsConstructor(onConstructor = @__(@Autowired))
public class UserService {

    public NewUserRequest createCompletedUserRequest(NewUserAutogeneratedPasswordRequest newUserAutogeneratedPasswordRequest) {
        String password = generatePassword();
        return NewUserRequest.builder()
                .username(newUserAutogeneratedPasswordRequest.getUsername())
                .userRole(newUserAutogeneratedPasswordRequest.getUserRole())
                .password(password)
                .passwordConfirmation(password)
                .build();
    }

    private String generatePassword() {
        PasswordGenerator generator = new PasswordGenerator();

        CharacterData lowerCaseChars = EnglishCharacterData.LowerCase;
        CharacterRule lowerCaseRule = new CharacterRule(lowerCaseChars);
        lowerCaseRule.setNumberOfCharacters(2);

        CharacterData upperCaseChars = EnglishCharacterData.UpperCase;
        CharacterRule upperCaseRule = new CharacterRule(upperCaseChars);
        upperCaseRule.setNumberOfCharacters(2);

        CharacterData digitChars = EnglishCharacterData.Digit;
        CharacterRule digitRule = new CharacterRule(digitChars);
        digitRule.setNumberOfCharacters(2);

        Random random = new Random();
        int passwordLength = random.nextInt(8) + 8; //rand.nextInt((max - min) + 1) + min; max=15, min=8

        return generator.generatePassword(passwordLength, lowerCaseRule,
                upperCaseRule, digitRule);
    }
}
