# Cloudiator/Colosseum client configuration 

colosseum.endpoint			http://192.168.98.135:9000/api
colosseum.auth.email		john.doe@example.com
colosseum.auth.tenant		admin
colosseum.auth.password		admin
