# VMS Discovery Server configuration

server.port = 22
server.key.file = hostkey.ser
heartbeat = off
heartbeat.period = 60000

num-of-vms = 1
registration-window = 30000

broker.address = 192.168.2.2
broker.port = 61616
broker.config.template = /opt/vms-discovery-client/bin/client1.sh.tpl
broker.config.file = /opt/vms-discovery-client/bin/client1.sh


VMS_CLIENT_DOWNLOAD_URL = https://bitbucket.7bulls.eu/projects/TST/repos/melodic/raw/esper-demo/vms-discovery-client.zip?at=refs%2Fheads%2Fesper-demo

VMS_SERVER_HOST = 192.168.2.2
VMS_SERVER_PORT = 22
VMS_SERVER_PUBKEY = AAAAB3NzaC1yc2EAAAADAQABAAABAQDKAyYAkXcrRat3qKawSipfZJPsmoGTggin+GIoA/0DJ8xc+3vGYAV0J6EAtDZyFKFYWzWamfpsb08wRGkFTLzXcfW+MRvRYauoAzSFBozKNKq8ycn3x0PIySnZOI3B1SIR9sgJMTyT32QPI8IhxNE78ZPf+rhEaAIjG/T7hnnhkAJ+OvAmhYb3T2x0W2mlmj0JPihUynsoCdQFSt7UARvzG/UIRBmdZ//DRqUn919gf9mLOfQ9zVhrpSq75/cqGwXM1c+UYBYWtnJS2UyWKlMwFe3y6mTtlyWfD3Jn03ZFNCX5q3UDQhcdKj4kMI6xdRn6AnfpfXWPbiK2cMvH9ZXJ
VMS_SERVER_FINGERPRINT = SHA256:9iANcu6iK6UePw0n1DwKwUTeS8MF2W/ih+lUewXgL0A

VMS_SERVER_USERNAME = bb
VMS_SERVER_PASSWORD = yy

VMS_SERVER_CREDENTIALS_FILE = ~/melodic/vms-server.credentials
