# Event Management Server configuration

server.port = 22
server.home.dir = C:\\Users\\user\\Desktop\\sshd
server.key.file = hostkey.ser
heartbeat = off
heartbeat.period = 60000

num-of-vms = 1
registration-window = 30000

broker.address = 192.168.2.2
broker.port = 61616
