#### Communication with ESB ####
esb.url=http://94.177.187.234:8088

memcache.host=paasage04
memcache.port=11211
memcache.ttl=86400

cloudiatorV2.url=http://test:9999
### logback configuration ###
logging.config=file:${MELODIC_CONFIG_DIR}/logback-conf/logback-spring.xml

# ProActive config
pa-rest.url=http://trydev.activeeon.com:8080/rest
pa-rest.login=9MsPgBv+3kZoeE6qsJjhJw==
pa-rest.password=y3VeZGcHmaL0AJAUqv7JHStmZubtOKWE
