#### Communication with ESB ####
esb.url=https://mule:8088

### logback configuration ###
logging.config=file:${MELODIC_CONFIG_DIR}/logback-conf/logback-spring.xml

# ProActive config
pa-config.rest-url=http://${PROACTIVE_IP}:8880
pa-config.login=i4EYCtBsuRpxnU7gomxbvQ==
pa-config.password=i4EYCtBsuRpxnU7gomxbvQ==
pa-config.encryptor-pw=${PROACTIVE_ENCRYPTOR_PW}
