#### Communication with ESB ####
esb.url=http://94.177.187.234:8088

memcache.host=paasage04
memcache.port=11211
memcache.ttl=86400

cloudiatorV2.url=http://test:9999
### logback configuration ###
logging.config=file:${MELODIC_CONFIG_DIR}/logback-conf/logback-spring.xml

# ProActive config
pa-config.rest-url=http://${PROACTIVE_IP}:8880
pa-config.login=i4EYCtBsuRpxnU7gomxbvQ==
pa-config.password=i4EYCtBsuRpxnU7gomxbvQ==
pa-config.encryptor-pw=${PROACTIVE_ENCRYPTOR_PW}
