mule.host=158.39.75.33
mule.port=8088
cloudiator.url=http://158.39.75.115:8089/api/adapter/cloudiatorProxy/api/v2
cloudiator.apiKey=secure
#AWS settings
aws.endpoint=
aws.user=awsUser
aws.secret=awsSecret
aws.nodeGroup=awsNodeGroup
#OpenStack settings
openStack.endpoint=https://omistack.e-technik.uni-ulm.de:5000/v3/
openStack.user=openStackUser
openStack.secret=openStackSecret
openStack.nodeGroup=openStackNodeGroup
#### Logback-config
logging.config=file:${MELODIC_CONFIG_DIR}/logback-conf/logback-spring.xml
