#### Communication with ESB ####
esb.url=https://mule:8088
esb.sslVerificationEnabled=true
#### Communication with Camunda
camunda.url=http://camunda:8095
#### CDO uploader settings
cdoUploader.validationEnabled=true
#### JWT-server settings
jwtServer.url=http://jwtserver:8080
#### Adapter settings
adapter.url=http://adapter:8080
#### MetaSolver settings
metaSolver.url=http://metasolver:8092
#### FunctionizerTestingTool settings
functionizerTestingTool.url=http://functionizer-testing-tool:8080
### HTTPS configuration
server.ssl.key-store=/certs/keystore.p12
server.ssl.key-store-password=melodic
server.ssl.trust-store=/config/common/melodic-truststore.p12
server.ssl.trust-store-password=melodic

#### Logback-config
logging.config=file:${MELODIC_CONFIG_DIR}/logback-conf/logback-spring.xml
# Secure store config
secure-store.pw=${SECURE_STORE_PW}
secure-store.db-url=${SECURE_STORE_DB_URL}
secure-store.db-username=${SECURE_STORE_DB_USER}
secure-store.db-password=${SECURE_STORE_DB_PASSWORD}
# ProActive config
pa-config.rest-url=http://${PROACTIVE_IP}:8880
pa-config.login=i4EYCtBsuRpxnU7gomxbvQ==
pa-config.password=i4EYCtBsuRpxnU7gomxbvQ==
pa-config.encryptor-pw=${PROACTIVE_ENCRYPTOR_PW}
