#
# Copyright (C) 2017 Institute of Communication and Computer Systems (imu.iccs.com)
#
# This Source Code Form is subject to the terms of the
# Mozilla Public License, v. 2.0. If a copy of the MPL
# was not distributed with this file, You can obtain one at
# http://mozilla.org/MPL/2.0/.
#

#### Enable Web security ####
#melodic.security.enabled=false

#### Communication with ESB ####
esb.url=https://mule:8088/api/simulationHandler/deploymentProcess
#### Mock ESB endpoint in MetaSolver - For testing only
#esb.url=http://localhost:8092/esbTest

ems-broker-username=aaa
ems-broker-password=111

#### Communication with EMS ####
ems-url=https://ems:8111/cpModelJson

### Communication with MetaSolver
met

#### REST interface port ####
server.port = 8094

#### Pub/Sub configuration for Metrice Values and Scale events ####
pubsub.on = true

#### CDO configuration ####
cdo.host = cdoserver
cdo.port = 2036
cdo.repositoryName = repo1
#cdo.secure = false

#### New solutions must have utilities at least '1.1' times higher than the utility of the deployed solution
utility-threshold-factor = 0

### logback configuration ###
logging.config=file:${MELODIC_CONFIG_DIR}/logback-conf/logback-spring.xml

history.enabled = false
