// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: facade.proto

package eu.morphemic.facade.proto.test;

/**
 * Protobuf type {@code eu.melodic.upperware.utilitygenerator.facade.test.CallPmPredictionResponse}
 */
public final class CallPmPredictionResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:eu.melodic.upperware.utilitygenerator.facade.test.CallPmPredictionResponse)
    CallPmPredictionResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CallPmPredictionResponse.newBuilder() to construct.
  private CallPmPredictionResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CallPmPredictionResponse() {
    senderID_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new CallPmPredictionResponse();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CallPmPredictionResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 9: {

            utilityValue_ = input.readDouble();
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            senderID_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Facade.internal_static_eu_melodic_upperware_utilitygenerator_facade_test_CallPmPredictionResponse_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Facade.internal_static_eu_melodic_upperware_utilitygenerator_facade_test_CallPmPredictionResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            CallPmPredictionResponse.class, Builder.class);
  }

  public static final int UTILITYVALUE_FIELD_NUMBER = 1;
  private double utilityValue_;
  /**
   * <code>double utilityValue = 1;</code>
   * @return The utilityValue.
   */
  @Override
  public double getUtilityValue() {
    return utilityValue_;
  }

  public static final int SENDERID_FIELD_NUMBER = 2;
  private volatile Object senderID_;
  /**
   * <pre>
   *  int32 utilityValue = 1;
   * </pre>
   *
   * <code>string senderID = 2;</code>
   * @return The senderID.
   */
  @Override
  public String getSenderID() {
    Object ref = senderID_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      senderID_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *  int32 utilityValue = 1;
   * </pre>
   *
   * <code>string senderID = 2;</code>
   * @return The bytes for senderID.
   */
  @Override
  public com.google.protobuf.ByteString
      getSenderIDBytes() {
    Object ref = senderID_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      senderID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (Double.doubleToRawLongBits(utilityValue_) != 0) {
      output.writeDouble(1, utilityValue_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(senderID_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, senderID_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (Double.doubleToRawLongBits(utilityValue_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, utilityValue_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(senderID_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, senderID_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof CallPmPredictionResponse)) {
      return super.equals(obj);
    }
    CallPmPredictionResponse other = (CallPmPredictionResponse) obj;

    if (Double.doubleToLongBits(getUtilityValue())
        != Double.doubleToLongBits(
            other.getUtilityValue())) return false;
    if (!getSenderID()
        .equals(other.getSenderID())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + UTILITYVALUE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        Double.doubleToLongBits(getUtilityValue()));
    hash = (37 * hash) + SENDERID_FIELD_NUMBER;
    hash = (53 * hash) + getSenderID().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static CallPmPredictionResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CallPmPredictionResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CallPmPredictionResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CallPmPredictionResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CallPmPredictionResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CallPmPredictionResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CallPmPredictionResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CallPmPredictionResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static CallPmPredictionResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static CallPmPredictionResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static CallPmPredictionResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CallPmPredictionResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(CallPmPredictionResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code eu.melodic.upperware.utilitygenerator.facade.test.CallPmPredictionResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:eu.melodic.upperware.utilitygenerator.facade.test.CallPmPredictionResponse)
      CallPmPredictionResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Facade.internal_static_eu_melodic_upperware_utilitygenerator_facade_test_CallPmPredictionResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Facade.internal_static_eu_melodic_upperware_utilitygenerator_facade_test_CallPmPredictionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CallPmPredictionResponse.class, Builder.class);
    }

    // Construct using eu.melodic.upperware.utilitygenerator.facade.test.CallPmPredictionResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      utilityValue_ = 0D;

      senderID_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Facade.internal_static_eu_melodic_upperware_utilitygenerator_facade_test_CallPmPredictionResponse_descriptor;
    }

    @Override
    public CallPmPredictionResponse getDefaultInstanceForType() {
      return CallPmPredictionResponse.getDefaultInstance();
    }

    @Override
    public CallPmPredictionResponse build() {
      CallPmPredictionResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public CallPmPredictionResponse buildPartial() {
      CallPmPredictionResponse result = new CallPmPredictionResponse(this);
      result.utilityValue_ = utilityValue_;
      result.senderID_ = senderID_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof CallPmPredictionResponse) {
        return mergeFrom((CallPmPredictionResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(CallPmPredictionResponse other) {
      if (other == CallPmPredictionResponse.getDefaultInstance()) return this;
      if (other.getUtilityValue() != 0D) {
        setUtilityValue(other.getUtilityValue());
      }
      if (!other.getSenderID().isEmpty()) {
        senderID_ = other.senderID_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      CallPmPredictionResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (CallPmPredictionResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private double utilityValue_ ;
    /**
     * <code>double utilityValue = 1;</code>
     * @return The utilityValue.
     */
    @Override
    public double getUtilityValue() {
      return utilityValue_;
    }
    /**
     * <code>double utilityValue = 1;</code>
     * @param value The utilityValue to set.
     * @return This builder for chaining.
     */
    public Builder setUtilityValue(double value) {
      
      utilityValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double utilityValue = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUtilityValue() {
      
      utilityValue_ = 0D;
      onChanged();
      return this;
    }

    private Object senderID_ = "";
    /**
     * <pre>
     *  int32 utilityValue = 1;
     * </pre>
     *
     * <code>string senderID = 2;</code>
     * @return The senderID.
     */
    public String getSenderID() {
      Object ref = senderID_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        senderID_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *  int32 utilityValue = 1;
     * </pre>
     *
     * <code>string senderID = 2;</code>
     * @return The bytes for senderID.
     */
    public com.google.protobuf.ByteString
        getSenderIDBytes() {
      Object ref = senderID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        senderID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *  int32 utilityValue = 1;
     * </pre>
     *
     * <code>string senderID = 2;</code>
     * @param value The senderID to set.
     * @return This builder for chaining.
     */
    public Builder setSenderID(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      senderID_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *  int32 utilityValue = 1;
     * </pre>
     *
     * <code>string senderID = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSenderID() {
      
      senderID_ = getDefaultInstance().getSenderID();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *  int32 utilityValue = 1;
     * </pre>
     *
     * <code>string senderID = 2;</code>
     * @param value The bytes for senderID to set.
     * @return This builder for chaining.
     */
    public Builder setSenderIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      senderID_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:eu.melodic.upperware.utilitygenerator.facade.test.CallPmPredictionResponse)
  }

  // @@protoc_insertion_point(class_scope:eu.melodic.upperware.utilitygenerator.facade.test.CallPmPredictionResponse)
  private static final CallPmPredictionResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new CallPmPredictionResponse();
  }

  public static CallPmPredictionResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CallPmPredictionResponse>
      PARSER = new com.google.protobuf.AbstractParser<CallPmPredictionResponse>() {
    @Override
    public CallPmPredictionResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CallPmPredictionResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CallPmPredictionResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<CallPmPredictionResponse> getParserForType() {
    return PARSER;
  }

  @Override
  public CallPmPredictionResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

