// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: facade.proto

package eu.morphemic.facade.proto.test;

/**
 * Protobuf type {@code eu.melodic.upperware.utilitygenerator.facade.test.CallPmPrediction2}
 */
public final class CallPmPrediction2 extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:eu.melodic.upperware.utilitygenerator.facade.test.CallPmPrediction2)
    CallPmPrediction2OrBuilder {
private static final long serialVersionUID = 0L;
  // Use CallPmPrediction2.newBuilder() to construct.
  private CallPmPrediction2(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CallPmPrediction2() {
    senderID_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new CallPmPrediction2();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CallPmPrediction2(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            Config.Builder subBuilder = null;
            if (dispatcher_ != null) {
              subBuilder = dispatcher_.toBuilder();
            }
            dispatcher_ = input.readMessage(Config.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dispatcher_);
              dispatcher_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            Config.Builder subBuilder = null;
            if (worker_ != null) {
              subBuilder = worker_.toBuilder();
            }
            worker_ = input.readMessage(Config.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(worker_);
              worker_ = subBuilder.buildPartial();
            }

            break;
          }
          case 24: {

            workerMulti_ = input.readInt32();
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            senderID_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Facade.internal_static_eu_melodic_upperware_utilitygenerator_facade_test_CallPmPrediction2_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Facade.internal_static_eu_melodic_upperware_utilitygenerator_facade_test_CallPmPrediction2_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            CallPmPrediction2.class, Builder.class);
  }

  public static final int DISPATCHER_FIELD_NUMBER = 1;
  private Config dispatcher_;
  /**
   * <code>.eu.melodic.upperware.utilitygenerator.facade.test.Config dispatcher = 1;</code>
   * @return Whether the dispatcher field is set.
   */
  @Override
  public boolean hasDispatcher() {
    return dispatcher_ != null;
  }
  /**
   * <code>.eu.melodic.upperware.utilitygenerator.facade.test.Config dispatcher = 1;</code>
   * @return The dispatcher.
   */
  @Override
  public Config getDispatcher() {
    return dispatcher_ == null ? Config.getDefaultInstance() : dispatcher_;
  }
  /**
   * <code>.eu.melodic.upperware.utilitygenerator.facade.test.Config dispatcher = 1;</code>
   */
  @Override
  public ConfigOrBuilder getDispatcherOrBuilder() {
    return getDispatcher();
  }

  public static final int WORKER_FIELD_NUMBER = 2;
  private Config worker_;
  /**
   * <code>.eu.melodic.upperware.utilitygenerator.facade.test.Config worker = 2;</code>
   * @return Whether the worker field is set.
   */
  @Override
  public boolean hasWorker() {
    return worker_ != null;
  }
  /**
   * <code>.eu.melodic.upperware.utilitygenerator.facade.test.Config worker = 2;</code>
   * @return The worker.
   */
  @Override
  public Config getWorker() {
    return worker_ == null ? Config.getDefaultInstance() : worker_;
  }
  /**
   * <code>.eu.melodic.upperware.utilitygenerator.facade.test.Config worker = 2;</code>
   */
  @Override
  public ConfigOrBuilder getWorkerOrBuilder() {
    return getWorker();
  }

  public static final int WORKERMULTI_FIELD_NUMBER = 3;
  private int workerMulti_;
  /**
   * <code>int32 workerMulti = 3;</code>
   * @return The workerMulti.
   */
  @Override
  public int getWorkerMulti() {
    return workerMulti_;
  }

  public static final int SENDERID_FIELD_NUMBER = 4;
  private volatile Object senderID_;
  /**
   * <pre>
   *  facade sender ID
   * </pre>
   *
   * <code>string senderID = 4;</code>
   * @return The senderID.
   */
  @Override
  public String getSenderID() {
    Object ref = senderID_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      senderID_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *  facade sender ID
   * </pre>
   *
   * <code>string senderID = 4;</code>
   * @return The bytes for senderID.
   */
  @Override
  public com.google.protobuf.ByteString
      getSenderIDBytes() {
    Object ref = senderID_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      senderID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (dispatcher_ != null) {
      output.writeMessage(1, getDispatcher());
    }
    if (worker_ != null) {
      output.writeMessage(2, getWorker());
    }
    if (workerMulti_ != 0) {
      output.writeInt32(3, workerMulti_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(senderID_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, senderID_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (dispatcher_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getDispatcher());
    }
    if (worker_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getWorker());
    }
    if (workerMulti_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, workerMulti_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(senderID_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, senderID_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof CallPmPrediction2)) {
      return super.equals(obj);
    }
    CallPmPrediction2 other = (CallPmPrediction2) obj;

    if (hasDispatcher() != other.hasDispatcher()) return false;
    if (hasDispatcher()) {
      if (!getDispatcher()
          .equals(other.getDispatcher())) return false;
    }
    if (hasWorker() != other.hasWorker()) return false;
    if (hasWorker()) {
      if (!getWorker()
          .equals(other.getWorker())) return false;
    }
    if (getWorkerMulti()
        != other.getWorkerMulti()) return false;
    if (!getSenderID()
        .equals(other.getSenderID())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasDispatcher()) {
      hash = (37 * hash) + DISPATCHER_FIELD_NUMBER;
      hash = (53 * hash) + getDispatcher().hashCode();
    }
    if (hasWorker()) {
      hash = (37 * hash) + WORKER_FIELD_NUMBER;
      hash = (53 * hash) + getWorker().hashCode();
    }
    hash = (37 * hash) + WORKERMULTI_FIELD_NUMBER;
    hash = (53 * hash) + getWorkerMulti();
    hash = (37 * hash) + SENDERID_FIELD_NUMBER;
    hash = (53 * hash) + getSenderID().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static CallPmPrediction2 parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CallPmPrediction2 parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CallPmPrediction2 parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CallPmPrediction2 parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CallPmPrediction2 parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CallPmPrediction2 parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CallPmPrediction2 parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CallPmPrediction2 parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static CallPmPrediction2 parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static CallPmPrediction2 parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static CallPmPrediction2 parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CallPmPrediction2 parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(CallPmPrediction2 prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code eu.melodic.upperware.utilitygenerator.facade.test.CallPmPrediction2}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:eu.melodic.upperware.utilitygenerator.facade.test.CallPmPrediction2)
      CallPmPrediction2OrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Facade.internal_static_eu_melodic_upperware_utilitygenerator_facade_test_CallPmPrediction2_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Facade.internal_static_eu_melodic_upperware_utilitygenerator_facade_test_CallPmPrediction2_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CallPmPrediction2.class, Builder.class);
    }

    // Construct using eu.melodic.upperware.utilitygenerator.facade.test.CallPmPrediction2.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      if (dispatcherBuilder_ == null) {
        dispatcher_ = null;
      } else {
        dispatcher_ = null;
        dispatcherBuilder_ = null;
      }
      if (workerBuilder_ == null) {
        worker_ = null;
      } else {
        worker_ = null;
        workerBuilder_ = null;
      }
      workerMulti_ = 0;

      senderID_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Facade.internal_static_eu_melodic_upperware_utilitygenerator_facade_test_CallPmPrediction2_descriptor;
    }

    @Override
    public CallPmPrediction2 getDefaultInstanceForType() {
      return CallPmPrediction2.getDefaultInstance();
    }

    @Override
    public CallPmPrediction2 build() {
      CallPmPrediction2 result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public CallPmPrediction2 buildPartial() {
      CallPmPrediction2 result = new CallPmPrediction2(this);
      if (dispatcherBuilder_ == null) {
        result.dispatcher_ = dispatcher_;
      } else {
        result.dispatcher_ = dispatcherBuilder_.build();
      }
      if (workerBuilder_ == null) {
        result.worker_ = worker_;
      } else {
        result.worker_ = workerBuilder_.build();
      }
      result.workerMulti_ = workerMulti_;
      result.senderID_ = senderID_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof CallPmPrediction2) {
        return mergeFrom((CallPmPrediction2)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(CallPmPrediction2 other) {
      if (other == CallPmPrediction2.getDefaultInstance()) return this;
      if (other.hasDispatcher()) {
        mergeDispatcher(other.getDispatcher());
      }
      if (other.hasWorker()) {
        mergeWorker(other.getWorker());
      }
      if (other.getWorkerMulti() != 0) {
        setWorkerMulti(other.getWorkerMulti());
      }
      if (!other.getSenderID().isEmpty()) {
        senderID_ = other.senderID_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      CallPmPrediction2 parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (CallPmPrediction2) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Config dispatcher_;
    private com.google.protobuf.SingleFieldBuilderV3<
        Config, Config.Builder, ConfigOrBuilder> dispatcherBuilder_;
    /**
     * <code>.eu.melodic.upperware.utilitygenerator.facade.test.Config dispatcher = 1;</code>
     * @return Whether the dispatcher field is set.
     */
    public boolean hasDispatcher() {
      return dispatcherBuilder_ != null || dispatcher_ != null;
    }
    /**
     * <code>.eu.melodic.upperware.utilitygenerator.facade.test.Config dispatcher = 1;</code>
     * @return The dispatcher.
     */
    public Config getDispatcher() {
      if (dispatcherBuilder_ == null) {
        return dispatcher_ == null ? Config.getDefaultInstance() : dispatcher_;
      } else {
        return dispatcherBuilder_.getMessage();
      }
    }
    /**
     * <code>.eu.melodic.upperware.utilitygenerator.facade.test.Config dispatcher = 1;</code>
     */
    public Builder setDispatcher(Config value) {
      if (dispatcherBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dispatcher_ = value;
        onChanged();
      } else {
        dispatcherBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.eu.melodic.upperware.utilitygenerator.facade.test.Config dispatcher = 1;</code>
     */
    public Builder setDispatcher(
        Config.Builder builderForValue) {
      if (dispatcherBuilder_ == null) {
        dispatcher_ = builderForValue.build();
        onChanged();
      } else {
        dispatcherBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.eu.melodic.upperware.utilitygenerator.facade.test.Config dispatcher = 1;</code>
     */
    public Builder mergeDispatcher(Config value) {
      if (dispatcherBuilder_ == null) {
        if (dispatcher_ != null) {
          dispatcher_ =
            Config.newBuilder(dispatcher_).mergeFrom(value).buildPartial();
        } else {
          dispatcher_ = value;
        }
        onChanged();
      } else {
        dispatcherBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.eu.melodic.upperware.utilitygenerator.facade.test.Config dispatcher = 1;</code>
     */
    public Builder clearDispatcher() {
      if (dispatcherBuilder_ == null) {
        dispatcher_ = null;
        onChanged();
      } else {
        dispatcher_ = null;
        dispatcherBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.eu.melodic.upperware.utilitygenerator.facade.test.Config dispatcher = 1;</code>
     */
    public Config.Builder getDispatcherBuilder() {
      
      onChanged();
      return getDispatcherFieldBuilder().getBuilder();
    }
    /**
     * <code>.eu.melodic.upperware.utilitygenerator.facade.test.Config dispatcher = 1;</code>
     */
    public ConfigOrBuilder getDispatcherOrBuilder() {
      if (dispatcherBuilder_ != null) {
        return dispatcherBuilder_.getMessageOrBuilder();
      } else {
        return dispatcher_ == null ?
            Config.getDefaultInstance() : dispatcher_;
      }
    }
    /**
     * <code>.eu.melodic.upperware.utilitygenerator.facade.test.Config dispatcher = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Config, Config.Builder, ConfigOrBuilder>
        getDispatcherFieldBuilder() {
      if (dispatcherBuilder_ == null) {
        dispatcherBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Config, Config.Builder, ConfigOrBuilder>(
                getDispatcher(),
                getParentForChildren(),
                isClean());
        dispatcher_ = null;
      }
      return dispatcherBuilder_;
    }

    private Config worker_;
    private com.google.protobuf.SingleFieldBuilderV3<
        Config, Config.Builder, ConfigOrBuilder> workerBuilder_;
    /**
     * <code>.eu.melodic.upperware.utilitygenerator.facade.test.Config worker = 2;</code>
     * @return Whether the worker field is set.
     */
    public boolean hasWorker() {
      return workerBuilder_ != null || worker_ != null;
    }
    /**
     * <code>.eu.melodic.upperware.utilitygenerator.facade.test.Config worker = 2;</code>
     * @return The worker.
     */
    public Config getWorker() {
      if (workerBuilder_ == null) {
        return worker_ == null ? Config.getDefaultInstance() : worker_;
      } else {
        return workerBuilder_.getMessage();
      }
    }
    /**
     * <code>.eu.melodic.upperware.utilitygenerator.facade.test.Config worker = 2;</code>
     */
    public Builder setWorker(Config value) {
      if (workerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        worker_ = value;
        onChanged();
      } else {
        workerBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.eu.melodic.upperware.utilitygenerator.facade.test.Config worker = 2;</code>
     */
    public Builder setWorker(
        Config.Builder builderForValue) {
      if (workerBuilder_ == null) {
        worker_ = builderForValue.build();
        onChanged();
      } else {
        workerBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.eu.melodic.upperware.utilitygenerator.facade.test.Config worker = 2;</code>
     */
    public Builder mergeWorker(Config value) {
      if (workerBuilder_ == null) {
        if (worker_ != null) {
          worker_ =
            Config.newBuilder(worker_).mergeFrom(value).buildPartial();
        } else {
          worker_ = value;
        }
        onChanged();
      } else {
        workerBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.eu.melodic.upperware.utilitygenerator.facade.test.Config worker = 2;</code>
     */
    public Builder clearWorker() {
      if (workerBuilder_ == null) {
        worker_ = null;
        onChanged();
      } else {
        worker_ = null;
        workerBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.eu.melodic.upperware.utilitygenerator.facade.test.Config worker = 2;</code>
     */
    public Config.Builder getWorkerBuilder() {
      
      onChanged();
      return getWorkerFieldBuilder().getBuilder();
    }
    /**
     * <code>.eu.melodic.upperware.utilitygenerator.facade.test.Config worker = 2;</code>
     */
    public ConfigOrBuilder getWorkerOrBuilder() {
      if (workerBuilder_ != null) {
        return workerBuilder_.getMessageOrBuilder();
      } else {
        return worker_ == null ?
            Config.getDefaultInstance() : worker_;
      }
    }
    /**
     * <code>.eu.melodic.upperware.utilitygenerator.facade.test.Config worker = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Config, Config.Builder, ConfigOrBuilder>
        getWorkerFieldBuilder() {
      if (workerBuilder_ == null) {
        workerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Config, Config.Builder, ConfigOrBuilder>(
                getWorker(),
                getParentForChildren(),
                isClean());
        worker_ = null;
      }
      return workerBuilder_;
    }

    private int workerMulti_ ;
    /**
     * <code>int32 workerMulti = 3;</code>
     * @return The workerMulti.
     */
    @Override
    public int getWorkerMulti() {
      return workerMulti_;
    }
    /**
     * <code>int32 workerMulti = 3;</code>
     * @param value The workerMulti to set.
     * @return This builder for chaining.
     */
    public Builder setWorkerMulti(int value) {
      
      workerMulti_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 workerMulti = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearWorkerMulti() {
      
      workerMulti_ = 0;
      onChanged();
      return this;
    }

    private Object senderID_ = "";
    /**
     * <pre>
     *  facade sender ID
     * </pre>
     *
     * <code>string senderID = 4;</code>
     * @return The senderID.
     */
    public String getSenderID() {
      Object ref = senderID_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        senderID_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *  facade sender ID
     * </pre>
     *
     * <code>string senderID = 4;</code>
     * @return The bytes for senderID.
     */
    public com.google.protobuf.ByteString
        getSenderIDBytes() {
      Object ref = senderID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        senderID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *  facade sender ID
     * </pre>
     *
     * <code>string senderID = 4;</code>
     * @param value The senderID to set.
     * @return This builder for chaining.
     */
    public Builder setSenderID(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      senderID_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *  facade sender ID
     * </pre>
     *
     * <code>string senderID = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSenderID() {
      
      senderID_ = getDefaultInstance().getSenderID();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *  facade sender ID
     * </pre>
     *
     * <code>string senderID = 4;</code>
     * @param value The bytes for senderID to set.
     * @return This builder for chaining.
     */
    public Builder setSenderIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      senderID_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:eu.melodic.upperware.utilitygenerator.facade.test.CallPmPrediction2)
  }

  // @@protoc_insertion_point(class_scope:eu.melodic.upperware.utilitygenerator.facade.test.CallPmPrediction2)
  private static final CallPmPrediction2 DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new CallPmPrediction2();
  }

  public static CallPmPrediction2 getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CallPmPrediction2>
      PARSER = new com.google.protobuf.AbstractParser<CallPmPrediction2>() {
    @Override
    public CallPmPrediction2 parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CallPmPrediction2(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CallPmPrediction2> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<CallPmPrediction2> getParserForType() {
    return PARSER;
  }

  @Override
  public CallPmPrediction2 getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

