// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: facade.proto

package eu.morphemic.facade.proto.test;

public interface CallPmPredictionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:eu.melodic.upperware.utilitygenerator.facade.test.CallPmPredictionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double utilityValue = 1;</code>
   * @return The utilityValue.
   */
  double getUtilityValue();

  /**
   * <pre>
   *  int32 utilityValue = 1;
   * </pre>
   *
   * <code>string senderID = 2;</code>
   * @return The senderID.
   */
  String getSenderID();
  /**
   * <pre>
   *  int32 utilityValue = 1;
   * </pre>
   *
   * <code>string senderID = 2;</code>
   * @return The bytes for senderID.
   */
  com.google.protobuf.ByteString
      getSenderIDBytes();
}
