// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: facade.proto

package eu.morphemic.facade.proto.test;

public interface CallPmPredictionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:eu.melodic.upperware.utilitygenerator.facade.test.CallPmPrediction)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 dispatcherCores = 1;</code>
   * @return The dispatcherCores.
   */
  int getDispatcherCores();

  /**
   * <code>int32 dispatcherRam = 2;</code>
   * @return The dispatcherRam.
   */
  int getDispatcherRam();

  /**
   * <code>string dispatcherLocation = 3;</code>
   * @return The dispatcherLocation.
   */
  String getDispatcherLocation();
  /**
   * <code>string dispatcherLocation = 3;</code>
   * @return The bytes for dispatcherLocation.
   */
  com.google.protobuf.ByteString
      getDispatcherLocationBytes();

  /**
   * <code>int32 workerCores = 4;</code>
   * @return The workerCores.
   */
  int getWorkerCores();

  /**
   * <code>int32 workerRam = 5;</code>
   * @return The workerRam.
   */
  int getWorkerRam();

  /**
   * <code>string workerLocation = 6;</code>
   * @return The workerLocation.
   */
  String getWorkerLocation();
  /**
   * <code>string workerLocation = 6;</code>
   * @return The bytes for workerLocation.
   */
  com.google.protobuf.ByteString
      getWorkerLocationBytes();

  /**
   * <code>int32 workerMulti = 7;</code>
   * @return The workerMulti.
   */
  int getWorkerMulti();

  /**
   * <pre>
   *  facade sender ID
   * </pre>
   *
   * <code>string senderID = 8;</code>
   * @return The senderID.
   */
  String getSenderID();
  /**
   * <pre>
   *  facade sender ID
   * </pre>
   *
   * <code>string senderID = 8;</code>
   * @return The bytes for senderID.
   */
  com.google.protobuf.ByteString
      getSenderIDBytes();
}
