// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: facade.proto

package eu.morphemic.facade.proto.test;

/**
 * Protobuf type {@code eu.melodic.upperware.utilitygenerator.facade.test.CallPmPrediction}
 */
public final class CallPmPrediction extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:eu.melodic.upperware.utilitygenerator.facade.test.CallPmPrediction)
    CallPmPredictionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CallPmPrediction.newBuilder() to construct.
  private CallPmPrediction(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CallPmPrediction() {
    dispatcherLocation_ = "";
    workerLocation_ = "";
    senderID_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new CallPmPrediction();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CallPmPrediction(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            dispatcherCores_ = input.readInt32();
            break;
          }
          case 16: {

            dispatcherRam_ = input.readInt32();
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            dispatcherLocation_ = s;
            break;
          }
          case 32: {

            workerCores_ = input.readInt32();
            break;
          }
          case 40: {

            workerRam_ = input.readInt32();
            break;
          }
          case 50: {
            String s = input.readStringRequireUtf8();

            workerLocation_ = s;
            break;
          }
          case 56: {

            workerMulti_ = input.readInt32();
            break;
          }
          case 66: {
            String s = input.readStringRequireUtf8();

            senderID_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Facade.internal_static_eu_melodic_upperware_utilitygenerator_facade_test_CallPmPrediction_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Facade.internal_static_eu_melodic_upperware_utilitygenerator_facade_test_CallPmPrediction_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            CallPmPrediction.class, Builder.class);
  }

  public static final int DISPATCHERCORES_FIELD_NUMBER = 1;
  private int dispatcherCores_;
  /**
   * <code>int32 dispatcherCores = 1;</code>
   * @return The dispatcherCores.
   */
  @Override
  public int getDispatcherCores() {
    return dispatcherCores_;
  }

  public static final int DISPATCHERRAM_FIELD_NUMBER = 2;
  private int dispatcherRam_;
  /**
   * <code>int32 dispatcherRam = 2;</code>
   * @return The dispatcherRam.
   */
  @Override
  public int getDispatcherRam() {
    return dispatcherRam_;
  }

  public static final int DISPATCHERLOCATION_FIELD_NUMBER = 3;
  private volatile Object dispatcherLocation_;
  /**
   * <code>string dispatcherLocation = 3;</code>
   * @return The dispatcherLocation.
   */
  @Override
  public String getDispatcherLocation() {
    Object ref = dispatcherLocation_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      dispatcherLocation_ = s;
      return s;
    }
  }
  /**
   * <code>string dispatcherLocation = 3;</code>
   * @return The bytes for dispatcherLocation.
   */
  @Override
  public com.google.protobuf.ByteString
      getDispatcherLocationBytes() {
    Object ref = dispatcherLocation_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      dispatcherLocation_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WORKERCORES_FIELD_NUMBER = 4;
  private int workerCores_;
  /**
   * <code>int32 workerCores = 4;</code>
   * @return The workerCores.
   */
  @Override
  public int getWorkerCores() {
    return workerCores_;
  }

  public static final int WORKERRAM_FIELD_NUMBER = 5;
  private int workerRam_;
  /**
   * <code>int32 workerRam = 5;</code>
   * @return The workerRam.
   */
  @Override
  public int getWorkerRam() {
    return workerRam_;
  }

  public static final int WORKERLOCATION_FIELD_NUMBER = 6;
  private volatile Object workerLocation_;
  /**
   * <code>string workerLocation = 6;</code>
   * @return The workerLocation.
   */
  @Override
  public String getWorkerLocation() {
    Object ref = workerLocation_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      workerLocation_ = s;
      return s;
    }
  }
  /**
   * <code>string workerLocation = 6;</code>
   * @return The bytes for workerLocation.
   */
  @Override
  public com.google.protobuf.ByteString
      getWorkerLocationBytes() {
    Object ref = workerLocation_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      workerLocation_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WORKERMULTI_FIELD_NUMBER = 7;
  private int workerMulti_;
  /**
   * <code>int32 workerMulti = 7;</code>
   * @return The workerMulti.
   */
  @Override
  public int getWorkerMulti() {
    return workerMulti_;
  }

  public static final int SENDERID_FIELD_NUMBER = 8;
  private volatile Object senderID_;
  /**
   * <pre>
   *  facade sender ID
   * </pre>
   *
   * <code>string senderID = 8;</code>
   * @return The senderID.
   */
  @Override
  public String getSenderID() {
    Object ref = senderID_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      senderID_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *  facade sender ID
   * </pre>
   *
   * <code>string senderID = 8;</code>
   * @return The bytes for senderID.
   */
  @Override
  public com.google.protobuf.ByteString
      getSenderIDBytes() {
    Object ref = senderID_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      senderID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (dispatcherCores_ != 0) {
      output.writeInt32(1, dispatcherCores_);
    }
    if (dispatcherRam_ != 0) {
      output.writeInt32(2, dispatcherRam_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dispatcherLocation_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, dispatcherLocation_);
    }
    if (workerCores_ != 0) {
      output.writeInt32(4, workerCores_);
    }
    if (workerRam_ != 0) {
      output.writeInt32(5, workerRam_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(workerLocation_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, workerLocation_);
    }
    if (workerMulti_ != 0) {
      output.writeInt32(7, workerMulti_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(senderID_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, senderID_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (dispatcherCores_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, dispatcherCores_);
    }
    if (dispatcherRam_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, dispatcherRam_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dispatcherLocation_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, dispatcherLocation_);
    }
    if (workerCores_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, workerCores_);
    }
    if (workerRam_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, workerRam_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(workerLocation_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, workerLocation_);
    }
    if (workerMulti_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, workerMulti_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(senderID_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, senderID_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof CallPmPrediction)) {
      return super.equals(obj);
    }
    CallPmPrediction other = (CallPmPrediction) obj;

    if (getDispatcherCores()
        != other.getDispatcherCores()) return false;
    if (getDispatcherRam()
        != other.getDispatcherRam()) return false;
    if (!getDispatcherLocation()
        .equals(other.getDispatcherLocation())) return false;
    if (getWorkerCores()
        != other.getWorkerCores()) return false;
    if (getWorkerRam()
        != other.getWorkerRam()) return false;
    if (!getWorkerLocation()
        .equals(other.getWorkerLocation())) return false;
    if (getWorkerMulti()
        != other.getWorkerMulti()) return false;
    if (!getSenderID()
        .equals(other.getSenderID())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DISPATCHERCORES_FIELD_NUMBER;
    hash = (53 * hash) + getDispatcherCores();
    hash = (37 * hash) + DISPATCHERRAM_FIELD_NUMBER;
    hash = (53 * hash) + getDispatcherRam();
    hash = (37 * hash) + DISPATCHERLOCATION_FIELD_NUMBER;
    hash = (53 * hash) + getDispatcherLocation().hashCode();
    hash = (37 * hash) + WORKERCORES_FIELD_NUMBER;
    hash = (53 * hash) + getWorkerCores();
    hash = (37 * hash) + WORKERRAM_FIELD_NUMBER;
    hash = (53 * hash) + getWorkerRam();
    hash = (37 * hash) + WORKERLOCATION_FIELD_NUMBER;
    hash = (53 * hash) + getWorkerLocation().hashCode();
    hash = (37 * hash) + WORKERMULTI_FIELD_NUMBER;
    hash = (53 * hash) + getWorkerMulti();
    hash = (37 * hash) + SENDERID_FIELD_NUMBER;
    hash = (53 * hash) + getSenderID().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static CallPmPrediction parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CallPmPrediction parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CallPmPrediction parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CallPmPrediction parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CallPmPrediction parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CallPmPrediction parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CallPmPrediction parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CallPmPrediction parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static CallPmPrediction parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static CallPmPrediction parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static CallPmPrediction parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CallPmPrediction parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(CallPmPrediction prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code eu.melodic.upperware.utilitygenerator.facade.test.CallPmPrediction}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:eu.melodic.upperware.utilitygenerator.facade.test.CallPmPrediction)
      CallPmPredictionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Facade.internal_static_eu_melodic_upperware_utilitygenerator_facade_test_CallPmPrediction_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Facade.internal_static_eu_melodic_upperware_utilitygenerator_facade_test_CallPmPrediction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CallPmPrediction.class, Builder.class);
    }

    // Construct using eu.melodic.upperware.utilitygenerator.facade.test.CallPmPrediction.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      dispatcherCores_ = 0;

      dispatcherRam_ = 0;

      dispatcherLocation_ = "";

      workerCores_ = 0;

      workerRam_ = 0;

      workerLocation_ = "";

      workerMulti_ = 0;

      senderID_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Facade.internal_static_eu_melodic_upperware_utilitygenerator_facade_test_CallPmPrediction_descriptor;
    }

    @Override
    public CallPmPrediction getDefaultInstanceForType() {
      return CallPmPrediction.getDefaultInstance();
    }

    @Override
    public CallPmPrediction build() {
      CallPmPrediction result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public CallPmPrediction buildPartial() {
      CallPmPrediction result = new CallPmPrediction(this);
      result.dispatcherCores_ = dispatcherCores_;
      result.dispatcherRam_ = dispatcherRam_;
      result.dispatcherLocation_ = dispatcherLocation_;
      result.workerCores_ = workerCores_;
      result.workerRam_ = workerRam_;
      result.workerLocation_ = workerLocation_;
      result.workerMulti_ = workerMulti_;
      result.senderID_ = senderID_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof CallPmPrediction) {
        return mergeFrom((CallPmPrediction)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(CallPmPrediction other) {
      if (other == CallPmPrediction.getDefaultInstance()) return this;
      if (other.getDispatcherCores() != 0) {
        setDispatcherCores(other.getDispatcherCores());
      }
      if (other.getDispatcherRam() != 0) {
        setDispatcherRam(other.getDispatcherRam());
      }
      if (!other.getDispatcherLocation().isEmpty()) {
        dispatcherLocation_ = other.dispatcherLocation_;
        onChanged();
      }
      if (other.getWorkerCores() != 0) {
        setWorkerCores(other.getWorkerCores());
      }
      if (other.getWorkerRam() != 0) {
        setWorkerRam(other.getWorkerRam());
      }
      if (!other.getWorkerLocation().isEmpty()) {
        workerLocation_ = other.workerLocation_;
        onChanged();
      }
      if (other.getWorkerMulti() != 0) {
        setWorkerMulti(other.getWorkerMulti());
      }
      if (!other.getSenderID().isEmpty()) {
        senderID_ = other.senderID_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      CallPmPrediction parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (CallPmPrediction) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int dispatcherCores_ ;
    /**
     * <code>int32 dispatcherCores = 1;</code>
     * @return The dispatcherCores.
     */
    @Override
    public int getDispatcherCores() {
      return dispatcherCores_;
    }
    /**
     * <code>int32 dispatcherCores = 1;</code>
     * @param value The dispatcherCores to set.
     * @return This builder for chaining.
     */
    public Builder setDispatcherCores(int value) {
      
      dispatcherCores_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 dispatcherCores = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDispatcherCores() {
      
      dispatcherCores_ = 0;
      onChanged();
      return this;
    }

    private int dispatcherRam_ ;
    /**
     * <code>int32 dispatcherRam = 2;</code>
     * @return The dispatcherRam.
     */
    @Override
    public int getDispatcherRam() {
      return dispatcherRam_;
    }
    /**
     * <code>int32 dispatcherRam = 2;</code>
     * @param value The dispatcherRam to set.
     * @return This builder for chaining.
     */
    public Builder setDispatcherRam(int value) {
      
      dispatcherRam_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 dispatcherRam = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDispatcherRam() {
      
      dispatcherRam_ = 0;
      onChanged();
      return this;
    }

    private Object dispatcherLocation_ = "";
    /**
     * <code>string dispatcherLocation = 3;</code>
     * @return The dispatcherLocation.
     */
    public String getDispatcherLocation() {
      Object ref = dispatcherLocation_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        dispatcherLocation_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string dispatcherLocation = 3;</code>
     * @return The bytes for dispatcherLocation.
     */
    public com.google.protobuf.ByteString
        getDispatcherLocationBytes() {
      Object ref = dispatcherLocation_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        dispatcherLocation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dispatcherLocation = 3;</code>
     * @param value The dispatcherLocation to set.
     * @return This builder for chaining.
     */
    public Builder setDispatcherLocation(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dispatcherLocation_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string dispatcherLocation = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDispatcherLocation() {
      
      dispatcherLocation_ = getDefaultInstance().getDispatcherLocation();
      onChanged();
      return this;
    }
    /**
     * <code>string dispatcherLocation = 3;</code>
     * @param value The bytes for dispatcherLocation to set.
     * @return This builder for chaining.
     */
    public Builder setDispatcherLocationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dispatcherLocation_ = value;
      onChanged();
      return this;
    }

    private int workerCores_ ;
    /**
     * <code>int32 workerCores = 4;</code>
     * @return The workerCores.
     */
    @Override
    public int getWorkerCores() {
      return workerCores_;
    }
    /**
     * <code>int32 workerCores = 4;</code>
     * @param value The workerCores to set.
     * @return This builder for chaining.
     */
    public Builder setWorkerCores(int value) {
      
      workerCores_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 workerCores = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearWorkerCores() {
      
      workerCores_ = 0;
      onChanged();
      return this;
    }

    private int workerRam_ ;
    /**
     * <code>int32 workerRam = 5;</code>
     * @return The workerRam.
     */
    @Override
    public int getWorkerRam() {
      return workerRam_;
    }
    /**
     * <code>int32 workerRam = 5;</code>
     * @param value The workerRam to set.
     * @return This builder for chaining.
     */
    public Builder setWorkerRam(int value) {
      
      workerRam_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 workerRam = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearWorkerRam() {
      
      workerRam_ = 0;
      onChanged();
      return this;
    }

    private Object workerLocation_ = "";
    /**
     * <code>string workerLocation = 6;</code>
     * @return The workerLocation.
     */
    public String getWorkerLocation() {
      Object ref = workerLocation_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        workerLocation_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string workerLocation = 6;</code>
     * @return The bytes for workerLocation.
     */
    public com.google.protobuf.ByteString
        getWorkerLocationBytes() {
      Object ref = workerLocation_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        workerLocation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string workerLocation = 6;</code>
     * @param value The workerLocation to set.
     * @return This builder for chaining.
     */
    public Builder setWorkerLocation(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      workerLocation_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string workerLocation = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearWorkerLocation() {
      
      workerLocation_ = getDefaultInstance().getWorkerLocation();
      onChanged();
      return this;
    }
    /**
     * <code>string workerLocation = 6;</code>
     * @param value The bytes for workerLocation to set.
     * @return This builder for chaining.
     */
    public Builder setWorkerLocationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      workerLocation_ = value;
      onChanged();
      return this;
    }

    private int workerMulti_ ;
    /**
     * <code>int32 workerMulti = 7;</code>
     * @return The workerMulti.
     */
    @Override
    public int getWorkerMulti() {
      return workerMulti_;
    }
    /**
     * <code>int32 workerMulti = 7;</code>
     * @param value The workerMulti to set.
     * @return This builder for chaining.
     */
    public Builder setWorkerMulti(int value) {
      
      workerMulti_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 workerMulti = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearWorkerMulti() {
      
      workerMulti_ = 0;
      onChanged();
      return this;
    }

    private Object senderID_ = "";
    /**
     * <pre>
     *  facade sender ID
     * </pre>
     *
     * <code>string senderID = 8;</code>
     * @return The senderID.
     */
    public String getSenderID() {
      Object ref = senderID_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        senderID_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *  facade sender ID
     * </pre>
     *
     * <code>string senderID = 8;</code>
     * @return The bytes for senderID.
     */
    public com.google.protobuf.ByteString
        getSenderIDBytes() {
      Object ref = senderID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        senderID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *  facade sender ID
     * </pre>
     *
     * <code>string senderID = 8;</code>
     * @param value The senderID to set.
     * @return This builder for chaining.
     */
    public Builder setSenderID(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      senderID_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *  facade sender ID
     * </pre>
     *
     * <code>string senderID = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearSenderID() {
      
      senderID_ = getDefaultInstance().getSenderID();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *  facade sender ID
     * </pre>
     *
     * <code>string senderID = 8;</code>
     * @param value The bytes for senderID to set.
     * @return This builder for chaining.
     */
    public Builder setSenderIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      senderID_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:eu.melodic.upperware.utilitygenerator.facade.test.CallPmPrediction)
  }

  // @@protoc_insertion_point(class_scope:eu.melodic.upperware.utilitygenerator.facade.test.CallPmPrediction)
  private static final CallPmPrediction DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new CallPmPrediction();
  }

  public static CallPmPrediction getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CallPmPrediction>
      PARSER = new com.google.protobuf.AbstractParser<CallPmPrediction>() {
    @Override
    public CallPmPrediction parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CallPmPrediction(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CallPmPrediction> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<CallPmPrediction> getParserForType() {
    return PARSER;
  }

  @Override
  public CallPmPrediction getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

