// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: facade.proto

package eu.morphemic.facade.proto.test;

public interface CallPmPrediction2OrBuilder extends
    // @@protoc_insertion_point(interface_extends:eu.melodic.upperware.utilitygenerator.facade.test.CallPmPrediction2)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.eu.melodic.upperware.utilitygenerator.facade.test.Config dispatcher = 1;</code>
   * @return Whether the dispatcher field is set.
   */
  boolean hasDispatcher();
  /**
   * <code>.eu.melodic.upperware.utilitygenerator.facade.test.Config dispatcher = 1;</code>
   * @return The dispatcher.
   */
  Config getDispatcher();
  /**
   * <code>.eu.melodic.upperware.utilitygenerator.facade.test.Config dispatcher = 1;</code>
   */
  ConfigOrBuilder getDispatcherOrBuilder();

  /**
   * <code>.eu.melodic.upperware.utilitygenerator.facade.test.Config worker = 2;</code>
   * @return Whether the worker field is set.
   */
  boolean hasWorker();
  /**
   * <code>.eu.melodic.upperware.utilitygenerator.facade.test.Config worker = 2;</code>
   * @return The worker.
   */
  Config getWorker();
  /**
   * <code>.eu.melodic.upperware.utilitygenerator.facade.test.Config worker = 2;</code>
   */
  ConfigOrBuilder getWorkerOrBuilder();

  /**
   * <code>int32 workerMulti = 3;</code>
   * @return The workerMulti.
   */
  int getWorkerMulti();

  /**
   * <pre>
   *  facade sender ID
   * </pre>
   *
   * <code>string senderID = 4;</code>
   * @return The senderID.
   */
  String getSenderID();
  /**
   * <pre>
   *  facade sender ID
   * </pre>
   *
   * <code>string senderID = 4;</code>
   * @return The bytes for senderID.
   */
  com.google.protobuf.ByteString
      getSenderIDBytes();
}
