// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: facade.proto

package eu.morphemic.facade.proto.test;

public interface ConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:eu.melodic.upperware.utilitygenerator.facade.test.Config)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 cores = 1;</code>
   * @return The cores.
   */
  int getCores();

  /**
   * <code>int32 ram = 2;</code>
   * @return The ram.
   */
  int getRam();

  /**
   * <code>string location = 3;</code>
   * @return The location.
   */
  String getLocation();
  /**
   * <code>string location = 3;</code>
   * @return The bytes for location.
   */
  com.google.protobuf.ByteString
      getLocationBytes();
}
