// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: facade.proto

package eu.morphemic.facade.proto.test;

public final class Facade {
  private Facade() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eu_melodic_upperware_utilitygenerator_facade_test_CallPmPrediction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_eu_melodic_upperware_utilitygenerator_facade_test_CallPmPrediction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eu_melodic_upperware_utilitygenerator_facade_test_Config_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_eu_melodic_upperware_utilitygenerator_facade_test_Config_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eu_melodic_upperware_utilitygenerator_facade_test_CallPmPrediction2_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_eu_melodic_upperware_utilitygenerator_facade_test_CallPmPrediction2_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eu_melodic_upperware_utilitygenerator_facade_test_CallPmPredictionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_eu_melodic_upperware_utilitygenerator_facade_test_CallPmPredictionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014facade.proto\0221eu.melodic.upperware.uti" +
      "litygenerator.facade.test\"\305\001\n\020CallPmPred" +
      "iction\022\027\n\017dispatcherCores\030\001 \001(\005\022\025\n\rdispa" +
      "tcherRam\030\002 \001(\005\022\032\n\022dispatcherLocation\030\003 \001" +
      "(\t\022\023\n\013workerCores\030\004 \001(\005\022\021\n\tworkerRam\030\005 \001" +
      "(\005\022\026\n\016workerLocation\030\006 \001(\t\022\023\n\013workerMult" +
      "i\030\007 \001(\005\022\020\n\010senderID\030\010 \001(\t\"6\n\006Config\022\r\n\005c" +
      "ores\030\001 \001(\005\022\013\n\003ram\030\002 \001(\005\022\020\n\010location\030\003 \001(" +
      "\t\"\324\001\n\021CallPmPrediction2\022M\n\ndispatcher\030\001 " +
      "\001(\01329.eu.melodic.upperware.utilitygenera" +
      "tor.facade.test.Config\022I\n\006worker\030\002 \001(\01329" +
      ".eu.melodic.upperware.utilitygenerator.f" +
      "acade.test.Config\022\023\n\013workerMulti\030\003 \001(\005\022\020" +
      "\n\010senderID\030\004 \001(\t\"B\n\030CallPmPredictionResp" +
      "onse\022\024\n\014utilityValue\030\001 \001(\001\022\020\n\010senderID\030\002" +
      " \001(\tB7\n1eu.melodic.upperware.utilitygene" +
      "rator.facade.testH\001P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_eu_melodic_upperware_utilitygenerator_facade_test_CallPmPrediction_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_eu_melodic_upperware_utilitygenerator_facade_test_CallPmPrediction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_eu_melodic_upperware_utilitygenerator_facade_test_CallPmPrediction_descriptor,
        new String[] { "DispatcherCores", "DispatcherRam", "DispatcherLocation", "WorkerCores", "WorkerRam", "WorkerLocation", "WorkerMulti", "SenderID", });
    internal_static_eu_melodic_upperware_utilitygenerator_facade_test_Config_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_eu_melodic_upperware_utilitygenerator_facade_test_Config_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_eu_melodic_upperware_utilitygenerator_facade_test_Config_descriptor,
        new String[] { "Cores", "Ram", "Location", });
    internal_static_eu_melodic_upperware_utilitygenerator_facade_test_CallPmPrediction2_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_eu_melodic_upperware_utilitygenerator_facade_test_CallPmPrediction2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_eu_melodic_upperware_utilitygenerator_facade_test_CallPmPrediction2_descriptor,
        new String[] { "Dispatcher", "Worker", "WorkerMulti", "SenderID", });
    internal_static_eu_melodic_upperware_utilitygenerator_facade_test_CallPmPredictionResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_eu_melodic_upperware_utilitygenerator_facade_test_CallPmPredictionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_eu_melodic_upperware_utilitygenerator_facade_test_CallPmPredictionResponse_descriptor,
        new String[] { "UtilityValue", "SenderID", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
