##Testing with the db
spring.jpa.hibernate.ddl-auto=create
spring.datasource.url=jdbc:mysql://localhost:3306/db_schema
spring.datasource.username=user
spring.datasource.password=test









#### Communication with ESB ####
#esb.url=http://localhost:8088/api/solverToDeployment
#esb.url=http://94.177.187.234:8088
#### REST interface port ####
#server.port = 8082



#hostname where CDO Server resides
#host=134.60.64.43
#port on which CDO Server listens
#port=2036
#the name of the CDO repository of the server
#repository=repo1
#logging to be set off or on - default is off
#logging=off



#hsqldb connection properties
#dbtype=hsqldb
#dburl=jdbc:hsqldb:file:cdohibernate
#username=sa
#password=

#type of store to be created
#storetype=hibernate

#
#bin.includes = .,\
#               META-INF/,\
#               plugin.xml,\
#               plugin.properties
#               model/,\
#jars.compile.order = .
#source.. = src/main/java, src/test/java, src/main/resources
#output.. = bin