<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="eu" nsURI="http://paasage.inria.fr/eu" nsPrefix="eu">
  <eSubpackages name="paasage" nsURI="http://paasage.inria.fr/eu/paasage" nsPrefix="paasage">
    <eSubpackages name="upperware" nsURI="http://paasage.inria.fr/eu/paasage/upperware"
        nsPrefix="upperware">
      <eSubpackages name="metamodel" nsURI="http://paasage.inria.fr/eu/paasage/upperware/metamodel"
          nsPrefix="metamodel">
        <eSubpackages name="application" nsURI="http://paasage.inria.fr/eu/paasage/upperware/metamodel/application"
            nsPrefix="application">
          <eClassifiers xsi:type="ecore:EClass" name="PaasageConfiguration">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="goals" upperBound="-1"
                eType="#//paasage/upperware/metamodel/application/PaaSageGoal" containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
                eType="#//paasage/upperware/metamodel/application/PaaSageVariable"
                containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="rules" upperBound="-1"
                eType="#//paasage/upperware/metamodel/application/ElasticityRule"
                containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
                eType="#//paasage/upperware/metamodel/application/ApplicationComponent"
                containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="providers" lowerBound="1"
                upperBound="-1" eType="#//paasage/upperware/metamodel/application/Provider"
                containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="vmProfiles" upperBound="-1"
                eType="#//paasage/upperware/metamodel/application/VirtualMachineProfile"
                containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="auxExpressions"
                upperBound="-1" eType="ecore:EClass cp.ecore#//paasage/upperware/metamodel/cp/Expression"
                containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="vms" upperBound="-1"
                eType="#//paasage/upperware/metamodel/application/VirtualMachine"
                containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="monitoredDimensions"
                upperBound="-1" eType="#//paasage/upperware/metamodel/application/Dimension"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="VirtualMachine" eSuperTypes="paasageTypes.ecore#//paasage/upperware/metamodel/types/typesPaasage/PaaSageCPElement">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="profile" lowerBound="1"
                eType="#//paasage/upperware/metamodel/application/VirtualMachineProfile"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="VirtualMachineProfile" eSuperTypes="#//paasage/upperware/metamodel/application/CloudMLElementUpperware">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" lowerBound="1"
                eType="ecore:EEnum paasageTypes.ecore#//paasage/upperware/metamodel/types/typesPaasage/VMSizeEnum"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="memory" eType="#//paasage/upperware/metamodel/application/Memory"
                containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="storage" eType="#//paasage/upperware/metamodel/application/Storage"
                containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="cpu" eType="#//paasage/upperware/metamodel/application/CPU"
                containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="os" eType="ecore:EClass paasageTypes.ecore#//paasage/upperware/metamodel/types/typesPaasage/OS"
                containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="providerDimension"
                upperBound="-1" eType="#//paasage/upperware/metamodel/application/ProviderDimension"
                containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="location" eType="ecore:EClass paasageTypes.ecore#//paasage/upperware/metamodel/types/typesPaasage/LocationUpperware"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="image" eType="#//paasage/upperware/metamodel/application/ImageUpperware"
                containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="relatedCloudVMId"
                lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="CloudMLElementUpperware" abstract="true">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="cloudMLId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="ResourceUpperware" abstract="true"
              eSuperTypes="paasageTypes.ecore#//paasage/upperware/metamodel/types/typesPaasage/PaaSageCPElement">
            <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1"
                eType="ecore:EClass paasageTypes.ecore#//paasage/upperware/metamodel/types/NumericValueUpperware"
                containment="true"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="Memory" eSuperTypes="#//paasage/upperware/metamodel/application/ResourceUpperware">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" eType="ecore:EEnum paasageTypes.ecore#//paasage/upperware/metamodel/types/typesPaasage/DataUnitEnum"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="Storage" eSuperTypes="#//paasage/upperware/metamodel/application/ResourceUpperware">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" eType="ecore:EEnum paasageTypes.ecore#//paasage/upperware/metamodel/types/typesPaasage/DataUnitEnum"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="CPU" eSuperTypes="#//paasage/upperware/metamodel/application/ResourceUpperware">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="frequency" eType="ecore:EEnum paasageTypes.ecore#//paasage/upperware/metamodel/types/typesPaasage/FrequencyEnum"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="cores" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="Provider" eSuperTypes="paasageTypes.ecore#//paasage/upperware/metamodel/types/typesPaasage/PaaSageCPElement">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="location" eType="ecore:EClass paasageTypes.ecore#//paasage/upperware/metamodel/types/typesPaasage/LocationUpperware"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
                eType="ecore:EClass paasageTypes.ecore#//paasage/upperware/metamodel/types/typesPaasage/ProviderType"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="ApplicationComponent" eSuperTypes="#//paasage/upperware/metamodel/application/CloudMLElementUpperware">
            <eStructuralFeatures xsi:type="ecore:EReference" name="vm" eType="#//paasage/upperware/metamodel/application/VirtualMachine"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="preferredLocations"
                upperBound="-1" eType="ecore:EClass paasageTypes.ecore#//paasage/upperware/metamodel/types/typesPaasage/LocationUpperware"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="requiredProfile"
                upperBound="-1" eType="#//paasage/upperware/metamodel/application/VirtualMachineProfile"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="features" upperBound="-1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="requiredFeatures"
                upperBound="-1" eType="#//paasage/upperware/metamodel/application/RequiredFeature"
                containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="preferredProviders"
                upperBound="-1" eType="ecore:EClass paasageTypes.ecore#//paasage/upperware/metamodel/types/typesPaasage/ProviderType"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="ElasticityRule">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="action" lowerBound="1"
                eType="#//paasage/upperware/metamodel/application/ActionUpperware"
                containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
                eType="#//paasage/upperware/metamodel/application/ConditionUpperware"
                containment="true"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="ActionUpperware">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameters" upperBound="-1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
                eType="ecore:EClass paasageTypes.ecore#//paasage/upperware/metamodel/types/typesPaasage/ActionType"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="ConditionUpperware" eSuperTypes="cp.ecore#//paasage/upperware/metamodel/cp/BooleanExpression">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
                eType="ecore:EEnum paasageTypes.ecore#//paasage/upperware/metamodel/types/typesPaasage/LogicOperatorEnum"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="exp1" lowerBound="1"
                eType="ecore:EClass cp.ecore#//paasage/upperware/metamodel/cp/BooleanExpression"
                containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="exp2" eType="ecore:EClass cp.ecore#//paasage/upperware/metamodel/cp/BooleanExpression"
                containment="true"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="PaaSageVariable">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="paasageType" eType="ecore:EEnum paasageTypes.ecore#//paasage/upperware/metamodel/types/typesPaasage/VariableElementTypeEnum"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="relatedComponent"
                eType="#//paasage/upperware/metamodel/application/ApplicationComponent"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="cpVariableId" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="relatedProvider"
                eType="#//paasage/upperware/metamodel/application/Provider"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="relatedVirtualMachineProfile"
                eType="#//paasage/upperware/metamodel/application/VirtualMachineProfile"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="PaaSageGoal">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="goal" lowerBound="1"
                eType="ecore:EEnum cp.ecore#//paasage/upperware/metamodel/cp/GoalOperatorEnum"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="function" lowerBound="1"
                eType="ecore:EClass paasageTypes.ecore#//paasage/upperware/metamodel/types/typesPaasage/FunctionType"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="applicationComponent"
                upperBound="-1" eType="#//paasage/upperware/metamodel/application/ComponentMetricRelationship"
                containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="applicationMetric"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="RequiredFeature">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="feature" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="providedBy" lowerBound="1"
                eType="#//paasage/upperware/metamodel/application/CloudMLElementUpperware"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="communicationType"
                lowerBound="1" eType="ecore:EEnum paasageTypes.ecore#//paasage/upperware/metamodel/types/typesPaasage/CommunicationTypeUpperware"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="optional" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="contaiment" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="Dimension">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="ProviderDimension">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="provider" lowerBound="1"
                eType="#//paasage/upperware/metamodel/application/Provider"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="metricID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
                defaultValueLiteral=""/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="ImageUpperware">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="ComponentMetricRelationship">
            <eStructuralFeatures xsi:type="ecore:EReference" name="component" lowerBound="1"
                eType="#//paasage/upperware/metamodel/application/ApplicationComponent"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="metricId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
          </eClassifiers>
        </eSubpackages>
      </eSubpackages>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
