<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="eu" nsURI="http://www.paasage.eu/eu" nsPrefix="eu">
  <eSubpackages name="paasage" nsURI="http://www.paasage.eu/eu/paasage" nsPrefix="paasage">
    <eSubpackages name="upperware" nsURI="http://www.paasage.eu/eu/paasage/upperware"
        nsPrefix="upperware">
      <eSubpackages name="metamodel" nsURI="http://www.paasage.eu/eu/paasage/upperware/metamodel"
          nsPrefix="metamodel">
        <eSubpackages name="types" nsURI="http://www.paasage.eu/eu/paasage/upperware/metamodel/types"
            nsPrefix="types">
          <eClassifiers xsi:type="ecore:EClass" name="ValueUpperware" abstract="true"/>
          <eClassifiers xsi:type="ecore:EClass" name="NumericValueUpperware" abstract="true"
              eSuperTypes="#//paasage/upperware/metamodel/types/ValueUpperware"/>
          <eClassifiers xsi:type="ecore:EClass" name="IntegerValueUpperware" eSuperTypes="#//paasage/upperware/metamodel/types/NumericValueUpperware">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="LongValueUpperware" eSuperTypes="#//paasage/upperware/metamodel/types/NumericValueUpperware">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="FloatValueUpperware" eSuperTypes="#//paasage/upperware/metamodel/types/NumericValueUpperware">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="DoubleValueUpperware" eSuperTypes="#//paasage/upperware/metamodel/types/NumericValueUpperware">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EEnum" name="BasicTypeEnum">
            <eLiterals name="Integer"/>
            <eLiterals name="Float" value="1"/>
            <eLiterals name="Double" value="2"/>
            <eLiterals name="Long" value="3"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="StringValueUpperware" eSuperTypes="#//paasage/upperware/metamodel/types/ValueUpperware">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="BooleanValueUpperware" eSuperTypes="#//paasage/upperware/metamodel/types/ValueUpperware">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
          </eClassifiers>
          <eSubpackages name="typesPaasage" nsURI="http://www.paasage.eu/eu/paasage/upperware/metamodel/types/typesPaasage"
              nsPrefix="typesPaasage">
            <eClassifiers xsi:type="ecore:EEnum" name="FrequencyEnum">
              <eLiterals name="MHz"/>
              <eLiterals name="GHz" value="1"/>
            </eClassifiers>
            <eClassifiers xsi:type="ecore:EEnum" name="VMSizeEnum">
              <eLiterals name="XS" literal="XS"/>
              <eLiterals name="S" value="1" literal="S"/>
              <eLiterals name="L" value="2" literal="L"/>
              <eLiterals name="XL" value="3" literal="XL"/>
              <eLiterals name="XXL" value="4" literal="XXL"/>
              <eLiterals name="A6" value="5" literal="A6"/>
              <eLiterals name="A7" value="6" literal="A7"/>
            </eClassifiers>
            <eClassifiers xsi:type="ecore:EEnum" name="LogicOperatorEnum">
              <eLiterals name="And" literal="And"/>
              <eLiterals name="Or" value="1" literal="Or"/>
            </eClassifiers>
            <eClassifiers xsi:type="ecore:EEnum" name="DataUnitEnum">
              <eLiterals name="MB" literal="MB"/>
              <eLiterals name="GB" value="1" literal="GB"/>
              <eLiterals name="TB" value="2" literal="TB"/>
            </eClassifiers>
            <eClassifiers xsi:type="ecore:EEnum" name="VariableElementTypeEnum">
              <eLiterals name="GeoLocation" literal="GeoLocation"/>
              <eLiterals name="PhysicalLoccation" value="1" literal="PhysicalLoccation"/>
              <eLiterals name="VirtualLocation" value="2" literal="VirtualLocation"/>
              <eLiterals name="ResponseTime" value="3" literal="ResponseTime"/>
              <eLiterals name="Provider" value="4" literal="Provider"/>
              <eLiterals name="Bandwidth" value="5"/>
              <eLiterals name="Users" value="6"/>
              <eLiterals name="Quantity" value="7"/>
            </eClassifiers>
            <eClassifiers xsi:type="ecore:EClass" name="PaaSageCPElement" abstract="true">
              <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeId" lowerBound="1"
                  eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
            </eClassifiers>
            <eClassifiers xsi:type="ecore:EClass" name="OS" eSuperTypes="#//paasage/upperware/metamodel/types/typesPaasage/PaaSageCPElement">
              <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
                  eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
              <eStructuralFeatures xsi:type="ecore:EAttribute" name="vers" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
              <eStructuralFeatures xsi:type="ecore:EAttribute" name="architecture"
                  lowerBound="1" eType="#//paasage/upperware/metamodel/types/typesPaasage/OSArchitectureEnum"/>
            </eClassifiers>
            <eClassifiers xsi:type="ecore:EClass" name="LocationUpperware" abstract="true"
                eSuperTypes="#//paasage/upperware/metamodel/types/typesPaasage/PaaSageCPElement">
              <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
                  eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
              <eStructuralFeatures xsi:type="ecore:EAttribute" name="alternativeNames"
                  upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            </eClassifiers>
            <eClassifiers xsi:type="ecore:EClass" name="ContinentUpperware" eSuperTypes="#//paasage/upperware/metamodel/types/typesPaasage/LocationUpperware"/>
            <eClassifiers xsi:type="ecore:EClass" name="CountryUpperware" eSuperTypes="#//paasage/upperware/metamodel/types/typesPaasage/LocationUpperware">
              <eStructuralFeatures xsi:type="ecore:EReference" name="continent" eType="#//paasage/upperware/metamodel/types/typesPaasage/ContinentUpperware"/>
            </eClassifiers>
            <eClassifiers xsi:type="ecore:EClass" name="CityUpperware" eSuperTypes="#//paasage/upperware/metamodel/types/typesPaasage/LocationUpperware">
              <eStructuralFeatures xsi:type="ecore:EReference" name="country" eType="#//paasage/upperware/metamodel/types/typesPaasage/CountryUpperware"/>
            </eClassifiers>
            <eClassifiers xsi:type="ecore:EClass" name="Locations">
              <eStructuralFeatures xsi:type="ecore:EReference" name="locations" lowerBound="1"
                  upperBound="-1" eType="#//paasage/upperware/metamodel/types/typesPaasage/LocationUpperware"
                  containment="true"/>
            </eClassifiers>
            <eClassifiers xsi:type="ecore:EClass" name="ApplicationComponentProfile"
                abstract="true">
              <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
                  eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
              <eStructuralFeatures xsi:type="ecore:EAttribute" name="vers" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
              <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
                  eType="#//paasage/upperware/metamodel/types/typesPaasage/ApplicationComponentType"/>
            </eClassifiers>
            <eClassifiers xsi:type="ecore:EClass" name="ApplicationComponentProfiles">
              <eStructuralFeatures xsi:type="ecore:EReference" name="profiles" lowerBound="1"
                  upperBound="-1" eType="#//paasage/upperware/metamodel/types/typesPaasage/ApplicationComponentProfile"
                  containment="true"/>
            </eClassifiers>
            <eClassifiers xsi:type="ecore:EClass" name="OperatingSystems">
              <eStructuralFeatures xsi:type="ecore:EReference" name="oss" lowerBound="1"
                  upperBound="-1" eType="#//paasage/upperware/metamodel/types/typesPaasage/OS"
                  containment="true"/>
            </eClassifiers>
            <eClassifiers xsi:type="ecore:EClass" name="DatabaseProfile" eSuperTypes="#//paasage/upperware/metamodel/types/typesPaasage/ApplicationComponentProfile"/>
            <eClassifiers xsi:type="ecore:EClass" name="WebServerProfile" eSuperTypes="#//paasage/upperware/metamodel/types/typesPaasage/ApplicationComponentProfile"/>
            <eClassifiers xsi:type="ecore:EClass" name="ApplicationServerProfile"
                eSuperTypes="#//paasage/upperware/metamodel/types/typesPaasage/ApplicationComponentProfile"/>
            <eClassifiers xsi:type="ecore:EClass" name="WarProfile" eSuperTypes="#//paasage/upperware/metamodel/types/typesPaasage/ApplicationComponentProfile"/>
            <eClassifiers xsi:type="ecore:EClass" name="JarProfile" eSuperTypes="#//paasage/upperware/metamodel/types/typesPaasage/ApplicationComponentProfile"/>
            <eClassifiers xsi:type="ecore:EClass" name="ApplicationComponentType">
              <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1"
                  eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            </eClassifiers>
            <eClassifiers xsi:type="ecore:EClass" name="ProviderType">
              <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1"
                  eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            </eClassifiers>
            <eClassifiers xsi:type="ecore:EClass" name="ProviderTypes">
              <eStructuralFeatures xsi:type="ecore:EReference" name="types" lowerBound="1"
                  upperBound="-1" eType="#//paasage/upperware/metamodel/types/typesPaasage/ProviderType"
                  containment="true"/>
            </eClassifiers>
            <eClassifiers xsi:type="ecore:EClass" name="ApplicationComponentTypes">
              <eStructuralFeatures xsi:type="ecore:EReference" name="types" lowerBound="1"
                  upperBound="-1" eType="#//paasage/upperware/metamodel/types/typesPaasage/ApplicationComponentType"
                  containment="true"/>
            </eClassifiers>
            <eClassifiers xsi:type="ecore:EClass" name="ActionType">
              <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1"
                  eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            </eClassifiers>
            <eClassifiers xsi:type="ecore:EClass" name="ActionTypes">
              <eStructuralFeatures xsi:type="ecore:EReference" name="types" lowerBound="1"
                  upperBound="-1" eType="#//paasage/upperware/metamodel/types/typesPaasage/ActionType"
                  containment="true"/>
            </eClassifiers>
            <eClassifiers xsi:type="ecore:EClass" name="FunctionType">
              <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1"
                  eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            </eClassifiers>
            <eClassifiers xsi:type="ecore:EClass" name="FunctionTypes">
              <eStructuralFeatures xsi:type="ecore:EReference" name="types" lowerBound="1"
                  upperBound="-1" eType="#//paasage/upperware/metamodel/types/typesPaasage/FunctionType"
                  containment="true"/>
            </eClassifiers>
            <eClassifiers xsi:type="ecore:EEnum" name="OSArchitectureEnum">
              <eLiterals name="thirty_two_bits" value="32" literal="32bits"/>
              <eLiterals name="sixty_four_bits" value="64" literal="64bits"/>
            </eClassifiers>
            <eClassifiers xsi:type="ecore:EEnum" name="CommunicationTypeUpperware">
              <eLiterals name="Local" literal="Local"/>
              <eLiterals name="Remote" value="1" literal="Remote"/>
              <eLiterals name="Any" value="2" literal="Any"/>
            </eClassifiers>
          </eSubpackages>
        </eSubpackages>
      </eSubpackages>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
