package eu.melodic.upperware.adapter.plangenerator;

public enum TaskType {

  CLOUD_API, CLOUD, CLOUD_PROPERTY, CLOUD_CREDENTIAL,
  APPLICATION, APPLICATION_INSTANCE,
  VIRTUALMACHINE, VIRTUALMACHINE_INSTANCE,
  LIFECYCLE,
  APPLICATION_COMPONENT, APPLICATION_COMPONENT_INSTANCE,
  PORT_PROVIDED, PORT_REQUIRED, COMMUNICATION,
  VM_INSTANCE_MONITOR, APP_COMP_INSTANCE_MONITOR

}
