jwt.secret=mE1odiCl0ud
jwt.expirationTime=86400000
jwt.refreshTokenExpirationTime=8640000
ldap.url=ldap://melodic-ldap
ldap.partitionSuffix=dc=example,dc=org
ldap.principal=cn=admin,dc=example,dc=org
ldap.password=
### logback configuration ###
logging.config=file:${MELODIC_CONFIG_DIR}/logback-conf/logback-spring.xml


