# ZEROMQ: Subscriber
SUBSCRIBER_PROTOCOL=tcp://
SUBSCRIBER_HOST=localhost
SUBSCRIBER_PORT=5544
SUBSCRIBER_TOPIC=startSolving

# ZEROMQ: Publisher
PUBLISHER_PROTOCOL=tcp://
PUBLISHER_HOST=*
PUBLISHER_PORT=5545
PUBLISHER_TOPIC=RPSolutionAvailable

# TMP DIRECTORY
RP_TEMP_DIR=/tmp/

# CONFIGURATION DIRECTORY
PAASAGE_CONFIG_DIR=/etc/paasage/

# LOGGING
log4j.rootLogger=info, stdout
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.Target=System.out
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d{ABSOLUTE} %5p %c{1}:%L - %m%n
