#properties
#number of instances to consider from the database (not using this in the application atm)
recordsConsider=5000
#time interval in seconds to update
timeInterval=300
#time to purge old records in seconds
timePurge = 2000
#timePurge = 6000
#in ms
bestLatency=5
worstLatency=2000
#in Mbps
bestBandwidth=1024
worstBandwidth=1
#algorithm function, options 1) average, 2) latest_higher
function=latest_higher
#number of records to generate each second
numRecordGenerate = 20