#
# Copyright (C) 2017 7bulls.com
#
# This Source Code Form is subject to the terms of the
# Mozilla Public License, v. 2.0. If a copy of the MPL
# was not distributed with this file, You can obtain one at
# http://mozilla.org/MPL/2.0/.
#

#### Communication with ESB ####

esb.url=http://94.177.187.234:8088


#### Communication with Colosseum ####

# REST API URL
colosseum.url=http://94.177.187.234:8089/api/adapter/cloudiatorProxy/api

# Credentials used to authorize requests to API
colosseum.auth.email=john.doe@example.com
colosseum.auth.password=admin
colosseum.auth.tenant=admin

# Timeouts in millis used while waiting for Colosseum to download locations, hardware, images and operating systems
colosseum.timeouts.image=100000
colosseum.timeouts.os=100000
colosseum.timeouts.location=200000
colosseum.timeouts.hardware=100000

# Timeouts in millis used while waiting for Colosseum to start VM instances and AC instances
colosseum.timeouts.vmInst=180000
colosseum.timeouts.acInst=180000


#### Endpoints and credentials used to authorize requests to Cloud APIs (via Colosseum) ####

# For adding new cloud provider:
#   a) copy cloud.endpoints.*, cloud.credentials.* and if needed cloud.filter.* lines
#   b) replace cloud provider name in each line and set correct values of properties
#   c) new cloud will be supported by the Adapter without any code modification
# Lines below you can consider as examples
#
# NOTE: Endpoints will be overwrote if they are defined in Camel Model
#

clouds.endpoints.flexiant=https://cp.sd1.flexiant.net/soap/user/current
clouds.logins.flexiant=
clouds.passwords.flexiant=

clouds.endpoints.omnistack=http://omistack-beta.e-technik.uni-ulm.de:5000/v2.0
clouds.logins.omnistack=
clouds.passwords.omnistack=

clouds.endpoints.ec2=https://ec2.eu-west-1.amazonaws.com
clouds.logins.ec2=
clouds.passwords.ec2=
clouds.filters.keys.ec2=sword.ec2.ami.query, sword.ec2.default.vpc
clouds.filters.values.ec2=state=available;image-type=machine;, subnet-284p3459


#### Spring thread pool task executor config (used for concurrent calling tasks generated by Plan Generator) ####

taskExecutor.corePoolSize=4
taskExecutor.maxPoolSize=4
taskExecutor.queueCapacity=

#### Logback-config
logging.config=file:${MELODIC_CONFIG_DIR}/logback-conf/logback-spring.xml

# ProActive config
pa-rest.url=http://trydev.activeeon.com:8080/rest
pa-rest.login=9MsPgBv+3kZoeE6qsJjhJw==
pa-rest.password=y3VeZGcHmaL0AJAUqv7JHStmZubtOKWE
