# Baguette Server credentials
host = BAGUETTE_SERVER_HOST
port = BAGUETTE_SERVER_PORT
pubkey = BAGUETTE_SERVER_PUBKEY
fingerprint = BAGUETTE_SERVER_FINGERPRINT

username = BAGUETTE_SERVER_USERNAME
password = BAGUETTE_SERVER_PASSWORD
