<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="fr" nsURI="fr" nsPrefix="fr">
  <eSubpackages name="inria" nsURI="inria" nsPrefix="inria">
    <eSubpackages name="paasage" nsURI="paasage" nsPrefix="paasage">
      <eSubpackages name="saloon" nsURI="saloon" nsPrefix="saloon">
        <eSubpackages name="camel" nsURI="http://fr.inria.paasage.saloon.camel" nsPrefix="camel">
          <eSubpackages name="mapping" nsURI="http://fr.inria.paasage.saloon.camel.mapping"
              nsPrefix="mapping">
            <eClassifiers xsi:type="ecore:EClass" name="ConceptToFeatureCamel" eSuperTypes="#//inria/paasage/saloon/camel/mapping/MappingCamel">
              <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1"
                  eType="ecore:EClass OntologyCamel.ecore#//inria/paasage/saloon/camel/ontology/ConceptCamel"/>
              <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1"
                  eType="ecore:EClass camel.ecore#//provider/Feature"/>
            </eClassifiers>
            <eClassifiers xsi:type="ecore:EClass" name="MappingListCamel">
              <eStructuralFeatures xsi:type="ecore:EReference" name="mappings" upperBound="-1"
                  eType="#//inria/paasage/saloon/camel/mapping/MappingCamel" containment="true"/>
              <eStructuralFeatures xsi:type="ecore:EReference" name="providerModel"
                  lowerBound="1" eType="ecore:EClass camel.ecore#//provider/ProviderModel"/>
            </eClassifiers>
            <eClassifiers xsi:type="ecore:EClass" name="ConceptToAttributeCamel" eSuperTypes="#//inria/paasage/saloon/camel/mapping/MappingCamel">
              <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1"
                  eType="ecore:EClass OntologyCamel.ecore#//inria/paasage/saloon/camel/ontology/ConceptCamel"/>
              <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1"
                  eType="ecore:EClass camel.ecore#//provider/Attribute"/>
            </eClassifiers>
            <eClassifiers xsi:type="ecore:EClass" name="MappingCamel" abstract="true"/>
            <eClassifiers xsi:type="ecore:EClass" name="BooleanExpressionCamel" eSuperTypes="#//inria/paasage/saloon/camel/mapping/ExpressionCamel">
              <eStructuralFeatures xsi:type="ecore:EReference" name="element" lowerBound="1"
                  eType="ecore:EClass OntologyCamel.ecore#//inria/paasage/saloon/camel/ontology/QuantifiableElementCamel"/>
              <eStructuralFeatures xsi:type="ecore:EAttribute" name="relationship"
                  lowerBound="1" eType="#//inria/paasage/saloon/camel/mapping/ComparatorEnumCamel"/>
              <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1"
                  eType="ecore:EClass camel.ecore#//type/NumericValue" containment="true"/>
            </eClassifiers>
            <eClassifiers xsi:type="ecore:EEnum" name="ComparatorEnumCamel">
              <eLiterals name="equal"/>
              <eLiterals name="equalOrLessThan" value="1"/>
              <eLiterals name="lessThan" value="2"/>
              <eLiterals name="equalOrGreaterThan" value="3"/>
              <eLiterals name="greaterThan" value="4"/>
            </eClassifiers>
            <eClassifiers xsi:type="ecore:EEnum" name="LogicalOperatorEnumCamel">
              <eLiterals name="and"/>
              <eLiterals name="or" value="1"/>
            </eClassifiers>
            <eClassifiers xsi:type="ecore:EClass" name="ConditionCamel" eSuperTypes="#//inria/paasage/saloon/camel/mapping/ExpressionCamel">
              <eStructuralFeatures xsi:type="ecore:EReference" name="exp1" lowerBound="1"
                  eType="#//inria/paasage/saloon/camel/mapping/ExpressionCamel" containment="true"/>
              <eStructuralFeatures xsi:type="ecore:EReference" name="exp2" eType="#//inria/paasage/saloon/camel/mapping/ExpressionCamel"
                  containment="true"/>
              <eStructuralFeatures xsi:type="ecore:EAttribute" name="connector" eType="#//inria/paasage/saloon/camel/mapping/LogicalOperatorEnumCamel"/>
            </eClassifiers>
            <eClassifiers xsi:type="ecore:EClass" name="ExpressionCamel" abstract="true"/>
            <eClassifiers xsi:type="ecore:EClass" name="MappingRuleCamel" eSuperTypes="#//inria/paasage/saloon/camel/mapping/MappingCamel">
              <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
                  eType="#//inria/paasage/saloon/camel/mapping/ExpressionCamel" containment="true"/>
              <eStructuralFeatures xsi:type="ecore:EReference" name="assignment" lowerBound="1"
                  eType="#//inria/paasage/saloon/camel/mapping/ValueAssignmentCamel"
                  containment="true"/>
            </eClassifiers>
            <eClassifiers xsi:type="ecore:EClass" name="ValueAssignmentCamel">
              <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" lowerBound="1"
                  eType="ecore:EClass camel.ecore#//provider/Attribute"/>
              <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1"
                  eType="ecore:EClass camel.ecore#//type/SingleValue" containment="true"/>
              <eStructuralFeatures xsi:type="ecore:EReference" name="associations"
                  upperBound="-1" eType="#//inria/paasage/saloon/camel/mapping/AssociationCamel"
                  containment="true"/>
            </eClassifiers>
            <eClassifiers xsi:type="ecore:EClass" name="AssociationCamel">
              <eStructuralFeatures xsi:type="ecore:EReference" name="concept" lowerBound="1"
                  eType="ecore:EClass OntologyCamel.ecore#//inria/paasage/saloon/camel/ontology/QuantifiableElementCamel"/>
              <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="ecore:EClass camel.ecore#//type/NumericValue"/>
            </eClassifiers>
          </eSubpackages>
        </eSubpackages>
      </eSubpackages>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
