<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cardSemantics" nsURI="http://fr.saloon.model.cardSemantics"
    nsPrefix="cardSemantics">
  <eClassifiers xsi:type="ecore:EClass" name="cardRepository">
    <eStructuralFeatures xsi:type="ecore:EReference" name="levels" upperBound="-1"
        eType="#//Level" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scopes" upperBound="-1"
        eType="#//Scope" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Level" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Global" eSuperTypes="#//Level"/>
  <eClassifiers xsi:type="ecore:EClass" name="Local" eSuperTypes="#//Level"/>
  <eClassifiers xsi:type="ecore:EClass" name="Scope" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureScope" eSuperTypes="#//Scope"/>
  <eClassifiers xsi:type="ecore:EClass" name="CloneScope" eSuperTypes="#//Scope"/>
</ecore:EPackage>
