# Baguette Client configuration

auth.timeout = 60000
exec.timeout = 120000

broker.command.windows = cmd.exe /c bin\\broker.bat
broker.command.linux = bin/broker.sh
broker.command.mac = broker
broker.command.other = broker

client.command.windows = cmd.exe /c bin\\client.bat
client.command.linux = bin/client.sh
client.command.mac = client
client.command.other = client
