#
# Copyright (C) 2017 Institute of Communication and Computer Systems (imu.iccs.com)
#
# This Source Code Form is subject to the terms of the
# Mozilla Public License, v. 2.0. If a copy of the MPL
# was not distributed with this file, You can obtain one at
# http://mozilla.org/MPL/2.0/.
#

#//XXX:TEST: Baguette client Broker-CEP config. when testing in the same machine with Server (which also uses port 61616)
brokercep.broker-name = broker
brokercep.connector-port = 1088
brokercep.broker-url = tcp://localhost:61615