#
# Copyright (C) 2017-2022 Institute of Communication and Computer Systems (imu.iccs.gr)
#
# This Source Code Form is subject to the terms of the Mozilla Public License, v2.0, unless
# Esper library is used, in which case it is subject to the terms of General Public License v2.0.
# If a copy of the MPL was not distributed with this file, you can obtain one at
# https://www.mozilla.org/en-US/MPL/2.0/
#

# Baguette Client configuration

auth-timeout = 60000
exec-timeout = 120000
#retry-period = 60000
exit-command-allowed = false
#kill-delay = 10

IP_SETTING=${IP_SETTING}

# -----------------------------------------------------------------------------
# Client Id and Baguette Server credentials
# -----------------------------------------------------------------------------

client-id = ${BAGUETTE_CLIENT_ID}

server-address = ${BAGUETTE_SERVER_HOSTNAME}
#server-address = ${BAGUETTE_SERVER_ADDRESS}
server-port = ${BAGUETTE_SERVER_PORT}
server-pubkey = ${BAGUETTE_SERVER_PUBKEY}
server-fingerprint = ${BAGUETTE_SERVER_PUBKEY_FINGERPRINT}

server-username = ${BAGUETTE_SERVER_USERNAME}
server-password = ${BAGUETTE_SERVER_PASSWORD}

# -----------------------------------------------------------------------------
# Collectors settings
# -----------------------------------------------------------------------------

#collector-classes = eu.melodic.event.baguette.client.collector.netdata.NetdataCollector

collector.netdata.enable = true
collector.netdata.delay = 10000
collector.netdata.url = http://127.0.0.1:19999/api/v1/allmetrics?format=json
#collector.netdata.create-topic = true
#collector.netdata.allowed-topics = netdata__system__cpu__user:an_alias

# -----------------------------------------------------------------------------
# Cluster settings
# -----------------------------------------------------------------------------

#cluster.cluster-id=cluster
#cluster.local-node.id=local-node
#cluster.local-node.address=localhost:1234
#cluster.local-node.properties.name=value
#cluster.member-addresses=[localhost:3456, localhost:5678]

#cluster.useSwim=false
#cluster.failureTimeout=5000
cluster.testInterval=5000

cluster.log-enabled=false
cluster.out-enabled=true

cluster.join-on-init=true
cluster.election-on-join=false
#cluster.usePBInMg=true
#cluster.usePBInPg=true
#cluster.mgName=system
#cluster.pgName=data

cluster.tls.enabled=false
#cluster.tls.keystore=${MELODIC_CONFIG_DIR}/cluster.jks
#cluster.tls.keystore-password=atomix
#cluster.tls.truststore=${MELODIC_CONFIG_DIR}/cluster.jks
#cluster.tls.truststore-password=atomix
cluster.tls.keystore-dir=conf

cluster.score.formula=20*cpu/32+80*ram/(256*1024)
cluster.score.default-score=0
cluster.score.default-args.cpu=1
cluster.score.default-args.ram=128
#cluster.score.throw-exception=false
