#

pluginName = Camel Model
providerName = www.example.org
_UI_DiagnosticRoot_diagnostic=_UI_DiagnosticRoot_diagnostic
_UI_RequiredFeatureMustBeSet_diagnostic=_UI_RequiredFeatureMustBeSet_diagnostic
_UI_ConstraintDelegateNotFound_diagnostic=_UI_ConstraintDelegateNotFound_diagnostic
_UI_DanglingReference_diagnostic=_UI_DanglingReference_diagnostic