# Client 1

client.id	UUID-WM_TwoComponentAppVMInstance_1_10
debug.fake-ip-address	34.243.144.177

# VMS Discovery Server credentials
host = 127.0.0.1
port = 2222
pubkey = AAAAB3NzaC1yc2EAAAADAQABAAABAQDKAyYAkXcrRat3qKawSipfZJPsmoGTggin+GIoA/0DJ8xc+3vGYAV0J6EAtDZyFKFYWzWamfpsb08wRGkFTLzXcfW+MRvRYauoAzSFBozKNKq8ycn3x0PIySnZOI3B1SIR9sgJMTyT32QPI8IhxNE78ZPf+rhEaAIjG/T7hnnhkAJ+OvAmhYb3T2x0W2mlmj0JPihUynsoCdQFSt7UARvzG/UIRBmdZ//DRqUn919gf9mLOfQ9zVhrpSq75/cqGwXM1c+UYBYWtnJS2UyWKlMwFe3y6mTtlyWfD3Jn03ZFNCX5q3UDQhcdKj4kMI6xdRn6AnfpfXWPbiK2cMvH9ZXJ
fingerprint = SHA256:9iANcu6iK6UePw0n1DwKwUTeS8MF2W/ih+lUewXgL0A

username = bb
password = yy
