package eu.melodic.upperware.guibackend.controller.user.request;

import eu.melodic.upperware.guibackend.model.user.UserRole;
import lombok.*;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class NewUserRequest extends NewUserAutogeneratedPasswordRequest {

    private String password;

    private String passwordConfirmation;

    @Builder
    public NewUserRequest(String username, UserRole userRole, String password, String passwordConfirmation) {
        super(username, userRole);
        this.password = password;
        this.passwordConfirmation = passwordConfirmation;
    }
}
