package eu.melodic.upperware.guibackend.controller.user.request;

import eu.melodic.upperware.guibackend.model.user.UserRole;
import lombok.*;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class NewUserRequest extends NewUserAutogeneratedPasswordRequest {

    private String password;
    private String passwordConfirmation;
    private String fullName;
    private String mail;
    @Builder
    public NewUserRequest(String username, UserRole userRole, String password, String passwordConfirmation, String fullName, String mail) {
        super(username, userRole, fullName, mail);
        this.password = password;
        this.passwordConfirmation = passwordConfirmation;
    }
}
