name: Build EMS Core Platform (Server + Client)

on:
  push:
    branches:
      - main
    tags:
      - "v*"
      - "r*"
      - "test"

permissions:
  contents: read
  packages: write

env:
  CORE_VERSION: 8.0.0-snapshot
  REGISTRY: ghcr.io/imu-iccs


jobs:

  # -------------------------------------------------------
  # 1. Collect metadata
  # -------------------------------------------------------
  metadata:
    runs-on: ubuntu-latest
    outputs:
      safe_time: ${{ steps.meta.outputs.safe_time }}

    steps:
      - uses: actions/checkout@v4

      - id: meta
        run: |
          COMMIT_DATE=$(git show -s --format=%cI HEAD)
          SAFE_TIME=$(date -u -d "$COMMIT_DATE" +"%Y%m%dT%H%M%SZ")
          echo "safe_time=$SAFE_TIME" >> "$GITHUB_OUTPUT"

  # -------------------------------------------------------
  # 2. Build and publish
  # -------------------------------------------------------
  build-and-publish:
    needs: metadata
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      #
      # Publish all images
      #
      - name: Build and publish all images
        run: |
          export CORE_VERSION="${{ env.core_version }}"
          export REGISTRY="${{ env.REGISTRY }}"
          export COMMIT_SHA="${{ github.sha }}"
          export COMMIT_SAFE_TIME="${{ needs.metadata.outputs.safe_time }}"
          
          echo "=============================================================" >> "$GITHUB_OUTPUT"
          echo "CORE_VERSION=$CORE_VERSION" >> "$GITHUB_OUTPUT"
          echo "REGISTRY=$REGISTRY" >> "$GITHUB_OUTPUT"
          echo "COMMIT_SHA=$COMMIT_SHA" >> "$GITHUB_OUTPUT"
          echo "COMMIT_SAFE_TIME=$COMMIT_SAFE_TIME" >> "$GITHUB_OUTPUT"
          echo "=============================================================" >> "$GITHUB_OUTPUT"

          docker buildx bake \
            --push